# Overview

This notebook implements a full ML pipeline:
- data processing
- feature engineering
- modeling
- evaluation

The focus is on maintaining data integrity and exploring model performance across multiple configurations.

# 1. Setup & Imports

This section contains all required libraries and initial setup.

In [1]:
import pandas as pd
import gc
import os
import json
import dask.dataframe as dd
from joblib import Parallel, delayed
import multiprocessing
import joblib

from tqdm import tqdm

from sklearn.utils.class_weight import compute_class_weight
from sklearn.model_selection import train_test_split, GridSearchCV
from itertools import product
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score
from sklearn.inspection import permutation_importance
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold

import numpy as np
from scipy.stats import rankdata
import matplotlib.pyplot as plt
import seaborn as sns

from catboost import CatBoostClassifier
from catboost import Pool
from lightgbm import LGBMClassifier, early_stopping, log_evaluation
import lightgbm as lgb
from xgboost import XGBClassifier, callback
import xgboost as xgb

In [2]:
path = r"C:\Users\User\-_PRACTICAL\junior-final-work\train_data"

In [3]:
sample_120k = pd.read_csv('sample_120k.csv')

In [3]:
data = pd.read_csv('full_data13.csv')

# 2. Data Pipeline Functions

This section defines reusable functions for:
- loading and merging data from multiple files
- memory optimization
- feature engineering pipeline

Note: functions are grouped together for convenience, although they cover multiple pipeline stages.

## functions

In [8]:
def reduce_mem_usage(df, int_cast=True, obj_to_category=True, subset=None):
    """
    Iterate through all the columns of a dataframe and modify the data type to reduce memory usage.
    :param df: dataframe to reduce (pd.DataFrame)
    :param int_cast: indicate if columns should be tried to be casted to int (bool)
    :param obj_to_category: convert non-datetime related objects to category dtype (bool)
    :param subset: subset of columns to analyse (list)
    :return: dataset with the column dtypes adjusted (pd.DataFrame)
    """
    start_mem = df.memory_usage().sum() / 1024 ** 2;
    gc.collect()
    print('Memory usage of dataframe is {:.2f} MB'.format(start_mem))

    cols = subset if subset is not None else df.columns.tolist()

    for col in tqdm(cols):

        col_type = df[col].dtype

        if col_type != object and col_type.name != 'category' and 'datetime' not in col_type.name:
            c_min = df[col].min()
            c_max = df[col].max()

            # test if column can be converted to an integer
            treat_as_int = str(col_type)[:3] == 'int'
            # if int_cast and not treat_as_int:
            #     treat_as_int = check_if_integer(df[col])

            if treat_as_int:
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.uint8).min and c_max < np.iinfo(np.uint8).max:
                    df[col] = df[col].astype(np.uint8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.uint16).min and c_max < np.iinfo(np.uint16).max:
                    df[col] = df[col].astype(np.uint16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                elif c_min > np.iinfo(np.uint32).min and c_max < np.iinfo(np.uint32).max:
                    df[col] = df[col].astype(np.uint32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)
                elif c_min > np.iinfo(np.uint64).min and c_max < np.iinfo(np.uint64).max:
                    df[col] = df[col].astype(np.uint64)
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    df[col] = df[col].astype(np.float16)
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)
        elif 'datetime' not in col_type.name and obj_to_category:
            df[col] = df[col].astype('category')
    gc.collect()
    end_mem = df.memory_usage().sum() / 1024 ** 2
    print('Memory usage after optimization is: {:.3f} MB'.format(end_mem))
    print('Decreased by {:.1f}%'.format(100 * (start_mem - end_mem) / start_mem))

    return df

In [9]:
def read_parquet_dataset_from_local(path_to_dataset: str, file_name_tag: str, start_from: int = 0,
                                     num_parts_to_read: int = 2, columns=None, verbose=False) -> pd.DataFrame:
    """
    читает num_parts_to_read партиций, преобразует их к pd.DataFrame и возвращает
    :param path_to_dataset: путь до директории с партициями
    :param start_from: номер партиции, с которой начать чтение
    :param num_parts_to_read: количество партиций, которые требуется прочитать
    :param columns: список колонок, которые нужно прочитать из партиции
    :return: pd.DataFrame
    """

    res = []
    dataset_paths = sorted([os.path.join(path_to_dataset, filename) for filename in os.listdir(path_to_dataset)
                              if filename.startswith(file_name_tag)])

    start_from = max(0, start_from)
    chunks = dataset_paths[start_from: start_from + num_parts_to_read]
    if verbose:
        print('Reading chunks:\n')
        for chunk in chunks:
            print(chunk)
    for chunk_path in tqdm(chunks, desc="Reading dataset with pandas"):
        print('chunk_path', chunk_path)
        chunk = pd.read_parquet(chunk_path,columns=columns)
        chunk = reduce_mem_usage(chunk)
        res.append(chunk)
        del chunk
        gc.collect()

    return pd.concat(res).fillna(0).reset_index(drop=True)

### pipeline

In [6]:
def prepare_transactions_dataset(path_to_dataset: str, file_name_tag: str, num_parts_to_preprocess_at_once: int = 1, num_parts_total: int=50,
                                 save_to_path=None, verbose: bool=False):
    """
    возвращает готовый pd.DataFrame с признаками, на которых можно учить модель для целевой задачи.
    path_to_dataset: str
        путь до датасета с партициями
    num_parts_to_preprocess_at_once: int
        количество партиций, которые будут одновременно держаться в памяти и обрабатываться
    num_parts_total: int
        общее количество партиций, которые нужно обработать
    save_to_path: str
        путь до папки, в которой будет сохранен каждый обработанный блок в .parquet формате. Если None, то не будет сохранен
    verbose: bool
        логирует каждый обрабатываемый кусок данных
    """
    preprocessed_frames = []

    for step in tqdm(range(0, num_parts_total, num_parts_to_preprocess_at_once),
                               desc="Transforming transactions data"):
        transactions_frame = read_parquet_dataset_from_local(
            path_to_dataset, file_name_tag, step, num_parts_to_preprocess_at_once,
            verbose=verbose
        )

        # === базовые колонки ===
        paym_cols = [f"enc_paym_{i}" for i in range(24)]  # FIX: используем все 0..23

        # === платежные фичи ===
        transactions_frame["paym_bad_count"] = (transactions_frame[paym_cols] > 0).sum(axis=1)
        transactions_frame["paym_severe_count"] = (transactions_frame[paym_cols] >= 2).sum(axis=1)
        transactions_frame["paym_nonzero_share"] = (transactions_frame[paym_cols] > 0).mean(axis=1)
        transactions_frame["paym_mean_status"] = transactions_frame[paym_cols].mean(axis=1)
        transactions_frame["enc_paym_weighted_score"] = transactions_frame[paym_cols].sum(axis=1)

        # === сортировка (ВАЖНО для last) ===
        transactions_frame = transactions_frame.sort_values(['id', 'rn'])

        # === клиентские агрегаты (до groupby) ===
        grp = transactions_frame.groupby('id')

        # utilization
        transactions_frame['utilization_ratio'] = (
            transactions_frame['pre_loans_outstanding'] /
            (transactions_frame['pre_loans_credit_limit'] + 1e-6)
        )

        # last loan flag
        transactions_frame["is_last_loan"] = (
            transactions_frame["rn"] == grp["rn"].transform("max")
        ).astype(int)

        # previous loan features
        transactions_frame["prev_util"] = grp["utilization_ratio"].shift(1)
        transactions_frame["prev_paym"] = grp["paym_mean_status"].shift(1)

        transactions_frame["last_vs_prev_util"] = (
            transactions_frame["utilization_ratio"] - transactions_frame["prev_util"]
        )
        transactions_frame["last_vs_prev_paym"] = (
            transactions_frame["paym_mean_status"] - transactions_frame["prev_paym"]
        )

        # ranks (позиция кредита внутри клиента)
        transactions_frame["util_rank"] = grp["utilization_ratio"].rank(pct=True)
        transactions_frame["paym_rank"] = grp["paym_mean_status"].rank(pct=True)

        # rolling last 3 loans (локальный контекст)
        transactions_frame["util_last3_mean"] = grp["utilization_ratio"].transform(
            lambda x: x.rolling(3, min_periods=1).mean()
        )

        transactions_frame["paym_last3_mean"] = grp["paym_mean_status"].transform(
            lambda x: x.rolling(3, min_periods=1).mean()
        )

        transactions_frame["last_vs_last3_util"] = (
            transactions_frame["utilization_ratio"] - transactions_frame["util_last3_mean"]
        )

        transactions_frame["last_vs_last3_paym"] = (
            transactions_frame["paym_mean_status"] - transactions_frame["paym_last3_mean"]
        )

        transactions_frame['client_products_count'] = grp['id'].transform('count')

        transactions_frame['mean_utilization_ratio'] = grp['utilization_ratio'].transform('mean')
        transactions_frame['max_utilization_ratio'] = grp['utilization_ratio'].transform('max')

        # last payment
        transactions_frame['last_paym_status'] = grp['enc_paym_0'].transform('last')

        # bad loan ratio
        transactions_frame["is_bad_loan"] = (transactions_frame["paym_bad_count"] > 0).astype(int)
        transactions_frame["client_bad_loan_ratio"] = grp["is_bad_loan"].transform("mean")

        # credit structure
        transactions_frame["client_total_credit"] = grp["pre_loans_credit_limit"].transform("sum")
        transactions_frame["max_credit_share"] = (
            grp["pre_loans_credit_limit"].transform("max") /
            (transactions_frame["client_total_credit"] + 1e-6)
        )

        # utilization volatility
        transactions_frame["util_ratio"] = (
            transactions_frame["pre_loans_outstanding"] /
            (transactions_frame["pre_loans_credit_limit"] + 1e-6)
        )
        transactions_frame["client_util_std"] = grp["util_ratio"].transform("std").fillna(0)

        transactions_frame["bad_loan_weight"] = (
            transactions_frame["is_bad_loan"] * transactions_frame["pre_loans_outstanding"]
        )
        transactions_frame["client_bad_weight_share"] = (
            grp["bad_loan_weight"].transform("sum") /
            (grp["pre_loans_outstanding"].transform("sum") + 1e-6)
        )

        # worst loan
        transactions_frame["loan_risk_score"] = transactions_frame["paym_bad_count"]
        transactions_frame["client_worst_loan"] = grp["loan_risk_score"].transform("max")

        # severe loans
        transactions_frame["is_severe_loan"] = (transactions_frame["paym_severe_count"] > 0).astype(int)
        transactions_frame["client_severe_loan_ratio"] = grp["is_severe_loan"].transform("mean")

        # credit diversity
        transactions_frame["credit_type_count"] = grp["enc_loans_credit_type"].transform("nunique")
        transactions_frame["credit_type_density"] = (
            transactions_frame["credit_type_count"] /
            (transactions_frame["client_products_count"] + 1)
        )

        # decay payments
        weights = np.array([0.9**i for i in range(24)])
        transactions_frame["decayed_paym_score"] = (
            transactions_frame[paym_cols].values * weights
        ).sum(axis=1)

        # recent vs total
        recent_cols = [f"enc_paym_{i}" for i in range(12, 24)]

        transactions_frame["recent_bad_count"] = (
            transactions_frame[recent_cols] > 0
        ).sum(axis=1)

        transactions_frame["recent_bad_ratio"] = (
            grp["recent_bad_count"].transform("sum") /
            (grp["paym_bad_count"].transform("sum") + 1e-6)
        )

        # --- базовые per-loan фичи ---
        transactions_frame["loan_paym_mean"] = transactions_frame[paym_cols].mean(axis=1)
        transactions_frame["loan_paym_max"] = transactions_frame[paym_cols].max(axis=1)

        transactions_frame["loan_util"] = (
            transactions_frame["pre_loans_outstanding"] /
            (transactions_frame["pre_loans_credit_limit"] + 1e-6)
        )

        transactions_frame["loan_overdue"] = transactions_frame["pre_loans_max_overdue_sum"]

        # --- WORST LOAN ---
        # индекс худшего кредита
        idx_worst = transactions_frame.groupby("id")["paym_bad_count"].idxmax()

        worst_df = transactions_frame.loc[idx_worst, [
            "id",
            "loan_paym_mean",
            "loan_paym_max",
            "loan_util",
            "loan_overdue",
            "pre_loans_outstanding",
            "pre_loans_credit_limit"
        ]].copy()

        worst_df = worst_df.rename(columns={
            "loan_paym_mean": "worst_loan_paym_mean",
            "loan_paym_max": "worst_loan_paym_max",
            "loan_util": "worst_loan_util",
            "loan_overdue": "worst_loan_overdue",
            "pre_loans_outstanding": "worst_loan_outstanding",
            "pre_loans_credit_limit": "worst_loan_credit_limit"
        })

        # нормализация
        worst_df["worst_loan_overdue_to_limit"] = (
            worst_df["worst_loan_overdue"] /
            (worst_df["worst_loan_credit_limit"] + 1e-6)
        )

        # --- LAST LOAN ---
        idx_last = transactions_frame.groupby("id")["rn"].idxmax()

        last_df = transactions_frame.loc[idx_last, [
            "id",
            "loan_paym_mean",
            "loan_paym_max",
            "loan_util",
            "loan_overdue",
            "pre_loans_outstanding"
        ]].copy()

        last_df = last_df.rename(columns={
            "loan_paym_mean": "last_loan_paym_mean",
            "loan_paym_max": "last_loan_paym_max",
            "loan_util": "last_loan_util",
            "loan_overdue": "last_loan_overdue",
            "pre_loans_outstanding": "last_loan_outstanding"
        })

        # --- DISPERSION ---
        disp_df = transactions_frame.groupby("id").agg({
            "loan_paym_mean": ["std", "max", "mean"],
            "loan_util": ["std", "max", "mean"],
            "loan_overdue": ["std", "max", "mean"]
        })

        disp_df.columns = [
            "loan_paym_std",
            "loan_paym_max",
            "loan_paym_mean_global",
            "loan_util_std",
            "loan_util_max",
            "loan_util_mean",
            "loan_overdue_std",
            "loan_overdue_max",
            "loan_overdue_mean"
        ]

        disp_df = disp_df.reset_index()

        # max - mean
        disp_df["loan_paym_max_minus_mean"] = (
            disp_df["loan_paym_max"] - disp_df["loan_paym_mean_global"]
        )

        disp_df["loan_util_max_minus_mean"] = (
            disp_df["loan_util_max"] - disp_df["loan_util_mean"]
        )

        disp_df["loan_overdue_max_minus_mean"] = (
            disp_df["loan_overdue_max"] - disp_df["loan_overdue_mean"]
        )


        df = transactions_frame.groupby("id").agg({
            "pre_since_opened": ["min", "max", "mean"],
            "pre_since_confirmed": ["min", "max", "mean"],
            "pre_pterm": ["min", "max", "mean"],
            "pre_fterm": ["min", "max", "mean"],
            "pre_till_pclose": ["min", "max"],
            "pre_till_fclose": ["min", "max"],

            "pre_loans_credit_limit": ["max", "mean"],
            "pre_loans_next_pay_summ": ["mean", "max"],
            "pre_loans_outstanding": ["max", "mean"],
            "pre_loans_max_overdue_sum": ["max"],
            "pre_loans_credit_cost_rate": ["mean"],

            "pre_loans5": ["sum"],
            "pre_loans530": ["sum", "max"],
            "pre_loans3060": ["max"],

            "is_zero_loans5": ["mean", "sum"],
            "is_zero_loans530": ["mean", "sum"],
            "is_zero_loans3060": ["mean"],
            "is_zero_loans6090": ["mean"],
            "is_zero_loans90": ["mean", "min"],

            "pre_util": ["mean", "max"],
            "pre_over2limit": ["max"],
            "pre_maxover2limit": ["max"],

            "is_zero_util": ["mean"],
            "is_zero_over2limit": ["mean"],
            "is_zero_maxover2limit": ["mean"],

            "enc_loans_account_holder_type": ["nunique"],
            "enc_loans_credit_status": ["nunique"],
            "enc_loans_credit_type": ["nunique"],
            "enc_loans_account_cur": ["nunique"],

            "pclose_flag": ["mean"],
            "fclose_flag": ["mean"],

            "enc_paym_0": ["max", "mean", "sum"],
            "enc_paym_1": ["max", "mean", "sum"],
            "enc_paym_2": ["max", "mean", "sum"],
            "enc_paym_3": ["max", "mean", "sum"],
            "enc_paym_4": ["max", "mean", "sum"],
            "enc_paym_5": ["max", "mean", "sum"],
            "enc_paym_6": ["max", "mean", "sum"],
            "enc_paym_7": ["mean", "sum"],
            "enc_paym_8": ["mean", "sum"],
            "enc_paym_9": ["mean", "sum"],
            "enc_paym_10": ["mean", "sum"],
            "enc_paym_11": ["mean", "sum"],
            "enc_paym_12": ["mean", "sum"],
            "enc_paym_13": ["mean", "sum"],
            "enc_paym_14": ["mean", "sum"],
            "enc_paym_15": ["mean", "sum"],
            "enc_paym_16": ["mean", "sum"],
            "enc_paym_17": ["mean", "sum"],
            "enc_paym_18": ["mean", "sum"],
            "enc_paym_19": ["mean", "sum"],
            "enc_paym_20": ["mean", "sum"],
            "enc_paym_21": ["mean", "sum"],
            "enc_paym_22": ["mean", "sum"],
            "enc_paym_23": ["mean", "sum"],

            "paym_bad_count": ["mean"],
            "paym_severe_count": ["mean"],
            "paym_nonzero_share": ["mean"],
            "paym_mean_status": ["mean"],
            "enc_paym_weighted_score": ["mean", "max"],

            "client_products_count": "max",
            "mean_utilization_ratio": "max",
            "max_utilization_ratio": "max",
            "last_paym_status": "max",
            "client_bad_loan_ratio": "max",
            "client_util_std": "max",
            "max_credit_share": "max",
            "recent_bad_ratio": "max",
            "client_worst_loan": "max",
            "decayed_paym_score": ["mean", "max"],

            "last_vs_prev_util": "last",
            "last_vs_prev_paym": "last",
            "util_rank": "last",
            "paym_rank": "last",
            "last_vs_last3_util": "last",
            "last_vs_last3_paym": "last",
        }).reset_index()

        df.columns = [
            '_'.join(col).rstrip('_') if isinstance(col, tuple) else col
            for col in df.columns
        ]

        client_counts = transactions_frame.groupby("id").size().rename("client_products_count")
        df = df.merge(client_counts, on="id", how="left")

        df = df.rename(columns={
            "paym_bad_count_mean": "client_mean_bad_months_per_product",
            "paym_nonzero_share_mean": "client_mean_nonzero_paym_share",
            "enc_paym_weighted_score_mean": "client_mean_weighted_paym_score",
            "paym_mean_status_mean": "client_mean_paym_status",
            "enc_paym_weighted_score_max": "client_max_weighted_paym_score",
            "paym_severe_count_mean": "client_mean_severe_bad_months",
        })


        df = df.merge(worst_df, on="id", how="left")
        df = df.merge(last_df, on="id", how="left")
        df = df.merge(disp_df, on="id", how="left")


        # --- дополнительные отношения (уже на уровне df) ---
        df["last_vs_mean_util"] = (
            df["last_loan_util"] - df["pre_util_mean"]
        )

        df["last_vs_mean_paym"] = (
            df["last_loan_paym_mean"] - df["client_mean_paym_status"]
        )

        df["last_vs_worst_paym"] = (
            df["last_loan_paym_mean"] - df["worst_loan_paym_mean"]
        )

        df["worst_loan_util_to_mean_util"] = (
            df["worst_loan_util"] / (df["pre_util_mean"] + 1e-6)
        )

        df["max_credit_share"] = transactions_frame.groupby("id")["max_credit_share"].max().values

        # 1. Нагрузка на один кредит
        df["util_per_loan"] = (
            df["pre_util_mean"] / (df["pre_loans_outstanding_mean"] + 1)
        )

        # 2. Нестабильность utilization
        df["util_stability"] = (
            df["pre_util_max"] - df["pre_util_mean"]
        )

        # 3. Regression trend
        cols = [f"enc_paym_{i}_mean" for i in range(13)]

        X_vals = df[cols].values
        x = np.arange(len(cols))

        x_mean = x.mean()
        denominator = ((x - x_mean) ** 2).sum()

        df["paym_trend_lr"] = (
            ((X_vals - X_vals.mean(axis=1, keepdims=True)) * (x - x_mean))
            .sum(axis=1) / denominator
        )

        # 4. Bad total
        df["bad_to_total_ratio"] = (
            df["client_mean_bad_months_per_product"] /
            (df["client_mean_paym_status"] + 1)
        )

        # 5.
        df["paym_trend_abs"] = np.abs(df["paym_trend_lr"])

        # 6. last bad month
        cols = [f"enc_paym_{i}_mean" for i in range(13)]
        mask = (df[cols[::-1]] > 0).values
        has_bad = mask.sum(axis=1) > 0

        last_idx = mask.argmax(axis=1)
        df["last_bad_month"] = np.where(has_bad, last_idx, -1)

        # 7. recent vs old
        recent = [f"enc_paym_{i}_mean" for i in range(12, 24)]
        old = [f"enc_paym_{i}_mean" for i in range(0, 12)]

        df["recent_vs_old"] = df[recent].mean(axis=1) - df[old].mean(axis=1)

        # 8. recent vs old (early)
        recent = [f"enc_paym_{i}_mean" for i in range(6, 13)]
        old = [f"enc_paym_{i}_mean" for i in range(0, 5)]

        df["recent_vs_old_early"] = df[recent].mean(axis=1) - df[old].mean(axis=1)

        # 9. Стабильность клиента
        cols = [f"enc_paym_{i}_mean" for i in range(13)]
        
        df["paym_std"] = df[cols].std(axis=1)

        # 10. самый худший месяц
        cols = [f"enc_paym_{i}_max" for i in range(7)] + [f"enc_paym_{i}_mean" for i in range(7, 24)]

        df["worst_paym_ever"] = df[cols].max(axis=1)

        # 11. Нестабильность клиента
        cols = [f"enc_paym_{i}_mean" for i in range(13)]

        arr = df[cols].values
        df["paym_switches"] = (np.diff(arr > 0, axis=1) != 0).sum(axis=1)

        # 12. Текущее состояние
        df["last_vs_mean"] = (
            df["last_paym_status_max"] - df["client_mean_paym_status"]
        )

        eps = 1e-6

        df["last_vs_std_util"] = (
            (df["last_loan_util"] - df["pre_util_mean"]) /
            (df["loan_util_std"] + eps)
        )

        df["last_vs_std_paym"] = (
            (df["last_loan_paym_mean"] - df["client_mean_paym_status"]) /
            (df["loan_paym_std"] + eps)
        )

        df["last_util_x_std"] = df["last_loan_util"] * df["loan_util_std"]
        df["last_paym_x_std"] = df["last_loan_paym_mean"] * df["loan_paym_std"]

        df["last_vs_mean_util_x_std"] = (
            (df["last_loan_util"] - df["pre_util_mean"]) * df["loan_util_std"]
        )

        df["last_vs_mean_paym_x_std"] = (
            (df["last_loan_paym_mean"] - df["client_mean_paym_status"]) * df["loan_paym_std"]
        )


        drop_cols = [
            "client_bad_loan_ratio_max",
            "last_bad_month",

            "enc_paym_2_max",
            "enc_paym_3_max",
            "enc_paym_4_max",
            "enc_paym_5_max",
            "enc_paym_6_max",

            "pre_loans530_max",
            "pre_loans3060_max",
            "pre_maxover2limit_max",

            "enc_paym_12_sum",
            "enc_paym_13_sum",
            "enc_paym_14_sum",
            "enc_paym_15_sum",
            "enc_paym_16_sum",
            "enc_paym_17_sum",
            "enc_paym_18_sum"
        ]

        existing_cols_to_drop = [col for col in drop_cols if col in df.columns]
        df = df.drop(columns=existing_cols_to_drop)

        
        display(df)
        df.info(max_cols=5, memory_usage='deep')


        # записываем подготовленные данные в файл
        if save_to_path:
            block_as_str = str(step)
            if len(block_as_str) == 1:
                block_as_str = '00' + block_as_str
            else:
                block_as_str = '0' + block_as_str
            df.to_parquet(os.path.join(save_to_path, f'processed_chunk_{block_as_str}.parquet'))
        gc.collect()
        preprocessed_frames.append(df)

    return pd.concat(preprocessed_frames)

## pipeline old version

In [1]:
def prepare_transactions_dataset(path_to_dataset: str, file_name_tag: str, num_parts_to_preprocess_at_once: int = 1, num_parts_total: int=50,
                                 save_to_path=None, verbose: bool=False):
    """
    возвращает готовый pd.DataFrame с признаками, на которых можно учить модель для целевой задачи.
    path_to_dataset: str
        путь до датасета с партициями
    num_parts_to_preprocess_at_once: int
        количество партиций, которые будут одновременно держаться в памяти и обрабатываться
    num_parts_total: int
        общее количество партиций, которые нужно обработать
    save_to_path: str
        путь до папки, в которой будет сохранен каждый обработанный блок в .parquet формате. Если None, то не будет сохранен
    verbose: bool
        логирует каждый обрабатываемый кусок данных
    """
    preprocessed_frames = []

    for step in tqdm(range(0, num_parts_total, num_parts_to_preprocess_at_once),
                               desc="Transforming transactions data"):
        transactions_frame = read_parquet_dataset_from_local(
            path_to_dataset, file_name_tag, step, num_parts_to_preprocess_at_once,
            verbose=verbose
        )

        # === базовые колонки ===
        paym_cols = [f"enc_paym_{i}" for i in range(24)]  # FIX: используем все 0..23

        # === платежные фичи ===
        transactions_frame["paym_bad_count"] = (transactions_frame[paym_cols] > 0).sum(axis=1)
        transactions_frame["paym_severe_count"] = (transactions_frame[paym_cols] >= 2).sum(axis=1)
        transactions_frame["paym_nonzero_share"] = (transactions_frame[paym_cols] > 0).mean(axis=1)
        transactions_frame["paym_mean_status"] = transactions_frame[paym_cols].mean(axis=1)
        transactions_frame["enc_paym_weighted_score"] = transactions_frame[paym_cols].sum(axis=1)

        # === сортировка (ВАЖНО для last) ===
        transactions_frame = transactions_frame.sort_values(['id', 'rn'])

        # === клиентские агрегаты (до groupby) ===
        grp = transactions_frame.groupby('id')

        transactions_frame['client_products_count'] = grp['id'].transform('count')

        # utilization
        transactions_frame['utilization_ratio'] = (
            transactions_frame['pre_loans_outstanding'] /
            (transactions_frame['pre_loans_credit_limit'] + 1e-6)
        )

        transactions_frame['mean_utilization_ratio'] = grp['utilization_ratio'].transform('mean')
        transactions_frame['max_utilization_ratio'] = grp['utilization_ratio'].transform('max')

        # last payment
        transactions_frame['last_paym_status'] = grp['enc_paym_0'].transform('last')

        # bad loan ratio
        transactions_frame["is_bad_loan"] = (transactions_frame["paym_bad_count"] > 0).astype(int)
        transactions_frame["client_bad_loan_ratio"] = grp["is_bad_loan"].transform("mean")

        # credit structure
        transactions_frame["client_total_credit"] = grp["pre_loans_credit_limit"].transform("sum")
        transactions_frame["max_credit_share"] = (
            grp["pre_loans_credit_limit"].transform("max") /
            (transactions_frame["client_total_credit"] + 1e-6)
        )

        # utilization volatility
        transactions_frame["util_ratio"] = (
            transactions_frame["pre_loans_outstanding"] /
            (transactions_frame["pre_loans_credit_limit"] + 1e-6)
        )
        transactions_frame["client_util_std"] = grp["util_ratio"].transform("std").fillna(0)

        transactions_frame["bad_loan_weight"] = (
            transactions_frame["is_bad_loan"] * transactions_frame["pre_loans_outstanding"]
        )
        transactions_frame["client_bad_weight_share"] = (
            grp["bad_loan_weight"].transform("sum") /
            (grp["pre_loans_outstanding"].transform("sum") + 1e-6)
        )

        # worst loan
        transactions_frame["loan_risk_score"] = transactions_frame["paym_bad_count"]
        transactions_frame["client_worst_loan"] = grp["loan_risk_score"].transform("max")

        # severe loans
        transactions_frame["is_severe_loan"] = (transactions_frame["paym_severe_count"] > 0).astype(int)
        transactions_frame["client_severe_loan_ratio"] = grp["is_severe_loan"].transform("mean")

        # credit diversity
        transactions_frame["credit_type_count"] = grp["enc_loans_credit_type"].transform("nunique")
        transactions_frame["credit_type_density"] = (
            transactions_frame["credit_type_count"] /
            (transactions_frame["client_products_count"] + 1)
        )

        # decay payments
        weights = np.array([0.9**i for i in range(24)])
        transactions_frame["decayed_paym_score"] = (
            transactions_frame[paym_cols].values * weights
        ).sum(axis=1)

        # recent vs total
        recent_cols = [f"enc_paym_{i}" for i in range(12, 24)]

        transactions_frame["recent_bad_count"] = (
            transactions_frame[recent_cols] > 0
        ).sum(axis=1)

        transactions_frame["recent_bad_ratio"] = (
            grp["recent_bad_count"].transform("sum") /
            (grp["paym_bad_count"].transform("sum") + 1e-6)
        )

        # --- базовые per-loan фичи ---
        transactions_frame["loan_paym_mean"] = transactions_frame[paym_cols].mean(axis=1)
        transactions_frame["loan_paym_max"] = transactions_frame[paym_cols].max(axis=1)

        transactions_frame["loan_util"] = (
            transactions_frame["pre_loans_outstanding"] /
            (transactions_frame["pre_loans_credit_limit"] + 1e-6)
        )

        transactions_frame["loan_overdue"] = transactions_frame["pre_loans_max_overdue_sum"]

        # --- WORST LOAN ---
        # индекс худшего кредита
        idx_worst = transactions_frame.groupby("id")["paym_bad_count"].idxmax()

        worst_df = transactions_frame.loc[idx_worst, [
            "id",
            "loan_paym_mean",
            "loan_paym_max",
            "loan_util",
            "loan_overdue",
            "pre_loans_outstanding",
            "pre_loans_credit_limit"
        ]].copy()

        worst_df = worst_df.rename(columns={
            "loan_paym_mean": "worst_loan_paym_mean",
            "loan_paym_max": "worst_loan_paym_max",
            "loan_util": "worst_loan_util",
            "loan_overdue": "worst_loan_overdue",
            "pre_loans_outstanding": "worst_loan_outstanding",
            "pre_loans_credit_limit": "worst_loan_credit_limit"
        })

        # нормализация
        worst_df["worst_loan_overdue_to_limit"] = (
            worst_df["worst_loan_overdue"] /
            (worst_df["worst_loan_credit_limit"] + 1e-6)
        )

        # --- LAST LOAN ---
        idx_last = transactions_frame.groupby("id")["rn"].idxmax()

        last_df = transactions_frame.loc[idx_last, [
            "id",
            "loan_paym_mean",
            "loan_paym_max",
            "loan_util",
            "loan_overdue",
            "pre_loans_outstanding"
        ]].copy()

        last_df = last_df.rename(columns={
            "loan_paym_mean": "last_loan_paym_mean",
            "loan_paym_max": "last_loan_paym_max",
            "loan_util": "last_loan_util",
            "loan_overdue": "last_loan_overdue",
            "pre_loans_outstanding": "last_loan_outstanding"
        })

        # --- DISPERSION ---
        disp_df = transactions_frame.groupby("id").agg({
            "loan_paym_mean": ["std", "max", "mean"],
            "loan_util": ["std", "max", "mean"],
            "loan_overdue": ["std", "max", "mean"]
        })

        disp_df.columns = [
            "loan_paym_std",
            "loan_paym_max",
            "loan_paym_mean_global",
            "loan_util_std",
            "loan_util_max",
            "loan_util_mean",
            "loan_overdue_std",
            "loan_overdue_max",
            "loan_overdue_mean"
        ]

        disp_df = disp_df.reset_index()

        # max - mean
        disp_df["loan_paym_max_minus_mean"] = (
            disp_df["loan_paym_max"] - disp_df["loan_paym_mean_global"]
        )

        disp_df["loan_util_max_minus_mean"] = (
            disp_df["loan_util_max"] - disp_df["loan_util_mean"]
        )

        disp_df["loan_overdue_max_minus_mean"] = (
            disp_df["loan_overdue_max"] - disp_df["loan_overdue_mean"]
        )


        df = transactions_frame.groupby("id").agg({
            "pre_since_opened": ["min", "max", "mean"],
            "pre_since_confirmed": ["min", "max", "mean"],
            "pre_pterm": ["min", "max", "mean"],
            "pre_fterm": ["min", "max", "mean"],
            "pre_till_pclose": ["min", "max"],
            "pre_till_fclose": ["min", "max"],

            "pre_loans_credit_limit": ["max", "mean"],
            "pre_loans_next_pay_summ": ["mean", "max"],
            "pre_loans_outstanding": ["max", "mean"],
            "pre_loans_max_overdue_sum": ["max"],
            "pre_loans_credit_cost_rate": ["mean"],

            "pre_loans5": ["sum"],
            "pre_loans530": ["sum", "max"],
            "pre_loans3060": ["max"],

            "is_zero_loans5": ["mean", "sum"],
            "is_zero_loans530": ["mean", "sum"],
            "is_zero_loans3060": ["mean"],
            "is_zero_loans6090": ["mean"],
            "is_zero_loans90": ["mean"],

            "pre_util": ["mean", "max"],
            "pre_over2limit": ["max"],
            "pre_maxover2limit": ["max"],

            "is_zero_util": ["mean"],
            "is_zero_over2limit": ["mean"],
            "is_zero_maxover2limit": ["mean"],

            "enc_loans_account_holder_type": ["nunique"],
            "enc_loans_credit_status": ["nunique"],
            "enc_loans_credit_type": ["nunique"],
            "enc_loans_account_cur": ["nunique"],

            "pclose_flag": ["mean"],
            "fclose_flag": ["mean"],

            "enc_paym_0": ["max", "mean", "sum"],
            "enc_paym_1": ["max", "mean", "sum"],
            "enc_paym_2": ["max", "mean", "sum"],
            "enc_paym_3": ["max", "mean", "sum"],
            "enc_paym_4": ["max", "mean", "sum"],
            "enc_paym_5": ["max", "mean", "sum"],
            "enc_paym_6": ["max", "mean", "sum"],
            "enc_paym_7": ["mean", "sum"],
            "enc_paym_8": ["mean", "sum"],
            "enc_paym_9": ["mean", "sum"],
            "enc_paym_10": ["mean", "sum"],
            "enc_paym_11": ["mean", "sum"],
            "enc_paym_12": ["mean", "sum"],
            "enc_paym_13": ["mean", "sum"],
            "enc_paym_14": ["mean", "sum"],
            "enc_paym_15": ["mean", "sum"],
            "enc_paym_16": ["mean", "sum"],
            "enc_paym_17": ["mean", "sum"],
            "enc_paym_18": ["mean", "sum"],
            "enc_paym_19": ["mean", "sum"],
            "enc_paym_20": ["mean", "sum"],
            "enc_paym_21": ["mean", "sum"],
            "enc_paym_22": ["mean", "sum"],
            "enc_paym_23": ["mean", "sum"],

            "paym_bad_count": ["mean"],
            "paym_severe_count": ["mean"],
            "paym_nonzero_share": ["mean"],
            "paym_mean_status": ["mean"],
            "enc_paym_weighted_score": ["mean", "max"],

            "client_products_count": "max",
            "mean_utilization_ratio": "max",
            "max_utilization_ratio": "max",
            "last_paym_status": "max",
            "client_bad_loan_ratio": "max",
            "client_util_std": "max",
            "max_credit_share": "max",
            "recent_bad_ratio": "max",
            "client_worst_loan": "max",
            "decayed_paym_score": ["mean", "max"],
        }).reset_index()

        df.columns = [
            '_'.join(col).rstrip('_') if isinstance(col, tuple) else col
            for col in df.columns
        ]

        client_counts = transactions_frame.groupby("id").size().rename("client_products_count")
        df = df.merge(client_counts, on="id", how="left")

        df = df.rename(columns={
            "paym_bad_count_mean": "client_mean_bad_months_per_product",
            "paym_nonzero_share_mean": "client_mean_nonzero_paym_share",
            "enc_paym_weighted_score_mean": "client_mean_weighted_paym_score",
            "paym_mean_status_mean": "client_mean_paym_status",
            "enc_paym_weighted_score_max": "client_max_weighted_paym_score",
            "paym_severe_count_mean": "client_mean_severe_bad_months",
        })


        df = df.merge(worst_df, on="id", how="left")
        df = df.merge(last_df, on="id", how="left")
        df = df.merge(disp_df, on="id", how="left")

        # --- дополнительные отношения (уже на уровне df) ---
        df["last_vs_mean_util"] = (
            df["last_loan_util"] - df["pre_util_mean"]
        )

        df["last_vs_mean_paym"] = (
            df["last_loan_paym_mean"] - df["client_mean_paym_status"]
        )

        df["last_vs_worst_paym"] = (
            df["last_loan_paym_mean"] - df["worst_loan_paym_mean"]
        )

        df["worst_loan_util_to_mean_util"] = (
            df["worst_loan_util"] / (df["pre_util_mean"] + 1e-6)
        )

        df["max_credit_share"] = transactions_frame.groupby("id")["max_credit_share"].max().values

        # 1. Нагрузка на один кредит
        df["util_per_loan"] = (
            df["pre_util_mean"] / (df["pre_loans_outstanding_mean"] + 1)
        )

        # 2. Нестабильность utilization
        df["util_stability"] = (
            df["pre_util_max"] - df["pre_util_mean"]
        )

        # 3. Regression trend
        cols = [f"enc_paym_{i}_mean" for i in range(13)]

        X_vals = df[cols].values
        x = np.arange(len(cols))

        x_mean = x.mean()
        denominator = ((x - x_mean) ** 2).sum()

        df["paym_trend_lr"] = (
            ((X_vals - X_vals.mean(axis=1, keepdims=True)) * (x - x_mean))
            .sum(axis=1) / denominator
        )

        # 4. Bad total
        df["bad_to_total_ratio"] = (
            df["client_mean_bad_months_per_product"] /
            (df["client_mean_paym_status"] + 1)
        )

        # 5.
        df["paym_trend_abs"] = np.abs(df["paym_trend_lr"])

        # 6. last bad month
        cols = [f"enc_paym_{i}_mean" for i in range(13)]
        mask = (df[cols[::-1]] > 0).values
        has_bad = mask.sum(axis=1) > 0

        last_idx = mask.argmax(axis=1)
        df["last_bad_month"] = np.where(has_bad, last_idx, -1)

        # 7. recent vs old
        recent = [f"enc_paym_{i}_mean" for i in range(12, 24)]
        old = [f"enc_paym_{i}_mean" for i in range(0, 12)]

        df["recent_vs_old"] = df[recent].mean(axis=1) - df[old].mean(axis=1)

        # 8. recent vs old (early)
        recent = [f"enc_paym_{i}_mean" for i in range(6, 13)]
        old = [f"enc_paym_{i}_mean" for i in range(0, 5)]

        df["recent_vs_old_early"] = df[recent].mean(axis=1) - df[old].mean(axis=1)

        # 9. Стабильность клиента
        cols = [f"enc_paym_{i}_mean" for i in range(13)]
        
        df["paym_std"] = df[cols].std(axis=1)

        # 10. самый худший месяц
        cols = [f"enc_paym_{i}_max" for i in range(7)] + [f"enc_paym_{i}_mean" for i in range(7, 24)]

        df["worst_paym_ever"] = df[cols].max(axis=1)

        # 11. Нестабильность клиента
        cols = [f"enc_paym_{i}_mean" for i in range(13)]

        arr = df[cols].values
        df["paym_switches"] = (np.diff(arr > 0, axis=1) != 0).sum(axis=1)

        # 12. Текущее состояние
        df["last_vs_mean"] = (
            df["last_paym_status_max"] - df["client_mean_paym_status"]
        )


        drop_cols = [
            "client_bad_loan_ratio_max",
            "last_bad_month",

            "enc_paym_2_max",
            "enc_paym_3_max",
            "enc_paym_4_max",
            "enc_paym_5_max",
            "enc_paym_6_max",

            "pre_loans530_max",
            "pre_loans3060_max",
            "pre_maxover2limit_max",

            "enc_paym_12_sum",
            "enc_paym_13_sum",
            "enc_paym_14_sum",
            "enc_paym_15_sum",
            "enc_paym_16_sum",
            "enc_paym_17_sum",
            "enc_paym_18_sum"
        ]

        existing_cols_to_drop = [col for col in drop_cols if col in df.columns]
        df = df.drop(columns=existing_cols_to_drop)

        
        display(df)
        df.info(max_cols=5, memory_usage='deep')


        # записываем подготовленные данные в файл
        if save_to_path:
            block_as_str = str(step)
            if len(block_as_str) == 1:
                block_as_str = '00' + block_as_str
            else:
                block_as_str = '0' + block_as_str
            df.to_parquet(os.path.join(save_to_path, f'processed_chunk_{block_as_str}.parquet'))
        gc.collect()
        preprocessed_frames.append(df)

    return pd.concat(preprocessed_frames)

# 3. Dataset Construction

In this section:
- raw data is processed using the pipeline functions
- multiple data sources are combined
- final dataset is constructed and merged with target

## preprocessing

In [10]:
data = prepare_transactions_dataset(path, 'train', num_parts_to_preprocess_at_once=1, num_parts_total=12,
                                    save_to_path=path)

Transforming transactions data:   0%|                   | 0/12 [00:00<?, ?it/s]
Reading dataset with pandas:   0%|                       | 0/1 [00:00<?, ?it/s]

chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\train_data_0.pq
Memory usage of dataframe is 919.02 MB

  0%|                                                   | 0/61 [00:00<?, ?it/s]

 30%|████████████                             | 18/61 [00:00<00:00, 172.71it/s]

 59%|████████████████████████▏                | 36/61 [00:00<00:00, 173.73it/s]

100%|█████████████████████████████████████████| 61/61 [00:00<00:00, 158.66it/s]

Reading dataset with pandas: 100%|███████████████| 1/1 [00:01<00:00,  1.17s/it]

Memory usage after optimization is: 120.528 MB
Decreased by 86.9%

,id,pre_since_opened_min,pre_since_opened_max,pre_since_opened_mean,pre_since_confirmed_min,pre_since_confirmed_max,pre_since_confirmed_mean,pre_pterm_min,pre_pterm_max,pre_pterm_mean,...,paym_std,worst_paym_ever,paym_switches,last_vs_mean,last_vs_std_util,last_vs_std_paym,last_util_x_std,last_paym_x_std,last_vs_mean_util_x_std,last_vs_mean_paym_x_std
0,0,1,18,8.100000,0,12,7.600000,1,15,7.100000,...,0.714592,3.400000,2,-1.612500,-0.000014,0.696151,118585.391439,2.416059,-1.278351e+07,0.746390
1,1,2,18,11.428571,3,14,7.642857,0,15,6.642857,...,0.598435,3.142857,0,1.294643,-0.000015,1.433731,218668.211377,2.963427,-9.574545e+06,1.324389
2,2,0,13,8.333333,9,14,10.666667,4,13,7.000000,...,0.738637,3.333333,0,1.097222,-2.836837,1.028886,6.110088,3.537849,-6.619274e+00,1.354582
3,3,1,18,7.000000,0,16,7.333333,0,16,7.600000,...,0.615609,3.000000,1,-1.075000,-12.723924,1.835863,0.111715,3.034825,-1.147312e+01,1.932029
4,4,12,12,12.000000,9,9,9.000000,4,4,4.000000,...,0.277350,4.000000,0,-0.083333,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,249995,0,18,7.615385,1,14,7.538462,0,16,10.230769,...,1.086880,4.000000,3,-1.923077,-11.037512,0.686996,0.189212,0.916948,-1.585013e+01,0.118445
249996,249996,1,19,9.217391,0,17,9.782609,2,17,8.652174,...,0.843664,3.608696,0,-1.914855,-0.000023,1.139251,41702.874612,2.709634,-8.933482e+06,0.955756
249997,249997,1,14,6.857143,2,6,5.142857,1,17,10.428571,...,0.602845,3.000000,2,-0.958333,-15.835339,0.672534,0.489411,1.905105,-1.517175e+01,0.836388
249998,249998,1,15,6.800000,5,9,7.800000,4,14,9.600000,...,0.686126,4.000000,0,-2.333333,-46.456948,0.171498,0.054332,1.791803,-3.094196e+00,0.091109
249999,249999,9,9,9.000000,0,16,8.333333,6,10,8.666667,...,1.552500,4.000000,1,-2.000000,-334.853912,-0.577342,0.009021,0.141331,-4.360197e-01,-0.003007

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Columns: 159 entries, id to last_vs_mean_paym_x_std
dtypes: float64(98), int32(1), int64(20), int8(40)
memory usage: 235.6 MB

Transforming transactions data:   8%|▉          | 1/12 [01:34<17:14, 94.04s/it]
Reading dataset with pandas:   0%|                       | 0/1 [00:00<?, ?it/s]

chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\train_data_1.pq
Memory usage of dataframe is 980.73 MB

  0%|                                                   | 0/61 [00:00<?, ?it/s]

 25%|██████████                               | 15/61 [00:00<00:00, 146.40it/s]

 51%|████████████████████▊                    | 31/61 [00:00<00:00, 152.76it/s]

100%|█████████████████████████████████████████| 61/61 [00:00<00:00, 132.87it/s]

Reading dataset with pandas: 100%|███████████████| 1/1 [00:01<00:00,  1.31s/it]

Memory usage after optimization is: 128.620 MB
Decreased by 86.9%

,id,pre_since_opened_min,pre_since_opened_max,pre_since_opened_mean,pre_since_confirmed_min,pre_since_confirmed_max,pre_since_confirmed_mean,pre_pterm_min,pre_pterm_max,pre_pterm_mean,...,paym_std,worst_paym_ever,paym_switches,last_vs_mean,last_vs_std_util,last_vs_std_paym,last_util_x_std,last_paym_x_std,last_vs_mean_util_x_std,last_vs_mean_paym_x_std
0,250000,6,18,11.428571,4,12,8.857143,0,12,6.142857,...,0.489823,3.571429,0,-1.845238,2.645739,-0.860328,3.401680e+12,0.986783,3.401663e+12,-1.094188
1,250001,1,18,8.454545,1,17,7.454545,6,14,9.636364,...,1.000583,3.181818,5,-1.598485,-0.000012,0.931253,8.090396e+04,2.269836,-1.723990e+07,0.793918
2,250002,0,15,8.000000,1,6,4.000000,0,9,4.333333,...,0.561084,3.000000,0,-1.500000,-2.875991,0.473016,8.808551e+00,2.569210,-1.394690e+01,0.719379
3,250003,8,10,9.000000,6,12,9.000000,4,6,5.000000,...,0.518875,3.000000,1,-1.520833,-132.068043,0.707106,2.236766e-02,6.014090,-1.438986e+00,2.922340
4,250004,4,19,11.500000,0,8,4.000000,1,15,8.000000,...,0.753198,4.000000,1,-2.083333,-26.869981,0.707106,2.064333e-01,2.393851,-2.931353e+00,0.552427
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,499995,10,19,16.000000,9,17,11.666667,2,6,4.000000,...,0.848159,3.000000,1,-1.833333,-0.000024,0.621149,2.474357e+05,3.815171,-8.027915e+06,1.232594
249996,499996,3,19,12.555556,0,17,6.888889,3,17,10.000000,...,0.807824,3.333333,1,-1.884259,-51.211354,0.970713,1.596861e-02,3.273334,-2.938225e+00,1.188440
249997,499997,0,17,4.000000,1,14,11.444444,0,17,9.666667,...,0.708337,3.000000,1,-1.148148,-0.000011,1.294704,3.379312e+05,2.863635,-1.148966e+07,1.590908
249998,499998,2,11,8.555556,1,17,13.000000,4,17,6.777778,...,0.834425,4.000000,1,-2.435185,-115.498987,0.029009,5.555553e-02,1.961693,-1.425926e+00,0.018472
249999,499999,1,15,10.000000,2,14,7.083333,1,17,9.750000,...,0.553254,3.250000,1,-1.541667,-90.065177,1.244259,7.401993e-02,2.941283,-1.973866e+00,1.340879

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Columns: 159 entries, id to last_vs_mean_paym_x_std
dtypes: float64(98), int32(1), int64(24), int8(36)
memory usage: 242.2 MB

Transforming transactions data:  17%|█▊         | 2/12 [03:09<15:48, 94.87s/it]
Reading dataset with pandas:   0%|                       | 0/1 [00:00<?, ?it/s]

chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\train_data_10.pq
Memory usage of dataframe is 1068.72 MB

  0%|                                                   | 0/61 [00:00<?, ?it/s]

 26%|██████████▊                              | 16/61 [00:00<00:00, 150.33it/s]

 52%|█████████████████████▌                   | 32/61 [00:00<00:00, 152.31it/s]

100%|█████████████████████████████████████████| 61/61 [00:00<00:00, 120.46it/s]

Reading dataset with pandas: 100%|███████████████| 1/1 [00:01<00:00,  1.43s/it]

Memory usage after optimization is: 140.160 MB
Decreased by 86.9%

,id,pre_since_opened_min,pre_since_opened_max,pre_since_opened_mean,pre_since_confirmed_min,pre_since_confirmed_max,pre_since_confirmed_mean,pre_pterm_min,pre_pterm_max,pre_pterm_mean,...,paym_std,worst_paym_ever,paym_switches,last_vs_mean,last_vs_std_util,last_vs_std_paym,last_util_x_std,last_paym_x_std,last_vs_mean_util_x_std,last_vs_mean_paym_x_std
0,2500000,3,12,6.833333,3,17,6.333333,6,16,11.500000,...,0.748931,4.000000,1,-1.958333,-9.877759,1.606436,0.218673,1.841548,-1.180834e+01,0.622495
1,2500001,9,11,10.000000,0,3,1.500000,4,6,5.000000,...,1.320451,4.000000,2,-1.187500,-38.183633,-0.707105,0.117851,0.734114,-2.121319e+00,-0.103734
2,2500002,2,19,9.200000,2,12,8.200000,1,15,7.600000,...,0.765942,3.400000,3,-1.575000,-43.266708,1.241891,0.131541,2.471586,-2.425611e+00,1.034264
3,2500003,1,17,6.333333,1,16,9.166667,4,15,11.000000,...,0.767252,3.000000,1,-1.298611,-36.652689,1.294915,0.237021,2.562996,-3.660664e+00,1.274608
4,2500004,1,19,11.900000,2,17,10.000000,2,17,7.950000,...,0.837368,3.400000,0,-1.708333,-62.736252,1.398436,0.061208,2.644321,-2.611555e+00,1.117319
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,2749995,3,14,10.571429,4,12,7.142857,1,12,6.714286,...,0.753329,4.000000,0,-2.642857,-71.401058,-2.014276,0.097938,0.807725,-2.219004e+00,-0.473096
249996,2749996,2,12,5.800000,2,12,8.200000,4,17,9.800000,...,0.806703,4.000000,1,-1.916667,-142.072904,1.262824,0.013439,2.056676,-1.642280e+00,0.665395
249997,2749997,14,15,14.666667,4,13,9.333333,1,4,3.000000,...,0.408248,3.000000,1,-1.111111,-149.450846,-0.641107,0.015943,0.133594,-8.272389e-01,-1.647661
249998,2749998,0,14,9.333333,4,14,7.833333,0,8,3.333333,...,0.862316,3.500000,1,-1.958333,-76.718364,0.956182,0.073116,3.093899,-2.916519e+00,1.045825
249999,2749999,0,19,8.833333,3,17,7.944444,1,17,8.666667,...,0.583486,3.333333,0,-1.745370,-0.000010,1.169252,95587.563333,3.068923,-1.819350e+07,1.258306

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Columns: 159 entries, id to last_vs_mean_paym_x_std
dtypes: float64(98), int32(1), int64(14), int8(46)
memory usage: 225.5 MB

Transforming transactions data:  25%|██▊        | 3/12 [04:46<14:24, 96.01s/it]
Reading dataset with pandas:   0%|                       | 0/1 [00:00<?, ?it/s]

chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\train_data_11.pq
Memory usage of dataframe is 1140.51 MB

  0%|                                                   | 0/61 [00:00<?, ?it/s]

 25%|██████████                               | 15/61 [00:00<00:00, 148.73it/s]

 51%|████████████████████▊                    | 31/61 [00:00<00:00, 151.53it/s]

100%|█████████████████████████████████████████| 61/61 [00:00<00:00, 122.17it/s]

Reading dataset with pandas: 100%|███████████████| 1/1 [00:01<00:00,  1.42s/it]

Memory usage after optimization is: 149.575 MB
Decreased by 86.9%

,id,pre_since_opened_min,pre_since_opened_max,pre_since_opened_mean,pre_since_confirmed_min,pre_since_confirmed_max,pre_since_confirmed_mean,pre_pterm_min,pre_pterm_max,pre_pterm_mean,...,paym_std,worst_paym_ever,paym_switches,last_vs_mean,last_vs_std_util,last_vs_std_paym,last_util_x_std,last_paym_x_std,last_vs_mean_util_x_std,last_vs_mean_paym_x_std
0,2750000,1,9,6.571429,2,16,5.000000,2,15,9.428571,...,1.012739,4.000000,5,-1.726190,-41.453486,1.147885,1.712067e-01,0.927558,-3.375219e+00,0.202513
1,2750001,0,15,7.100000,1,17,8.600000,6,15,8.700000,...,0.968544,4.000000,1,-2.308333,-29.463226,-0.142014,2.881481e-01,1.555007,-4.794786e+00,-0.070415
2,2750002,1,12,6.500000,6,16,11.000000,2,6,4.000000,...,0.657794,4.000000,1,-2.145833,-0.380752,0.707106,1.050556e+01,2.754770,-2.626404e+00,0.668437
3,2750003,10,17,13.000000,0,9,4.333333,6,11,9.333333,...,0.701037,3.000000,0,-1.791667,-84.424417,0.820694,9.686441e-03,4.205449,-1.782305e+00,1.658487
4,2750004,0,18,10.222222,2,17,11.111111,0,16,6.111111,...,0.927833,3.666667,3,-1.884259,-59.698492,-0.529148,7.889616e-02,1.173851,-4.128899e+00,-0.342839
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,2999995,0,19,8.818182,2,17,9.181818,2,17,8.909091,...,0.483901,3.000000,0,-0.215909,-0.000008,1.711650,1.119162e+06,2.160990,-2.314632e+07,1.160012
249996,2999996,1,16,8.000000,5,17,11.384615,4,16,9.000000,...,0.608006,3.538462,0,-1.448718,-13.073933,0.310495,2.329940e+00,1.428394,-7.885961e+00,0.217073
249997,2999997,2,17,8.100000,1,16,7.800000,0,15,8.500000,...,0.718795,3.400000,0,-1.529167,-0.000011,1.608577,1.264910e+06,2.628377,-1.030902e+07,1.269765
249998,2999998,4,19,11.600000,1,16,9.200000,0,17,7.800000,...,1.093805,4.000000,0,-2.600000,-46.710265,0.677605,5.024023e-02,0.975656,-2.213920e+00,0.080348
249999,2999999,0,16,6.416667,2,17,9.166667,2,14,7.666667,...,0.483985,3.000000,0,-1.295139,-0.000041,-0.182793,1.154700e+05,1.255280,-3.396743e+06,-0.245423

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Columns: 159 entries, id to last_vs_mean_paym_x_std
dtypes: float64(98), int32(1), int64(24), int8(36)
memory usage: 242.2 MB

Transforming transactions data:  33%|███▋       | 4/12 [06:23<12:50, 96.36s/it]
Reading dataset with pandas:   0%|                       | 0/1 [00:00<?, ?it/s]

chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\train_data_2.pq
Memory usage of dataframe is 968.25 MB

  0%|                                                   | 0/61 [00:00<?, ?it/s]

 30%|████████████                             | 18/61 [00:00<00:00, 173.70it/s]

 59%|████████████████████████▏                | 36/61 [00:00<00:00, 170.58it/s]

100%|█████████████████████████████████████████| 61/61 [00:00<00:00, 133.79it/s]

Reading dataset with pandas: 100%|███████████████| 1/1 [00:01<00:00,  1.21s/it]

Memory usage after optimization is: 126.984 MB
Decreased by 86.9%

,id,pre_since_opened_min,pre_since_opened_max,pre_since_opened_mean,pre_since_confirmed_min,pre_since_confirmed_max,pre_since_confirmed_mean,pre_pterm_min,pre_pterm_max,pre_pterm_mean,...,paym_std,worst_paym_ever,paym_switches,last_vs_mean,last_vs_std_util,last_vs_std_paym,last_util_x_std,last_paym_x_std,last_vs_mean_util_x_std,last_vs_mean_paym_x_std
0,500000,3,18,10.000000,0,16,7.875000,0,15,7.375000,...,0.720994,3.0,1,-1.114583,-30.350023,1.104475,0.132253,2.574751,-4.777636,1.344847
1,500001,2,18,11.888889,0,17,9.444444,0,17,7.666667,...,0.470396,3.0,0,-1.245370,-45.876323,1.381378,0.278526,2.158616,-3.558939,1.065080
2,500002,7,9,7.666667,1,9,6.333333,3,12,6.333333,...,1.441153,4.0,1,-2.541667,-6.724832,-0.577346,0.512113,0.354830,-13.827056,-0.012028
3,500003,7,7,7.000000,9,9,9.000000,4,4,4.000000,...,1.652504,4.0,1,-2.333333,NaN,NaN,NaN,NaN,NaN,NaN
4,500004,7,7,7.000000,9,9,9.000000,4,4,4.000000,...,1.652504,4.0,1,-2.333333,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,749995,12,12,12.000000,9,9,9.000000,4,4,4.000000,...,0.277350,4.0,0,-0.083333,NaN,NaN,NaN,NaN,NaN,NaN
249996,749996,1,19,8.933333,0,16,6.466667,2,17,7.000000,...,0.692820,3.8,1,-1.569444,-41.436979,1.703993,0.167724,2.411272,-4.662730,1.132053
249997,749997,0,17,9.000000,9,16,10.750000,4,12,7.250000,...,0.545964,3.5,0,1.343750,-28.761002,1.109902,0.057653,3.964466,-4.684309,1.834905
249998,749998,0,18,9.800000,9,10,9.200000,1,14,5.400000,...,0.480384,3.4,0,1.566667,-23.698846,1.417634,0.039195,3.588724,-8.191852,1.920452
249999,749999,5,14,8.000000,3,10,5.666667,0,12,4.666667,...,0.509175,3.0,2,-0.277778,-15.092502,1.148514,0.327639,3.224775,-7.841501,1.679571

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Columns: 159 entries, id to last_vs_mean_paym_x_std
dtypes: float64(98), int32(1), int64(22), int8(38)
memory usage: 238.9 MB

Transforming transactions data:  42%|████▌      | 5/12 [08:00<11:14, 96.37s/it]
Reading dataset with pandas:   0%|                       | 0/1 [00:00<?, ?it/s]

chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\train_data_3.pq
Memory usage of dataframe is 983.19 MB

  0%|                                                   | 0/61 [00:00<?, ?it/s]

 21%|████████▋                                | 13/61 [00:00<00:00, 128.18it/s]

 49%|████████████████████▏                    | 30/61 [00:00<00:00, 147.67it/s]

100%|█████████████████████████████████████████| 61/61 [00:00<00:00, 123.26it/s]

Reading dataset with pandas: 100%|███████████████| 1/1 [00:01<00:00,  1.37s/it]

Memory usage after optimization is: 128.943 MB
Decreased by 86.9%

,id,pre_since_opened_min,pre_since_opened_max,pre_since_opened_mean,pre_since_confirmed_min,pre_since_confirmed_max,pre_since_confirmed_mean,pre_pterm_min,pre_pterm_max,pre_pterm_mean,...,paym_std,worst_paym_ever,paym_switches,last_vs_mean,last_vs_std_util,last_vs_std_paym,last_util_x_std,last_paym_x_std,last_vs_mean_util_x_std,last_vs_mean_paym_x_std
0,750000,0,19,10.000000,2,16,10.000000,8,17,13.000000,...,0.518875,3.0000,0,-1.083333,-63.073959,1.543056,0.057710,2.852156,-1.312894e+00,1.711294
1,750001,9,19,15.000000,5,16,8.333333,4,9,4.833333,...,0.859214,4.0000,0,-2.944444,-55.956970,-1.951766,0.076447,0.161295,-2.943221e+00,-0.006325
2,750002,7,19,13.000000,2,5,3.500000,1,11,6.000000,...,1.224745,4.0000,1,-2.770833,-257.581835,0.707099,0.004549,0.250434,-3.412050e-01,0.005524
3,750003,0,17,10.200000,0,17,7.850000,3,17,9.950000,...,0.704609,3.1500,0,1.597917,-21.565649,1.706336,0.172335,3.038000,-8.611021e+00,1.656531
4,750004,6,13,9.800000,4,10,6.000000,7,17,13.000000,...,0.902418,3.4000,3,-1.708333,-20.325240,0.939551,0.289506,2.882578,-8.245144e+00,1.064337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,999995,2,19,9.750000,2,10,6.750000,0,11,6.500000,...,0.477037,3.0000,1,-1.156250,-6.629308,1.272657,0.980028,3.733711,-2.062960e+01,2.210028
249996,999996,3,18,8.000000,3,17,9.937500,4,16,7.625000,...,0.614495,3.8125,0,-2.414062,-70.762200,0.500754,0.032582,2.372288,-2.704271e+00,0.351046
249997,999997,3,17,8.866667,3,12,10.400000,0,13,4.133333,...,0.851344,3.8000,0,-2.550000,-58.036129,0.374961,0.045470,2.140962,-4.319611e+00,0.214096
249998,999998,0,18,10.055556,0,13,5.444444,0,17,8.944444,...,0.702052,3.0000,1,-1.368056,-0.000018,0.818388,321412.102219,2.752133,-8.753124e+06,1.138531
249999,999999,0,5,2.500000,8,16,12.000000,1,15,8.000000,...,0.877058,2.5000,1,-1.020833,-117.293418,-0.707106,0.009411,0.110485,-7.504892e-01,-1.242961

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Columns: 159 entries, id to last_vs_mean_paym_x_std
dtypes: float64(98), int32(1), int64(21), int8(39)
memory usage: 237.2 MB

Transforming transactions data:  50%|█████▌     | 6/12 [09:36<09:38, 96.49s/it]
Reading dataset with pandas:   0%|                       | 0/1 [00:00<?, ?it/s]

chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\train_data_4.pq
Memory usage of dataframe is 960.62 MB

  0%|                                                   | 0/61 [00:00<?, ?it/s]

 28%|███████████▍                             | 17/61 [00:00<00:00, 167.03it/s]

 57%|███████████████████████▌                 | 35/61 [00:00<00:00, 173.95it/s]

100%|█████████████████████████████████████████| 61/61 [00:00<00:00, 141.53it/s]

Reading dataset with pandas: 100%|███████████████| 1/1 [00:01<00:00,  1.22s/it]

Memory usage after optimization is: 125.983 MB
Decreased by 86.9%

,id,pre_since_opened_min,pre_since_opened_max,pre_since_opened_mean,pre_since_confirmed_min,pre_since_confirmed_max,pre_since_confirmed_mean,pre_pterm_min,pre_pterm_max,pre_pterm_mean,...,paym_std,worst_paym_ever,paym_switches,last_vs_mean,last_vs_std_util,last_vs_std_paym,last_util_x_std,last_paym_x_std,last_vs_mean_util_x_std,last_vs_mean_paym_x_std
0,1000000,8,17,11.400000,0,16,7.600000,1,16,9.800000,...,0.497687,3.000000,0,0.383333,-49.084725,0.141187,0.105087,1.652653,-4.249701e+00,0.125916
1,1000001,0,15,9.500000,2,16,7.000000,2,17,11.750000,...,0.821876,4.000000,1,-2.208333,-87.588627,1.050208,0.066896,1.686171,-2.787340e+00,0.371949
2,1000002,0,15,8.777778,4,6,5.777778,1,14,7.222222,...,0.571149,3.000000,1,-0.958333,-33.630909,1.555687,0.120330,2.370332,-6.546868e+00,1.446305
3,1000003,4,4,4.000000,0,0,0.000000,0,0,0.000000,...,0.375534,1.000000,3,0.833333,NaN,NaN,NaN,NaN,NaN,NaN
4,1000004,0,17,8.428571,0,12,5.428571,0,17,10.857143,...,0.670791,3.142857,0,1.389881,-0.000018,0.518412,400891.666997,1.901695,-1.139678e+07,0.431956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,1249995,0,15,8.000000,1,12,5.923077,3,16,9.307692,...,0.669241,3.538462,0,-1.641026,-19.557419,0.705650,0.119205,2.289213,-1.114719e+01,0.679217
249996,1249996,4,19,12.823529,0,10,3.117647,0,14,4.529412,...,0.554620,3.000000,0,-1.284314,-0.000012,1.080873,498158.077256,3.568149,-1.233674e+07,1.876104
249997,1249997,12,12,12.000000,9,9,9.000000,4,4,4.000000,...,0.898717,4.000000,1,-2.958333,NaN,NaN,NaN,NaN,NaN,NaN
249998,1249998,0,15,8.200000,0,12,6.400000,0,16,9.000000,...,0.472853,3.400000,7,-1.116667,-0.000010,-0.582343,289970.641251,0.496676,-2.600070e+07,-0.286319
249999,1249999,1,19,10.066667,0,17,9.666667,1,17,8.466667,...,0.907393,3.600000,1,-2.063889,-0.000018,0.668694,430331.385165,2.610117,-1.108534e+07,0.621074

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Columns: 159 entries, id to last_vs_mean_paym_x_std
dtypes: float64(98), int32(1), int64(20), int8(40)
memory usage: 235.6 MB

Transforming transactions data:  58%|██████▍    | 7/12 [11:13<08:02, 96.48s/it]
Reading dataset with pandas:   0%|                       | 0/1 [00:00<?, ?it/s]

chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\train_data_5.pq
Memory usage of dataframe is 1001.02 MB

  0%|                                                   | 0/61 [00:00<?, ?it/s]

 20%|████████                                 | 12/61 [00:00<00:00, 118.99it/s]

 46%|██████████████████▊                      | 28/61 [00:00<00:00, 140.85it/s]

 74%|██████████████████████████████▏          | 45/61 [00:00<00:00, 150.37it/s]

100%|█████████████████████████████████████████| 61/61 [00:00<00:00, 119.29it/s]

Reading dataset with pandas: 100%|███████████████| 1/1 [00:01<00:00,  1.41s/it]

Memory usage after optimization is: 131.281 MB
Decreased by 86.9%

,id,pre_since_opened_min,pre_since_opened_max,pre_since_opened_mean,pre_since_confirmed_min,pre_since_confirmed_max,pre_since_confirmed_mean,pre_pterm_min,pre_pterm_max,pre_pterm_mean,...,paym_std,worst_paym_ever,paym_switches,last_vs_mean,last_vs_std_util,last_vs_std_paym,last_util_x_std,last_paym_x_std,last_vs_mean_util_x_std,last_vs_mean_paym_x_std
0,1250000,9,17,13.000,3,10,6.50,14,15,14.500,...,0.982214,4.000,1,-1.750000,-198.182655,0.707104,5.696137e-03,0.576979,-1.446819e+00,0.061381
1,1250001,5,18,11.800,5,13,9.00,8,16,12.800,...,0.765272,3.400,1,-1.800000,-21.622462,-0.008164,4.624809e-01,1.828917,-4.624811e+00,-0.008507
2,1250002,7,7,7.000,6,6,6.00,1,4,2.500,...,1.605280,4.000,1,-2.270833,1.414212,0.707099,1.767767e+13,0.206239,1.767764e+13,0.005524
3,1250003,1,19,8.750,1,17,8.75,1,15,8.875,...,0.625961,3.375,0,-2.015625,-12.165500,0.701116,2.083452e-01,2.675855,-1.191474e+01,0.684401
4,1250004,5,17,10.125,0,17,7.00,0,17,9.250,...,0.649211,3.250,1,-1.458333,-15.709423,-0.595457,4.317165e-01,0.874677,-1.417110e+01,-0.656008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,1499995,7,18,13.250,1,10,5.25,2,17,11.750,...,0.478714,3.250,1,-1.468750,-6.355868,0.793605,7.394732e+00,2.058007,-2.172206e+01,0.689238
249996,1499996,0,19,11.600,1,16,8.70,0,15,10.100,...,0.901423,3.700,1,-2.058333,-32.493214,0.951879,1.205900e-01,2.306838,-5.788322e+00,0.630988
249997,1499997,7,7,7.000,2,2,2.00,17,17,17.000,...,1.664101,4.000,1,-2.208333,NaN,NaN,NaN,NaN,NaN,NaN
249998,1499998,1,1,1.000,6,6,6.00,10,10,10.000,...,0.277350,4.000,2,-1.458333,NaN,NaN,NaN,NaN,NaN,NaN
249999,1499999,0,12,4.125,0,17,8.75,0,17,9.000,...,0.587497,3.625,1,-1.812500,2.828421,0.920580,8.838834e+12,3.141888,8.838813e+12,1.132004

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Columns: 159 entries, id to last_vs_mean_paym_x_std
dtypes: float64(98), int32(1), int64(24), int8(36)
memory usage: 242.2 MB

Transforming transactions data:  67%|███████▎   | 8/12 [12:51<06:27, 96.94s/it]
Reading dataset with pandas:   0%|                       | 0/1 [00:00<?, ?it/s]

chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\train_data_6.pq
Memory usage of dataframe is 1012.91 MB

  0%|                                                   | 0/61 [00:00<?, ?it/s]

 18%|███████▍                                 | 11/61 [00:00<00:00, 109.32it/s]

 36%|██████████████▊                          | 22/61 [00:00<00:00, 108.34it/s]

 59%|████████████████████████▏                | 36/61 [00:00<00:00, 120.05it/s]

100%|█████████████████████████████████████████| 61/61 [00:00<00:00, 106.47it/s]

Reading dataset with pandas: 100%|███████████████| 1/1 [00:01<00:00,  1.52s/it]

Memory usage after optimization is: 132.840 MB
Decreased by 86.9%

,id,pre_since_opened_min,pre_since_opened_max,pre_since_opened_mean,pre_since_confirmed_min,pre_since_confirmed_max,pre_since_confirmed_mean,pre_pterm_min,pre_pterm_max,pre_pterm_mean,...,paym_std,worst_paym_ever,paym_switches,last_vs_mean,last_vs_std_util,last_vs_std_paym,last_util_x_std,last_paym_x_std,last_vs_mean_util_x_std,last_vs_mean_paym_x_std
0,1500000,4,18,10.833333,1,16,9.333333,0,16,8.166667,...,0.759867,3.333333,1,-1.689815,-0.000012,0.568100,589255.459745,2.643095,-1.682652e+07,0.728949
1,1500001,2,13,7.500000,16,17,16.500000,0,17,8.500000,...,0.277350,2.500000,2,-0.520833,-66.821271,0.707106,0.101015,0.592938,-2.727411e+00,0.270689
2,1500002,2,19,8.750000,0,17,5.250000,1,17,8.875000,...,0.789936,4.000000,0,0.770833,-56.989988,1.221994,0.064866,2.155229,-4.502806e+00,0.597057
3,1500003,1,17,8.142857,2,17,9.571429,0,13,6.571429,...,0.803129,3.571429,0,-1.607143,-38.265246,1.635418,0.102252,2.124351,-3.600720e+00,0.919362
4,1500004,10,19,15.250000,6,13,9.250000,0,10,5.250000,...,0.757970,3.250000,0,-1.885417,-14.590080,0.678918,0.080320,3.282768,-6.023989e+00,0.997456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,1749995,0,17,8.923077,1,13,7.923077,0,16,6.846154,...,0.647756,3.000000,0,-1.304487,-15.607182,0.963047,0.380972,2.492755,-1.610830e+01,1.099140
249996,1749996,6,6,6.000000,16,16,16.000000,0,0,0.000000,...,0.506370,2.000000,7,0.583333,NaN,NaN,NaN,NaN,NaN,NaN
249997,1749997,11,11,11.000000,9,9,9.000000,4,4,4.000000,...,0.277350,4.000000,0,-0.541667,NaN,NaN,NaN,NaN,NaN,NaN
249998,1749998,0,18,7.090909,0,11,6.181818,0,13,4.727273,...,0.355682,3.000000,0,-1.549242,-79.034855,0.027216,0.064701,1.983301,-1.323420e+00,0.042703
249999,1749999,19,19,19.000000,10,10,10.000000,17,17,17.000000,...,1.519109,4.000000,1,-2.583333,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Columns: 159 entries, id to last_vs_mean_paym_x_std
dtypes: float64(98), int32(1), int64(24), int8(36)
memory usage: 242.2 MB

Transforming transactions data:  75%|████████▎  | 9/12 [14:30<04:52, 97.53s/it]
Reading dataset with pandas:   0%|                       | 0/1 [00:00<?, ?it/s]

chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\train_data_7.pq
Memory usage of dataframe is 1034.22 MB

  0%|                                                   | 0/61 [00:00<?, ?it/s]

 25%|██████████                               | 15/61 [00:00<00:00, 147.96it/s]

 54%|██████████████████████▏                  | 33/61 [00:00<00:00, 161.08it/s]

100%|█████████████████████████████████████████| 61/61 [00:00<00:00, 128.19it/s]

Reading dataset with pandas: 100%|███████████████| 1/1 [00:01<00:00,  1.41s/it]

Memory usage after optimization is: 135.635 MB
Decreased by 86.9%

,id,pre_since_opened_min,pre_since_opened_max,pre_since_opened_mean,pre_since_confirmed_min,pre_since_confirmed_max,pre_since_confirmed_mean,pre_pterm_min,pre_pterm_max,pre_pterm_mean,...,paym_std,worst_paym_ever,paym_switches,last_vs_mean,last_vs_std_util,last_vs_std_paym,last_util_x_std,last_paym_x_std,last_vs_mean_util_x_std,last_vs_mean_paym_x_std
0,1750000,0,13,7.277778,1,17,9.055556,1,17,8.944444,...,0.707610,3.500000,0,-1.659722,-0.000020,0.592660,3.535531e+05,2.044197,-1.021376e+07,0.507835
1,1750001,3,13,8.500000,2,9,7.250000,4,17,9.250000,...,0.360288,3.000000,1,-0.833333,-0.000008,1.498703,2.647058e+05,4.194596,-1.848529e+07,3.013020
2,1750002,0,19,10.444444,1,16,8.944444,1,17,10.055556,...,0.740563,3.666667,0,-1.937500,-11.200320,0.699107,3.472117e+00,2.386475,-8.439185e+00,0.596619
3,1750003,0,19,9.272727,0,17,9.318182,0,17,8.363636,...,0.528911,3.000000,0,-1.357955,-14.073575,1.161833,2.153439e-01,2.724624,-1.225503e+01,1.292399
4,1750004,0,13,7.000000,4,9,6.800000,4,15,7.400000,...,1.256981,4.000000,0,-2.608333,-123.397627,-0.092253,3.475936e-02,0.700067,-2.004456e+00,-0.006775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,1999995,9,12,10.000000,1,16,11.000000,8,17,13.666667,...,1.012739,4.000000,0,0.625000,-33.060787,1.104267,1.645448e-01,1.977805,-2.486455e+00,0.454361
249996,1999996,6,19,13.300000,1,9,6.500000,0,15,5.600000,...,0.709279,3.100000,3,-1.383333,-0.000008,1.163790,1.129385e+06,2.663709,-2.100656e+07,1.237336
249997,1999997,0,18,9.428571,1,11,7.142857,4,17,9.000000,...,0.949676,3.571429,1,-1.904762,-301.404430,-1.794265,1.327092e-02,0.084595,-6.502751e-01,-1.849002
249998,1999998,1,19,9.222222,3,17,10.166667,1,17,8.944444,...,0.632806,3.166667,0,-1.576389,-49.113221,1.182030,8.991636e-02,3.012901,-3.113104e+00,1.336605
249999,1999999,7,7,7.000000,2,2,2.000000,9,9,9.000000,...,1.652504,4.000000,1,-2.333333,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Columns: 159 entries, id to last_vs_mean_paym_x_std
dtypes: float64(98), int32(1), int64(24), int8(36)
memory usage: 242.2 MB

Transforming transactions data:  83%|████████▎ | 10/12 [16:08<03:15, 97.90s/it]
Reading dataset with pandas:   0%|                       | 0/1 [00:00<?, ?it/s]

chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\train_data_8.pq
Memory usage of dataframe is 1043.70 MB

  0%|                                                   | 0/61 [00:00<?, ?it/s]

 25%|██████████                               | 15/61 [00:00<00:00, 145.11it/s]

 52%|█████████████████████▌                   | 32/61 [00:00<00:00, 159.36it/s]

100%|█████████████████████████████████████████| 61/61 [00:00<00:00, 130.33it/s]

Reading dataset with pandas: 100%|███████████████| 1/1 [00:01<00:00,  1.38s/it]

Memory usage after optimization is: 136.878 MB
Decreased by 86.9%

,id,pre_since_opened_min,pre_since_opened_max,pre_since_opened_mean,pre_since_confirmed_min,pre_since_confirmed_max,pre_since_confirmed_mean,pre_pterm_min,pre_pterm_max,pre_pterm_mean,...,paym_std,worst_paym_ever,paym_switches,last_vs_mean,last_vs_std_util,last_vs_std_paym,last_util_x_std,last_paym_x_std,last_vs_mean_util_x_std,last_vs_mean_paym_x_std
0,2000000,0,19,8.761905,3,17,10.142857,1,15,8.666667,...,0.736982,3.619048,0,-1.859127,-0.000024,1.270507,233804.809143,2.559463,-1.033417e+07,0.951001
1,2000001,0,14,9.333333,2,17,8.333333,1,9,3.666667,...,0.477037,3.000000,1,-1.395833,-0.000013,1.248128,151382.462485,3.703459,-1.922557e+07,1.956052
2,2000002,0,18,8.818182,1,13,8.000000,1,16,6.545455,...,0.728655,3.727273,0,-1.954545,-84.593146,-0.281292,0.029895,1.495285,-2.286966e+00,-0.215507
3,2000003,4,16,10.285714,0,14,7.428571,1,11,5.142857,...,0.552810,2.285714,4,-0.904762,-0.000014,0.815546,680335.742376,1.435094,-1.746195e+07,0.636067
4,2000004,1,18,9.833333,1,17,9.500000,0,17,7.166667,...,0.375323,3.000000,1,-0.842593,-35.660428,2.443525,0.049999,2.561488,-5.705428e+00,1.831925
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,2249995,2,17,8.222222,2,17,7.111111,2,14,7.944444,...,0.934991,3.500000,0,-1.914352,-0.000020,0.835218,176776.658034,2.574614,-1.003699e+07,0.754780
249996,2249996,0,18,6.411765,2,16,7.352941,1,17,7.294118,...,0.716672,3.647059,0,-1.977941,-21.730086,0.371983,0.330931,2.229263,-9.519142e+00,0.339541
249997,2249997,5,17,10.111111,0,17,9.000000,4,17,9.888889,...,0.708560,3.000000,1,-1.509259,-14.034252,1.154262,0.061437,3.250163,-1.191876e+01,1.518867
249998,2249998,1,19,9.200000,6,11,7.300000,1,15,8.800000,...,0.850339,3.700000,1,-1.804167,-22.898519,1.083180,0.135926,2.260734,-6.769093e+00,0.754737
249999,2249999,1,19,7.923077,0,13,4.230769,3,17,6.346154,...,0.647316,3.884615,0,-2.641026,-16.872697,0.376435,0.524379,1.447450,-1.288761e+01,0.098243

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Columns: 159 entries, id to last_vs_mean_paym_x_std
dtypes: float64(98), int32(1), int64(17), int8(43)
memory usage: 230.6 MB

Transforming transactions data:  92%|█████████▏| 11/12 [17:47<01:38, 98.09s/it]
Reading dataset with pandas:   0%|                       | 0/1 [00:00<?, ?it/s]

chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\train_data_9.pq
Memory usage of dataframe is 1063.08 MB

  0%|                                                   | 0/61 [00:00<?, ?it/s]

 21%|████████▋                                | 13/61 [00:00<00:00, 129.32it/s]

 44%|██████████████████▏                      | 27/61 [00:00<00:00, 133.25it/s]

 67%|███████████████████████████▌             | 41/61 [00:00<00:00, 124.10it/s]

100%|█████████████████████████████████████████| 61/61 [00:00<00:00, 107.32it/s]

Reading dataset with pandas: 100%|███████████████| 1/1 [00:01<00:00,  1.48s/it]

Memory usage after optimization is: 139.420 MB
Decreased by 86.9%

,id,pre_since_opened_min,pre_since_opened_max,pre_since_opened_mean,pre_since_confirmed_min,pre_since_confirmed_max,pre_since_confirmed_mean,pre_pterm_min,pre_pterm_max,pre_pterm_mean,...,paym_std,worst_paym_ever,paym_switches,last_vs_mean,last_vs_std_util,last_vs_std_paym,last_util_x_std,last_paym_x_std,last_vs_mean_util_x_std,last_vs_mean_paym_x_std
0,2250000,2,12,7.250000,2,17,7.750000,4,16,10.375000,...,0.759291,4.000000,1,-2.213542,-15.831213,1.006257,2.207550e-01,2.189638,-1.448704e+01,0.551265
1,2250001,12,12,12.000000,2,16,9.000000,4,16,10.000000,...,0.898717,4.000000,1,-2.958333,-6.942507,0.000000,2.592719e+00,0.000000,-1.166725e+01,0.000000
2,2250002,2,16,8.333333,4,16,9.111111,0,17,10.333333,...,0.507463,3.000000,1,-0.972222,-0.000006,1.578887,1.375000e+06,2.636054,-1.940278e+07,1.643991
3,2250003,9,12,11.250000,0,10,6.500000,1,6,3.500000,...,0.732160,4.000000,0,-2.645833,-34.542018,0.296078,3.039765e-01,1.794289,-3.191755e+00,0.118740
4,2250004,3,3,3.000000,6,6,6.000000,2,2,2.000000,...,0.650444,2.000000,10,-0.375000,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,2499995,0,19,12.642857,1,11,5.714286,0,15,7.214286,...,0.706135,3.571429,1,-1.994048,-0.000019,0.893849,4.952520e+05,2.660377,-1.282939e+07,0.788053
249996,2499996,1,11,3.400000,2,17,11.600000,8,14,12.200000,...,0.713604,3.400000,1,-1.483333,-144.970672,-0.037012,2.267675e-02,0.985050,-1.192797e+00,-0.016887
249997,2499997,1,17,10.714286,0,17,7.428571,0,17,10.285714,...,0.533420,3.000000,1,-1.127976,-19.919814,0.205950,2.612511e-01,1.329493,-1.065905e+01,0.204766
249998,2499998,3,19,10.142857,9,12,9.714286,1,14,4.142857,...,0.538181,3.000000,1,-0.851190,-250.133053,1.541495,1.729663e-02,2.902831,-9.167215e-01,1.946368
249999,2499999,0,17,6.933333,3,17,8.200000,1,17,6.800000,...,0.720517,3.800000,1,-1.775000,3.872972,1.058400,6.454972e+12,1.972970,6.454953e+12,0.617349

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Columns: 159 entries, id to last_vs_mean_paym_x_std
dtypes: float64(98), int32(1), int64(24), int8(36)
memory usage: 242.2 MB

Transforming transactions data: 100%|██████████| 12/12 [19:26<00:00, 97.17s/it]

In [11]:
data = read_parquet_dataset_from_local(path, 'processed', 0, 12, verbose=1)

Reading chunks:

C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_000.parquet
C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_001.parquet
C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_002.parquet
C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_003.parquet
C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_004.parquet
C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_005.parquet
C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_006.parquet
C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_007.parquet
C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_008.parquet
C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_009.parquet
C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_010.parquet
C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_011.parquet

Reading dataset with pandas:   0%|                      | 0/12 [00:00<?, ?it/s]

chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_000.parquet
Memory usage of dataframe is 235.56 MB

  0%|                                                  | 0/159 [00:00<?, ?it/s]
 45%|█████████████████▊                      | 71/159 [00:00<00:00, 707.82it/s]
100%|███████████████████████████████████████| 159/159 [00:00<00:00, 525.09it/s]
Reading dataset with pandas:   8%|█▏            | 1/12 [00:00<00:08,  1.26it/s]

Memory usage after optimization is: 72.479 MB
Decreased by 69.2%
chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_001.parquet
Memory usage of dataframe is 242.23 MB

  0%|                                                  | 0/159 [00:00<?, ?it/s]
 48%|███████████████████                     | 76/159 [00:00<00:00, 751.12it/s]
100%|███████████████████████████████████████| 159/159 [00:00<00:00, 574.00it/s]
Reading dataset with pandas:  17%|██▎           | 2/12 [00:01<00:07,  1.34it/s]

Memory usage after optimization is: 73.195 MB
Decreased by 69.8%
chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_002.parquet
Memory usage of dataframe is 225.54 MB

  0%|                                                  | 0/159 [00:00<?, ?it/s]
 49%|███████████████████▌                    | 78/159 [00:00<00:00, 772.07it/s]
100%|███████████████████████████████████████| 159/159 [00:00<00:00, 586.63it/s]
Reading dataset with pandas:  25%|███▌          | 3/12 [00:02<00:06,  1.39it/s]

Memory usage after optimization is: 71.049 MB
Decreased by 68.5%
chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_003.parquet
Memory usage of dataframe is 242.23 MB

  0%|                                                  | 0/159 [00:00<?, ?it/s]
 48%|███████████████████                     | 76/159 [00:00<00:00, 751.74it/s]
100%|███████████████████████████████████████| 159/159 [00:00<00:00, 572.28it/s]
Reading dataset with pandas:  33%|████▋         | 4/12 [00:02<00:05,  1.40it/s]

Memory usage after optimization is: 73.195 MB
Decreased by 69.8%
chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_004.parquet
Memory usage of dataframe is 238.90 MB

  0%|                                                  | 0/159 [00:00<?, ?it/s]
 48%|███████████████████                     | 76/159 [00:00<00:00, 743.72it/s]
100%|███████████████████████████████████████| 159/159 [00:00<00:00, 554.24it/s]
Reading dataset with pandas:  42%|█████▊        | 5/12 [00:03<00:05,  1.34it/s]

Memory usage after optimization is: 72.718 MB
Decreased by 69.6%
chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_005.parquet
Memory usage of dataframe is 237.23 MB

  0%|                                                  | 0/159 [00:00<?, ?it/s]
 47%|██████████████████▊                     | 75/159 [00:00<00:00, 733.60it/s]
100%|███████████████████████████████████████| 159/159 [00:00<00:00, 552.51it/s]
Reading dataset with pandas:  50%|███████       | 6/12 [00:04<00:04,  1.35it/s]

Memory usage after optimization is: 72.479 MB
Decreased by 69.4%
chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_006.parquet
Memory usage of dataframe is 235.56 MB

  0%|                                                  | 0/159 [00:00<?, ?it/s]
 45%|██████████████████                      | 72/159 [00:00<00:00, 713.15it/s]
100%|███████████████████████████████████████| 159/159 [00:00<00:00, 518.39it/s]
Reading dataset with pandas:  58%|████████▏     | 7/12 [00:05<00:03,  1.35it/s]

Memory usage after optimization is: 72.241 MB
Decreased by 69.3%
chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_007.parquet
Memory usage of dataframe is 242.23 MB

  0%|                                                  | 0/159 [00:00<?, ?it/s]
 46%|██████████████████▎                     | 73/159 [00:00<00:00, 724.97it/s]
100%|███████████████████████████████████████| 159/159 [00:00<00:00, 541.60it/s]
Reading dataset with pandas:  67%|█████████▎    | 8/12 [00:05<00:02,  1.36it/s]

Memory usage after optimization is: 73.195 MB
Decreased by 69.8%
chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_008.parquet
Memory usage of dataframe is 242.23 MB

  0%|                                                  | 0/159 [00:00<?, ?it/s]
 47%|██████████████████▌                     | 74/159 [00:00<00:00, 730.26it/s]
100%|███████████████████████████████████████| 159/159 [00:00<00:00, 549.07it/s]
Reading dataset with pandas:  75%|██████████▌   | 9/12 [00:06<00:02,  1.37it/s]

Memory usage after optimization is: 73.195 MB
Decreased by 69.8%
chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_009.parquet
Memory usage of dataframe is 242.23 MB

  0%|                                                  | 0/159 [00:00<?, ?it/s]
 47%|██████████████████▌                     | 74/159 [00:00<00:00, 724.87it/s]
100%|███████████████████████████████████████| 159/159 [00:00<00:00, 551.48it/s]
Reading dataset with pandas:  83%|██████████▊  | 10/12 [00:07<00:01,  1.37it/s]

Memory usage after optimization is: 73.195 MB
Decreased by 69.8%
chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_010.parquet
Memory usage of dataframe is 230.55 MB

  0%|                                                  | 0/159 [00:00<?, ?it/s]
 47%|██████████████████▊                     | 75/159 [00:00<00:00, 739.19it/s]
100%|███████████████████████████████████████| 159/159 [00:00<00:00, 555.65it/s]
Reading dataset with pandas:  92%|███████████▉ | 11/12 [00:08<00:00,  1.39it/s]

Memory usage after optimization is: 71.526 MB
Decreased by 69.0%
chunk_path C:\Users\User\-_PRACTICAL\junior-final-work\train_data\processed_chunk_011.parquet
Memory usage of dataframe is 242.23 MB

  0%|                                                  | 0/159 [00:00<?, ?it/s]
 45%|██████████████████                      | 72/159 [00:00<00:00, 716.94it/s]
100%|███████████████████████████████████████| 159/159 [00:00<00:00, 551.07it/s]
Reading dataset with pandas: 100%|█████████████| 12/12 [00:08<00:00,  1.37it/s]

Memory usage after optimization is: 73.195 MB
Decreased by 69.8%

In [12]:
data.info(max_cols=5, memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000000 entries, 0 to 2999999
Columns: 159 entries, id to last_vs_mean_paym_x_std
dtypes: float16(81), float32(17), int16(13), int32(1), int8(45), uint8(2)
memory usage: 878.3 MB

## merge with target

In [13]:
target_path = r"C:\Users\User\-_PRACTICAL\junior-final-work\train_target.csv"
target_df = pd.read_csv(target_path)

data = data.merge(target_df, on='id', how='left')

print(data.shape)
print(data.head())

(3000000, 160)
   id  pre_since_opened_min  pre_since_opened_max  pre_since_opened_mean  \
0   0                     1                    18               8.101562
1   1                     2                    18              11.429688
2   2                     0                    13               8.335938
3   3                     1                    18               7.000000
4   4                    12                    12              12.000000

   pre_since_confirmed_min  pre_since_confirmed_max  pre_since_confirmed_mean  \
0                        0                       12                  7.601562
1                        3                       14                  7.644531
2                        9                       14                 10.664062
3                        0                       16                  7.332031
4                        9                        9                  9.000000

   pre_pterm_min  pre_pterm_max  pre_pterm_mean  ...  worst_paym_ever  \
0              1             15        7.101562  ...         3.400391
1              0             15        6.644531  ...         3.142578
2              4             13        7.000000  ...         3.333984
3              0             16        7.601562  ...         3.000000
4              4              4        4.000000  ...         4.000000

   paym_switches  last_vs_mean  last_vs_std_util  last_vs_std_paym  \
0              2     -1.612305         -0.000014          0.696289
1              0      1.294922         -0.000015          1.433594
2              0      1.097656         -2.836837          1.029297
3              1     -1.075195        -12.723925          1.835938
4              0     -0.083313          0.000000          0.000000

   last_util_x_std  last_paym_x_std  last_vs_mean_util_x_std  \
0    118585.390625         2.416016            -1.278351e+07
1    218668.218750         2.962891            -9.574545e+06
2         6.110087         3.537109            -6.619274e+00
3         0.111715         3.035156            -1.147312e+01
4         0.000000         0.000000             0.000000e+00

   last_vs_mean_paym_x_std  flag
0                 0.746582     0
1                 1.324219     0
2                 1.354492     0
3                 1.931641     0
4                 0.000000     0

[5 rows x 160 columns]

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

In [15]:
X = data.drop(['flag', 'id'], axis=1)
y = data["flag"]

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y),
    y=y
)
class_weights_dict = {0: class_weights[0], 1: class_weights[1]}
print("Class weights:", class_weights_dict)

Class weights: {0: np.float64(0.5183929266321947), 1: np.float64(14.092181657616354)}

# 4. Baseline Models & Experiments

This section contains multiple experiments with different models and configurations.
The goal is to explore model behavior and establish strong baselines.

## modeling 13.03

In [160]:
X_train, X_val, y_train, y_val = train_test_split(
    X, y, 
    train_size=0.7, 
    stratify=y, 
    random_state=42
)

In [51]:
model = CatBoostClassifier(
    iterations=1000,
    depth=6,
    learning_rate=0.03,
    loss_function="Logloss",
    eval_metric="AUC",
    verbose=100
)

model.fit(X_train, y_train,
          eval_set=(X_val, y_val))

0:	test: 0.5898612	best: 0.5898612 (0)	total: 300ms	remaining: 4m 59s
100:	test: 0.7037026	best: 0.7037026 (100)	total: 32.3s	remaining: 4m 47s
200:	test: 0.7120052	best: 0.7120052 (200)	total: 1m 5s	remaining: 4m 18s
300:	test: 0.7165839	best: 0.7165839 (300)	total: 1m 37s	remaining: 3m 46s
400:	test: 0.7198728	best: 0.7198728 (400)	total: 2m 10s	remaining: 3m 14s
500:	test: 0.7222433	best: 0.7222433 (500)	total: 2m 42s	remaining: 2m 42s
600:	test: 0.7242320	best: 0.7242320 (600)	total: 3m 20s	remaining: 2m 13s
700:	test: 0.7256523	best: 0.7256523 (700)	total: 3m 55s	remaining: 1m 40s
800:	test: 0.7267832	best: 0.7267832 (800)	total: 4m 30s	remaining: 1m 7s
900:	test: 0.7276708	best: 0.7276708 (900)	total: 5m 5s	remaining: 33.6s
999:	test: 0.7283825	best: 0.7283825 (999)	total: 5m 39s	remaining: 0us

bestTest = 0.7283824774
bestIteration = 999

## param grid

In [60]:
grid = {
    'depth': [6, 8],
    'learning_rate': [0.03, 0.05],
    'l2_leaf_reg': [5, 7],
}

best_auc = 0
best_params = None

for depth, lr, l2 in product(grid['depth'], grid['learning_rate'], grid['l2_leaf_reg']):
    print(f"Testing: depth={depth}, lr={lr}, l2_leaf_reg={l2}")
    model = CatBoostClassifier(
        iterations=1000,
        depth=depth,
        learning_rate=lr,
        l2_leaf_reg=l2,
        loss_function='Logloss',
        eval_metric='AUC',
        early_stopping_rounds=50,
        verbose=100
    )
    model.fit(X_train, y_train, eval_set=(X_val, y_val))
    
    auc = model.get_best_score()['validation']['AUC']
    print(f"AUC: {auc}\n")
    
    if auc > best_auc:
        best_auc = auc
        best_params = {'depth': depth, 'learning_rate': lr, 'l2_leaf_reg': l2}

print(f"Best AUC: {best_auc} with params {best_params}")

Testing: depth=6, lr=0.03, l2_leaf_reg=5
0:	test: 0.5594944	best: 0.5594944 (0)	total: 325ms	remaining: 5m 24s
100:	test: 0.7034215	best: 0.7034215 (100)	total: 33.3s	remaining: 4m 56s
200:	test: 0.7113022	best: 0.7113022 (200)	total: 1m 14s	remaining: 4m 56s
300:	test: 0.7159701	best: 0.7159701 (300)	total: 1m 55s	remaining: 4m 27s
400:	test: 0.7189414	best: 0.7189414 (400)	total: 2m 35s	remaining: 3m 52s
500:	test: 0.7213733	best: 0.7213733 (500)	total: 3m 13s	remaining: 3m 12s
600:	test: 0.7231458	best: 0.7231458 (600)	total: 3m 49s	remaining: 2m 32s
700:	test: 0.7243845	best: 0.7243845 (700)	total: 4m 25s	remaining: 1m 53s
800:	test: 0.7252912	best: 0.7252912 (800)	total: 4m 59s	remaining: 1m 14s
900:	test: 0.7261244	best: 0.7261244 (900)	total: 5m 34s	remaining: 36.7s
999:	test: 0.7266658	best: 0.7266658 (999)	total: 6m 9s	remaining: 0us

bestTest = 0.7266658342
bestIteration = 999

AUC: 0.726665834216917

Testing: depth=6, lr=0.03, l2_leaf_reg=7
0:	test: 0.5594896	best: 0.5594896 (0)	total: 370ms	remaining: 6m 9s
100:	test: 0.7035989	best: 0.7035989 (100)	total: 39.9s	remaining: 5m 55s
200:	test: 0.7110887	best: 0.7110887 (200)	total: 1m 21s	remaining: 5m 24s
300:	test: 0.7157253	best: 0.7157253 (300)	total: 1m 59s	remaining: 4m 37s
400:	test: 0.7189491	best: 0.7189491 (400)	total: 2m 38s	remaining: 3m 57s
500:	test: 0.7211794	best: 0.7211794 (500)	total: 3m 17s	remaining: 3m 16s
600:	test: 0.7228117	best: 0.7228117 (600)	total: 3m 53s	remaining: 2m 34s
700:	test: 0.7242128	best: 0.7242128 (700)	total: 4m 28s	remaining: 1m 54s
800:	test: 0.7251415	best: 0.7251415 (800)	total: 5m 8s	remaining: 1m 16s
900:	test: 0.7259668	best: 0.7259671 (899)	total: 5m 45s	remaining: 37.9s
999:	test: 0.7265463	best: 0.7265463 (999)	total: 6m 22s	remaining: 0us

bestTest = 0.72654635
bestIteration = 999

AUC: 0.7265463499827838

Testing: depth=6, lr=0.05, l2_leaf_reg=5
0:	test: 0.5594944	best: 0.5594944 (0)	total: 325ms	remaining: 5m 24s
100:	test: 0.7092835	best: 0.7092835 (100)	total: 35.5s	remaining: 5m 15s
200:	test: 0.7169662	best: 0.7169662 (200)	total: 1m 11s	remaining: 4m 46s
300:	test: 0.7211686	best: 0.7211686 (300)	total: 1m 50s	remaining: 4m 17s
400:	test: 0.7237677	best: 0.7237677 (400)	total: 2m 28s	remaining: 3m 41s
500:	test: 0.7252999	best: 0.7252999 (500)	total: 3m 5s	remaining: 3m 4s
600:	test: 0.7263998	best: 0.7263998 (600)	total: 3m 43s	remaining: 2m 28s
700:	test: 0.7271981	best: 0.7271981 (700)	total: 4m 17s	remaining: 1m 49s
800:	test: 0.7277439	best: 0.7277439 (800)	total: 4m 53s	remaining: 1m 12s
900:	test: 0.7282713	best: 0.7282727 (898)	total: 5m 26s	remaining: 35.9s
999:	test: 0.7286669	best: 0.7286669 (999)	total: 6m 4s	remaining: 0us

bestTest = 0.7286668696
bestIteration = 999

AUC: 0.7286668696424248

Testing: depth=6, lr=0.05, l2_leaf_reg=7
0:	test: 0.5594896	best: 0.5594896 (0)	total: 328ms	remaining: 5m 27s
100:	test: 0.7089420	best: 0.7089420 (100)	total: 37.9s	remaining: 5m 37s
200:	test: 0.7168165	best: 0.7168165 (200)	total: 1m 16s	remaining: 5m 5s
300:	test: 0.7209851	best: 0.7209851 (300)	total: 1m 58s	remaining: 4m 34s
400:	test: 0.7235628	best: 0.7235628 (400)	total: 2m 33s	remaining: 3m 49s
500:	test: 0.7251296	best: 0.7251296 (500)	total: 3m 10s	remaining: 3m 9s
600:	test: 0.7263735	best: 0.7263735 (600)	total: 3m 48s	remaining: 2m 31s
700:	test: 0.7271779	best: 0.7271779 (700)	total: 4m 26s	remaining: 1m 53s
800:	test: 0.7278103	best: 0.7278103 (800)	total: 5m 2s	remaining: 1m 15s
900:	test: 0.7282318	best: 0.7282318 (900)	total: 5m 37s	remaining: 37.1s
999:	test: 0.7286416	best: 0.7286416 (999)	total: 6m 12s	remaining: 0us

bestTest = 0.7286415832
bestIteration = 999

AUC: 0.7286415831735593

Testing: depth=8, lr=0.03, l2_leaf_reg=5
0:	test: 0.5676545	best: 0.5676545 (0)	total: 381ms	remaining: 6m 20s
100:	test: 0.7070348	best: 0.7070348 (100)	total: 44.4s	remaining: 6m 35s
200:	test: 0.7149661	best: 0.7149661 (200)	total: 1m 29s	remaining: 5m 55s
300:	test: 0.7198799	best: 0.7198799 (300)	total: 2m 16s	remaining: 5m 17s
400:	test: 0.7225690	best: 0.7225690 (400)	total: 3m 4s	remaining: 4m 34s
500:	test: 0.7243712	best: 0.7243712 (500)	total: 3m 51s	remaining: 3m 50s
600:	test: 0.7257149	best: 0.7257149 (600)	total: 4m 37s	remaining: 3m 4s
700:	test: 0.7266961	best: 0.7266961 (700)	total: 5m 21s	remaining: 2m 17s
800:	test: 0.7273869	best: 0.7273869 (800)	total: 6m 4s	remaining: 1m 30s
900:	test: 0.7279917	best: 0.7279917 (900)	total: 6m 48s	remaining: 44.8s
999:	test: 0.7284280	best: 0.7284280 (999)	total: 7m 33s	remaining: 0us

bestTest = 0.7284279946
bestIteration = 999

AUC: 0.7284279946446321

Testing: depth=8, lr=0.03, l2_leaf_reg=7
0:	test: 0.5676503	best: 0.5676503 (0)	total: 367ms	remaining: 6m 6s
100:	test: 0.7070746	best: 0.7070746 (100)	total: 44.5s	remaining: 6m 36s
200:	test: 0.7154031	best: 0.7154031 (200)	total: 1m 32s	remaining: 6m 7s
300:	test: 0.7197262	best: 0.7197262 (300)	total: 2m 20s	remaining: 5m 26s
400:	test: 0.7225379	best: 0.7225379 (400)	total: 3m 8s	remaining: 4m 41s
500:	test: 0.7244599	best: 0.7244599 (500)	total: 3m 51s	remaining: 3m 50s
600:	test: 0.7259018	best: 0.7259018 (600)	total: 4m 35s	remaining: 3m 3s
700:	test: 0.7268346	best: 0.7268346 (700)	total: 5m 23s	remaining: 2m 18s
800:	test: 0.7275321	best: 0.7275321 (800)	total: 6m 5s	remaining: 1m 30s
900:	test: 0.7281166	best: 0.7281166 (900)	total: 6m 48s	remaining: 44.9s
999:	test: 0.7286323	best: 0.7286323 (999)	total: 7m 30s	remaining: 0us

bestTest = 0.7286322539
bestIteration = 999

AUC: 0.7286322539472307

Testing: depth=8, lr=0.05, l2_leaf_reg=5
0:	test: 0.5676545	best: 0.5676545 (0)	total: 402ms	remaining: 6m 42s
100:	test: 0.7131139	best: 0.7131139 (100)	total: 43.8s	remaining: 6m 29s
200:	test: 0.7206121	best: 0.7206121 (200)	total: 1m 27s	remaining: 5m 48s
300:	test: 0.7243026	best: 0.7243026 (300)	total: 2m 10s	remaining: 5m 3s
400:	test: 0.7264737	best: 0.7264784 (399)	total: 2m 53s	remaining: 4m 19s
500:	test: 0.7277823	best: 0.7277823 (500)	total: 3m 40s	remaining: 3m 39s
600:	test: 0.7285960	best: 0.7286013 (599)	total: 4m 21s	remaining: 2m 53s
700:	test: 0.7289983	best: 0.7289983 (700)	total: 5m 4s	remaining: 2m 9s
800:	test: 0.7293835	best: 0.7293835 (800)	total: 5m 46s	remaining: 1m 26s
900:	test: 0.7296891	best: 0.7296891 (900)	total: 6m 29s	remaining: 42.8s
999:	test: 0.7299537	best: 0.7299539 (998)	total: 7m 12s	remaining: 0us

bestTest = 0.7299539258
bestIteration = 998

Shrink model to first 999 iterations.
AUC: 0.7299539257651617

Testing: depth=8, lr=0.05, l2_leaf_reg=7
0:	test: 0.5676503	best: 0.5676503 (0)	total: 401ms	remaining: 6m 40s
100:	test: 0.7129855	best: 0.7129855 (100)	total: 43.1s	remaining: 6m 23s
200:	test: 0.7210546	best: 0.7210546 (200)	total: 1m 25s	remaining: 5m 40s
300:	test: 0.7244434	best: 0.7244434 (300)	total: 2m 7s	remaining: 4m 56s
400:	test: 0.7266775	best: 0.7266775 (400)	total: 2m 50s	remaining: 4m 14s
500:	test: 0.7276451	best: 0.7276451 (500)	total: 3m 31s	remaining: 3m 30s
600:	test: 0.7284622	best: 0.7284643 (599)	total: 4m 11s	remaining: 2m 47s
700:	test: 0.7290276	best: 0.7290276 (700)	total: 4m 52s	remaining: 2m 4s
800:	test: 0.7293935	best: 0.7293978 (799)	total: 5m 33s	remaining: 1m 22s
900:	test: 0.7297261	best: 0.7297261 (900)	total: 6m 15s	remaining: 41.2s
999:	test: 0.7300569	best: 0.7300569 (999)	total: 6m 55s	remaining: 0us

bestTest = 0.7300569308
bestIteration = 999

AUC: 0.7300569308228259

Best AUC: 0.7300569308228259 with params {'depth': 8, 'learning_rate': 0.05, 'l2_leaf_reg': 7}

## modeling 14.03 - 2

In [61]:
best_model = CatBoostClassifier(
    iterations=1000,
    depth=8,
    learning_rate=0.05,
    l2_leaf_reg=7,
    loss_function='Logloss',
    eval_metric='AUC',
    early_stopping_rounds=50,
    verbose=100
)

best_model.fit(X_train, y_train, eval_set=(X_val, y_val))

0:	test: 0.5676503	best: 0.5676503 (0)	total: 379ms	remaining: 6m 18s
100:	test: 0.7129855	best: 0.7129855 (100)	total: 44.6s	remaining: 6m 36s
200:	test: 0.7210546	best: 0.7210546 (200)	total: 1m 34s	remaining: 6m 16s
300:	test: 0.7244434	best: 0.7244434 (300)	total: 2m 20s	remaining: 5m 25s
400:	test: 0.7266775	best: 0.7266775 (400)	total: 3m 4s	remaining: 4m 36s
500:	test: 0.7276451	best: 0.7276451 (500)	total: 3m 51s	remaining: 3m 50s
600:	test: 0.7284622	best: 0.7284643 (599)	total: 4m 36s	remaining: 3m 3s
700:	test: 0.7290276	best: 0.7290276 (700)	total: 5m 23s	remaining: 2m 18s
800:	test: 0.7293935	best: 0.7293978 (799)	total: 6m 6s	remaining: 1m 30s
900:	test: 0.7297261	best: 0.7297261 (900)	total: 6m 46s	remaining: 44.7s
999:	test: 0.7300569	best: 0.7300569 (999)	total: 7m 27s	remaining: 0us

bestTest = 0.7300569308
bestIteration = 999

In [62]:
feature_aucs = []

for col in X_train.columns:
    
    auc = roc_auc_score(y_train, X_train[col])
    
    # симметрия AUC
    if auc < 0.5:
        auc = 1 - auc
        
    feature_aucs.append((col, auc))

feature_auc_df = pd.DataFrame(feature_aucs, columns=['feature', 'auc'])

feature_auc_df = feature_auc_df.sort_values('auc', ascending=False)

In [63]:
importances = best_model.get_feature_importance()

importance_df = pd.DataFrame({
    'feature': X_train.columns,
    'importance': importances
}).sort_values('importance', ascending=False)

In [64]:
print("TOP 20 features by AUC")
print(feature_auc_df.head(20))

print("\nBOTTOM 20 features by AUC")
print(feature_auc_df.tail(20))

print("TOP 20 important features")
print(importance_df.head(20))

print("\nBOTTOM 20 least important features")
print(importance_df.tail(20))

TOP 20 features by AUC
                   feature       auc
58         enc_paym_2_mean  0.603499
61         enc_paym_3_mean  0.603493
55         enc_paym_1_mean  0.601376
64         enc_paym_4_mean  0.601348
67         enc_paym_5_mean  0.598223
70         enc_paym_6_mean  0.595144
73         enc_paym_7_mean  0.594203
76         enc_paym_8_mean  0.593086
79         enc_paym_9_mean  0.592134
82        enc_paym_10_mean  0.589458
85        enc_paym_11_mean  0.589006
88        enc_paym_12_mean  0.588614
56          enc_paym_1_sum  0.573029
52         enc_paym_0_mean  0.572847
33   is_zero_loans530_mean  0.572250
42       is_zero_util_mean  0.566991
59          enc_paym_2_sum  0.565678
53          enc_paym_0_sum  0.563008
35  is_zero_loans3060_mean  0.561879
34    is_zero_loans530_sum  0.560961

BOTTOM 20 features by AUC
                            feature       auc
78                   enc_paym_9_max  0.509234
81                  enc_paym_10_max  0.507445
18     pre_loans_next_pay_summ_mean  0.507278
43          is_zero_over2limit_mean  0.507158
83                  enc_paym_10_sum  0.506775
84                  enc_paym_11_max  0.506445
16       pre_loans_credit_limit_max  0.506361
87                  enc_paym_12_max  0.505236
49                 pclose_flag_mean  0.504373
23  pre_loans_credit_cost_rate_mean  0.504003
48    enc_loans_account_cur_nunique  0.503909
30                  pre_loans90_max  0.503291
41            pre_maxover2limit_max  0.503136
28                pre_loans3060_max  0.503053
39                     pre_util_max  0.502869
40               pre_over2limit_max  0.501712
27                 pre_loans530_max  0.500514
89                  enc_paym_12_sum  0.500431
25                   pre_loans5_max  0.500076
29                pre_loans6090_max  0.500004
TOP 20 important features
                            feature  importance
33            is_zero_loans530_mean    8.726012
38                    pre_util_mean    4.667232
42                is_zero_util_mean    4.486531
21       pre_loans_outstanding_mean    3.621439
35           is_zero_loans3060_mean    3.348244
88                 enc_paym_12_mean    3.055407
20        pre_loans_outstanding_max    3.007120
31              is_zero_loans5_mean    2.656258
39                     pre_util_max    2.583029
16       pre_loans_credit_limit_max    2.527706
0              pre_since_opened_min    2.096067
1              pre_since_opened_max    2.022608
47    enc_loans_credit_type_nunique    2.010776
37             is_zero_loans90_mean    1.787417
23  pre_loans_credit_cost_rate_mean    1.747551
14              pre_till_fclose_min    1.707836
19      pre_loans_next_pay_summ_max    1.668473
12              pre_till_pclose_min    1.665322
64                  enc_paym_4_mean    1.572847
58                  enc_paym_2_mean    1.560413

BOTTOM 20 least important features
                  feature  importance
80         enc_paym_9_sum    0.230689
71         enc_paym_6_sum    0.222165
27       pre_loans530_max    0.213824
41  pre_maxover2limit_max    0.211643
68         enc_paym_5_sum    0.210534
77         enc_paym_8_sum    0.181349
66         enc_paym_5_max    0.170434
28      pre_loans3060_max    0.158494
74         enc_paym_7_sum    0.142153
63         enc_paym_4_max    0.138201
72         enc_paym_7_max    0.079755
75         enc_paym_8_max    0.078275
30        pre_loans90_max    0.065878
87        enc_paym_12_max    0.050563
81        enc_paym_10_max    0.045156
78         enc_paym_9_max    0.025711
69         enc_paym_6_max    0.021878
25         pre_loans5_max    0.008566
29      pre_loans6090_max    0.000048
84        enc_paym_11_max    0.000000

In [65]:
merged = feature_auc_df.merge(importance_df, on='feature')

merged = merged.sort_values('auc', ascending=False)

merged.head(30)

                   feature       auc  importance
0          enc_paym_2_mean  0.603499    1.560413
1          enc_paym_3_mean  0.603493    1.125562
2          enc_paym_1_mean  0.601376    1.492875
3          enc_paym_4_mean  0.601348    1.572847
4          enc_paym_5_mean  0.598223    0.441910
5          enc_paym_6_mean  0.595144    0.827449
6          enc_paym_7_mean  0.594203    0.380810
7          enc_paym_8_mean  0.593086    0.843822
8          enc_paym_9_mean  0.592134    1.077759
9         enc_paym_10_mean  0.589458    1.158957
10        enc_paym_11_mean  0.589006    0.989810
11        enc_paym_12_mean  0.588614    3.055407
12          enc_paym_1_sum  0.573029    0.632769
13         enc_paym_0_mean  0.572847    1.554032
14   is_zero_loans530_mean  0.572250    8.726012
15       is_zero_util_mean  0.566991    4.486531
16          enc_paym_2_sum  0.565678    0.789340
17          enc_paym_0_sum  0.563008    0.798953
18  is_zero_loans3060_mean  0.561879    3.348244
19    is_zero_loans530_sum  0.560961    0.711930
20           pre_util_mean  0.558657    4.667232
21          enc_paym_3_sum  0.556224    0.432318
22          enc_paym_0_max  0.555597    1.520797
23          enc_paym_1_max  0.554579    0.579639
24  is_zero_loans6090_mean  0.549797    1.298293
25    pre_since_opened_min  0.547959    2.096067
26    is_zero_loans90_mean  0.547714    1.787417
27          enc_paym_4_sum  0.545914    0.404123
28      is_zero_loans5_sum  0.543199    0.409557
29          enc_paym_2_max  0.543005    0.259485

## modeling 15.03

In [14]:
X = data.drop(['flag', 'id'], axis=1)
y = data["flag"]

In [15]:
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y),
    y=y
)
class_weights_dict = {0: class_weights[0], 1: class_weights[1]}
print("Class weights:", class_weights_dict)

# stratify=y для сохранения распределения классов
X_train, X_val, y_train, y_val = train_test_split(
    X, y, 
    train_size=0.7, 
    stratify=y, 
    random_state=42
)

Class weights: {0: np.float64(0.5183929266321947), 1: np.float64(14.092181657616354)}

In [16]:
X_train, X_val, y_train, y_val = train_test_split(
    X, y, 
    train_size=0.7, 
    stratify=y, 
    random_state=42
)

## grid

In [17]:
grid = {
    'depth': [4, 6, 8],
    'learning_rate': [0.01, 0.03, 0.05],
    'l2_leaf_reg': [3, 5, 7],
}

best_auc = 0
best_params = None

for depth, lr, l2 in product(grid['depth'], grid['learning_rate'], grid['l2_leaf_reg']):
    print(f"Testing: depth={depth}, lr={lr}, l2_leaf_reg={l2}")
    model = CatBoostClassifier(
        iterations=500,
        depth=depth,
        learning_rate=lr,
        l2_leaf_reg=l2,
        loss_function='Logloss',
        eval_metric='AUC',
        early_stopping_rounds=50,
        verbose=100
    )
    model.fit(X_train, y_train, eval_set=(X_val, y_val))
    
    auc = model.get_best_score()['validation']['AUC']
    print(f"AUC: {auc}\n")
    
    if auc > best_auc:
        best_auc = auc
        best_params = {'depth': depth, 'learning_rate': lr, 'l2_leaf_reg': l2}

print(f"Best AUC: {best_auc} with params {best_params}")

Testing: depth=4, lr=0.01, l2_leaf_reg=3
0:	test: 0.5916312	best: 0.5916312 (0)	total: 414ms	remaining: 3m 26s
100:	test: 0.6805910	best: 0.6805910 (100)	total: 26.4s	remaining: 1m 44s
200:	test: 0.6926423	best: 0.6926423 (200)	total: 53s	remaining: 1m 18s
300:	test: 0.6983356	best: 0.6983391 (299)	total: 1m 19s	remaining: 52.4s
400:	test: 0.7016755	best: 0.7016755 (400)	total: 1m 46s	remaining: 26.2s
499:	test: 0.7040320	best: 0.7040320 (499)	total: 2m 12s	remaining: 0us

bestTest = 0.7040320433
bestIteration = 499

AUC: 0.7040320432822642

Testing: depth=4, lr=0.01, l2_leaf_reg=5
0:	test: 0.5916317	best: 0.5916317 (0)	total: 281ms	remaining: 2m 20s
100:	test: 0.6779538	best: 0.6779538 (100)	total: 26.9s	remaining: 1m 46s
200:	test: 0.6925506	best: 0.6925506 (200)	total: 53.3s	remaining: 1m 19s
300:	test: 0.6979414	best: 0.6979659 (299)	total: 1m 22s	remaining: 54.7s
400:	test: 0.7016435	best: 0.7016435 (400)	total: 1m 49s	remaining: 27.1s
499:	test: 0.7042271	best: 0.7042271 (499)	total: 2m 16s	remaining: 0us

bestTest = 0.7042270714
bestIteration = 499

AUC: 0.7042270714466154

Testing: depth=4, lr=0.01, l2_leaf_reg=7
0:	test: 0.5916317	best: 0.5916317 (0)	total: 297ms	remaining: 2m 28s
100:	test: 0.6793602	best: 0.6793602 (100)	total: 27.5s	remaining: 1m 48s
200:	test: 0.6924683	best: 0.6924683 (200)	total: 56.1s	remaining: 1m 23s
300:	test: 0.6984687	best: 0.6984687 (300)	total: 1m 23s	remaining: 55.2s
400:	test: 0.7016867	best: 0.7016867 (400)	total: 1m 51s	remaining: 27.6s
499:	test: 0.7040832	best: 0.7040832 (499)	total: 2m 18s	remaining: 0us

bestTest = 0.7040831867
bestIteration = 499

AUC: 0.7040831866929171

Testing: depth=4, lr=0.03, l2_leaf_reg=3
0:	test: 0.5916312	best: 0.5916312 (0)	total: 283ms	remaining: 2m 21s
100:	test: 0.6984572	best: 0.6984572 (100)	total: 27.2s	remaining: 1m 47s
200:	test: 0.7058761	best: 0.7058761 (200)	total: 54.8s	remaining: 1m 21s
300:	test: 0.7101580	best: 0.7101580 (300)	total: 1m 26s	remaining: 57.3s
400:	test: 0.7133610	best: 0.7133610 (400)	total: 1m 56s	remaining: 28.7s
499:	test: 0.7157030	best: 0.7157030 (499)	total: 2m 23s	remaining: 0us

bestTest = 0.715702992
bestIteration = 499

AUC: 0.7157029919814804

Testing: depth=4, lr=0.03, l2_leaf_reg=5
0:	test: 0.5916317	best: 0.5916317 (0)	total: 287ms	remaining: 2m 23s
100:	test: 0.6982800	best: 0.6982800 (100)	total: 28.5s	remaining: 1m 52s
200:	test: 0.7060911	best: 0.7060911 (200)	total: 58.1s	remaining: 1m 26s
300:	test: 0.7102616	best: 0.7102616 (300)	total: 1m 26s	remaining: 57.4s
400:	test: 0.7135430	best: 0.7135430 (400)	total: 1m 57s	remaining: 29s
499:	test: 0.7157509	best: 0.7157509 (499)	total: 2m 26s	remaining: 0us

bestTest = 0.7157508793
bestIteration = 499

AUC: 0.7157508792574404

Testing: depth=4, lr=0.03, l2_leaf_reg=7
0:	test: 0.5916317	best: 0.5916317 (0)	total: 300ms	remaining: 2m 29s
100:	test: 0.6979492	best: 0.6979492 (100)	total: 29s	remaining: 1m 54s
200:	test: 0.7059259	best: 0.7059259 (200)	total: 58.4s	remaining: 1m 26s
300:	test: 0.7100560	best: 0.7100560 (300)	total: 1m 28s	remaining: 58.3s
400:	test: 0.7131033	best: 0.7131033 (400)	total: 1m 55s	remaining: 28.6s
499:	test: 0.7155419	best: 0.7155419 (499)	total: 2m 22s	remaining: 0us

bestTest = 0.7155419258
bestIteration = 499

AUC: 0.7155419258322805

Testing: depth=4, lr=0.05, l2_leaf_reg=3
0:	test: 0.5916312	best: 0.5916312 (0)	total: 275ms	remaining: 2m 17s
100:	test: 0.7040413	best: 0.7040413 (100)	total: 29.3s	remaining: 1m 55s
200:	test: 0.7114895	best: 0.7114895 (200)	total: 57.7s	remaining: 1m 25s
300:	test: 0.7158960	best: 0.7158960 (300)	total: 1m 28s	remaining: 58.7s
400:	test: 0.7189815	best: 0.7189815 (400)	total: 1m 56s	remaining: 28.7s
499:	test: 0.7210439	best: 0.7210439 (499)	total: 2m 23s	remaining: 0us

bestTest = 0.7210439154
bestIteration = 499

AUC: 0.7210439153605022

Testing: depth=4, lr=0.05, l2_leaf_reg=5
0:	test: 0.5916317	best: 0.5916317 (0)	total: 285ms	remaining: 2m 22s
100:	test: 0.7039274	best: 0.7039274 (100)	total: 29.1s	remaining: 1m 54s
200:	test: 0.7112902	best: 0.7112902 (200)	total: 57.9s	remaining: 1m 26s
300:	test: 0.7157452	best: 0.7157452 (300)	total: 1m 27s	remaining: 57.6s
400:	test: 0.7187006	best: 0.7187006 (400)	total: 1m 54s	remaining: 28.3s
499:	test: 0.7207573	best: 0.7207573 (499)	total: 2m 24s	remaining: 0us

bestTest = 0.7207572834
bestIteration = 499

AUC: 0.7207572834439699

Testing: depth=4, lr=0.05, l2_leaf_reg=7
0:	test: 0.5916317	best: 0.5916317 (0)	total: 293ms	remaining: 2m 26s
100:	test: 0.7037241	best: 0.7037241 (100)	total: 28.6s	remaining: 1m 52s
200:	test: 0.7115069	best: 0.7115069 (200)	total: 59.7s	remaining: 1m 28s
300:	test: 0.7157294	best: 0.7157294 (300)	total: 1m 27s	remaining: 57.8s
400:	test: 0.7188092	best: 0.7188092 (400)	total: 1m 53s	remaining: 28.1s
499:	test: 0.7207529	best: 0.7207529 (499)	total: 2m 20s	remaining: 0us

bestTest = 0.7207528904
bestIteration = 499

AUC: 0.7207528903858011

Testing: depth=6, lr=0.01, l2_leaf_reg=3
0:	test: 0.6101524	best: 0.6101524 (0)	total: 380ms	remaining: 3m 9s
100:	test: 0.6794993	best: 0.6794993 (100)	total: 32.8s	remaining: 2m 9s
200:	test: 0.6963984	best: 0.6963984 (200)	total: 1m 6s	remaining: 1m 38s
300:	test: 0.7031561	best: 0.7031561 (300)	total: 1m 42s	remaining: 1m 7s
400:	test: 0.7065839	best: 0.7065839 (400)	total: 2m 18s	remaining: 34.2s
499:	test: 0.7089868	best: 0.7089868 (499)	total: 2m 53s	remaining: 0us

bestTest = 0.7089867585
bestIteration = 499

AUC: 0.708986758513083

Testing: depth=6, lr=0.01, l2_leaf_reg=5
0:	test: 0.6101878	best: 0.6101878 (0)	total: 355ms	remaining: 2m 57s
100:	test: 0.6805348	best: 0.6805348 (100)	total: 33.1s	remaining: 2m 10s
200:	test: 0.6970371	best: 0.6970371 (200)	total: 1m 6s	remaining: 1m 38s
300:	test: 0.7031547	best: 0.7031547 (300)	total: 1m 40s	remaining: 1m 6s
400:	test: 0.7065979	best: 0.7065979 (400)	total: 2m 17s	remaining: 34s
499:	test: 0.7091077	best: 0.7091077 (499)	total: 2m 56s	remaining: 0us

bestTest = 0.7091077119
bestIteration = 499

AUC: 0.7091077119400094

Testing: depth=6, lr=0.01, l2_leaf_reg=7
0:	test: 0.6102007	best: 0.6102007 (0)	total: 391ms	remaining: 3m 15s
100:	test: 0.6797751	best: 0.6797751 (100)	total: 35.9s	remaining: 2m 21s
200:	test: 0.6969769	best: 0.6969769 (200)	total: 1m 12s	remaining: 1m 48s
300:	test: 0.7031728	best: 0.7031728 (300)	total: 1m 50s	remaining: 1m 13s
400:	test: 0.7066955	best: 0.7066955 (400)	total: 2m 30s	remaining: 37s
499:	test: 0.7091951	best: 0.7091951 (499)	total: 3m 9s	remaining: 0us

bestTest = 0.7091950869
bestIteration = 499

AUC: 0.7091950868837587

Testing: depth=6, lr=0.03, l2_leaf_reg=3
0:	test: 0.6101524	best: 0.6101524 (0)	total: 355ms	remaining: 2m 57s
100:	test: 0.7025626	best: 0.7025626 (100)	total: 35.6s	remaining: 2m 20s
200:	test: 0.7106542	best: 0.7106542 (200)	total: 1m 10s	remaining: 1m 44s
300:	test: 0.7154525	best: 0.7154525 (300)	total: 1m 44s	remaining: 1m 9s
400:	test: 0.7186004	best: 0.7186004 (400)	total: 2m 18s	remaining: 34.3s
499:	test: 0.7207481	best: 0.7207481 (499)	total: 2m 53s	remaining: 0us

bestTest = 0.7207480987
bestIteration = 499

AUC: 0.7207480987162842

Testing: depth=6, lr=0.03, l2_leaf_reg=5
0:	test: 0.6101878	best: 0.6101878 (0)	total: 354ms	remaining: 2m 56s
100:	test: 0.7024074	best: 0.7024074 (100)	total: 33.7s	remaining: 2m 13s
200:	test: 0.7110462	best: 0.7110462 (200)	total: 1m 11s	remaining: 1m 46s
300:	test: 0.7154641	best: 0.7154641 (300)	total: 1m 46s	remaining: 1m 10s
400:	test: 0.7185868	best: 0.7185868 (400)	total: 2m 22s	remaining: 35.1s
499:	test: 0.7207987	best: 0.7207987 (499)	total: 2m 56s	remaining: 0us

bestTest = 0.7207986544
bestIteration = 499

AUC: 0.720798654428175

Testing: depth=6, lr=0.03, l2_leaf_reg=7
0:	test: 0.6102007	best: 0.6102007 (0)	total: 389ms	remaining: 3m 14s
100:	test: 0.7028872	best: 0.7028872 (100)	total: 39.4s	remaining: 2m 35s
200:	test: 0.7106099	best: 0.7106099 (200)	total: 1m 23s	remaining: 2m 4s
300:	test: 0.7157056	best: 0.7157056 (300)	total: 2m 4s	remaining: 1m 21s
400:	test: 0.7187502	best: 0.7187502 (400)	total: 2m 38s	remaining: 39.2s
499:	test: 0.7208786	best: 0.7208786 (499)	total: 3m 13s	remaining: 0us

bestTest = 0.7208786401
bestIteration = 499

AUC: 0.7208786401178895

Testing: depth=6, lr=0.05, l2_leaf_reg=3
0:	test: 0.6101524	best: 0.6101524 (0)	total: 359ms	remaining: 2m 58s
100:	test: 0.7084672	best: 0.7084672 (100)	total: 35.1s	remaining: 2m 18s
200:	test: 0.7168263	best: 0.7168263 (200)	total: 1m 15s	remaining: 1m 52s
300:	test: 0.7208770	best: 0.7208770 (300)	total: 1m 58s	remaining: 1m 18s
400:	test: 0.7234133	best: 0.7234133 (400)	total: 2m 41s	remaining: 39.8s
499:	test: 0.7249642	best: 0.7249642 (499)	total: 3m 21s	remaining: 0us

bestTest = 0.7249641681
bestIteration = 499

AUC: 0.7249641680531806

Testing: depth=6, lr=0.05, l2_leaf_reg=5
0:	test: 0.6101878	best: 0.6101878 (0)	total: 467ms	remaining: 3m 53s
100:	test: 0.7089210	best: 0.7089210 (100)	total: 40.2s	remaining: 2m 38s
200:	test: 0.7167838	best: 0.7167838 (200)	total: 1m 18s	remaining: 1m 56s
300:	test: 0.7207825	best: 0.7207825 (300)	total: 1m 53s	remaining: 1m 15s
400:	test: 0.7234109	best: 0.7234109 (400)	total: 2m 30s	remaining: 37.1s
499:	test: 0.7249663	best: 0.7249667 (498)	total: 3m 13s	remaining: 0us

bestTest = 0.724966733
bestIteration = 498

Shrink model to first 499 iterations.
AUC: 0.7249667330258464

Testing: depth=6, lr=0.05, l2_leaf_reg=7
0:	test: 0.6102007	best: 0.6102007 (0)	total: 448ms	remaining: 3m 43s
100:	test: 0.7090102	best: 0.7090102 (100)	total: 43.8s	remaining: 2m 53s
200:	test: 0.7167632	best: 0.7167632 (200)	total: 1m 26s	remaining: 2m 8s
300:	test: 0.7207526	best: 0.7207526 (300)	total: 2m 8s	remaining: 1m 24s
400:	test: 0.7234751	best: 0.7234751 (400)	total: 2m 50s	remaining: 42s
499:	test: 0.7250847	best: 0.7250847 (499)	total: 3m 31s	remaining: 0us

bestTest = 0.7250846535
bestIteration = 499

AUC: 0.7250846534603481

Testing: depth=8, lr=0.01, l2_leaf_reg=3
0:	test: 0.6290333	best: 0.6290333 (0)	total: 533ms	remaining: 4m 26s
100:	test: 0.6800542	best: 0.6800542 (100)	total: 47.7s	remaining: 3m 8s
200:	test: 0.6976455	best: 0.6976455 (200)	total: 1m 37s	remaining: 2m 25s
300:	test: 0.7062057	best: 0.7062057 (300)	total: 2m 29s	remaining: 1m 38s
400:	test: 0.7101047	best: 0.7101047 (400)	total: 3m 23s	remaining: 50.1s
499:	test: 0.7128997	best: 0.7128997 (499)	total: 4m 17s	remaining: 0us

bestTest = 0.7128996949
bestIteration = 499

AUC: 0.7128996949496057

Testing: depth=8, lr=0.01, l2_leaf_reg=5
0:	test: 0.6290381	best: 0.6290381 (0)	total: 568ms	remaining: 4m 43s
100:	test: 0.6800613	best: 0.6800613 (100)	total: 50.9s	remaining: 3m 21s
200:	test: 0.6977038	best: 0.6977038 (200)	total: 1m 37s	remaining: 2m 24s
300:	test: 0.7062847	best: 0.7062847 (300)	total: 2m 19s	remaining: 1m 31s
400:	test: 0.7100007	best: 0.7100007 (400)	total: 3m 1s	remaining: 44.9s
499:	test: 0.7127271	best: 0.7127271 (499)	total: 3m 44s	remaining: 0us

bestTest = 0.7127271011
bestIteration = 499

AUC: 0.7127271011059585

Testing: depth=8, lr=0.01, l2_leaf_reg=7
0:	test: 0.6290492	best: 0.6290492 (0)	total: 421ms	remaining: 3m 30s
100:	test: 0.6800658	best: 0.6800658 (100)	total: 38.6s	remaining: 2m 32s
200:	test: 0.6977414	best: 0.6977414 (200)	total: 1m 18s	remaining: 1m 57s
300:	test: 0.7063377	best: 0.7063377 (300)	total: 2m	remaining: 1m 19s
400:	test: 0.7100561	best: 0.7100561 (400)	total: 2m 42s	remaining: 40.2s
499:	test: 0.7127654	best: 0.7127654 (499)	total: 3m 25s	remaining: 0us

bestTest = 0.7127653842
bestIteration = 499

AUC: 0.7127653842095389

Testing: depth=8, lr=0.03, l2_leaf_reg=3
0:	test: 0.6290333	best: 0.6290333 (0)	total: 432ms	remaining: 3m 35s
100:	test: 0.7066861	best: 0.7066861 (100)	total: 40.8s	remaining: 2m 41s
200:	test: 0.7151809	best: 0.7151809 (200)	total: 1m 24s	remaining: 2m 6s
300:	test: 0.7197438	best: 0.7197438 (300)	total: 2m 7s	remaining: 1m 24s
400:	test: 0.7224977	best: 0.7224977 (400)	total: 2m 49s	remaining: 41.8s
499:	test: 0.7241762	best: 0.7241762 (499)	total: 3m 35s	remaining: 0us

bestTest = 0.7241761751
bestIteration = 499

AUC: 0.7241761750880573

Testing: depth=8, lr=0.03, l2_leaf_reg=5
0:	test: 0.6290381	best: 0.6290381 (0)	total: 575ms	remaining: 4m 46s
100:	test: 0.7065551	best: 0.7065551 (100)	total: 51s	remaining: 3m 21s
200:	test: 0.7153495	best: 0.7153495 (200)	total: 1m 45s	remaining: 2m 36s
300:	test: 0.7197507	best: 0.7197507 (300)	total: 2m 37s	remaining: 1m 44s
400:	test: 0.7225126	best: 0.7225126 (400)	total: 3m 28s	remaining: 51.5s
499:	test: 0.7242530	best: 0.7242530 (499)	total: 4m 18s	remaining: 0us

bestTest = 0.7242530483
bestIteration = 499

AUC: 0.7242530482759204

Testing: depth=8, lr=0.03, l2_leaf_reg=7
0:	test: 0.6290492	best: 0.6290492 (0)	total: 507ms	remaining: 4m 12s
100:	test: 0.7066252	best: 0.7066252 (100)	total: 51.1s	remaining: 3m 21s
200:	test: 0.7153210	best: 0.7153210 (200)	total: 1m 42s	remaining: 2m 32s
300:	test: 0.7197198	best: 0.7197198 (300)	total: 2m 24s	remaining: 1m 35s
400:	test: 0.7226999	best: 0.7226999 (400)	total: 3m 5s	remaining: 45.7s
499:	test: 0.7245450	best: 0.7245450 (499)	total: 3m 44s	remaining: 0us

bestTest = 0.7245449663
bestIteration = 499

AUC: 0.7245449662525956

Testing: depth=8, lr=0.05, l2_leaf_reg=3
0:	test: 0.6290333	best: 0.6290333 (0)	total: 414ms	remaining: 3m 26s
100:	test: 0.7132337	best: 0.7132337 (100)	total: 41.1s	remaining: 2m 42s
200:	test: 0.7207539	best: 0.7207539 (200)	total: 1m 21s	remaining: 2m 1s
300:	test: 0.7242466	best: 0.7242466 (300)	total: 2m 1s	remaining: 1m 20s
400:	test: 0.7263192	best: 0.7263192 (400)	total: 2m 40s	remaining: 39.7s
499:	test: 0.7274884	best: 0.7274884 (499)	total: 3m 20s	remaining: 0us

bestTest = 0.7274883711
bestIteration = 499

AUC: 0.7274883710878698

Testing: depth=8, lr=0.05, l2_leaf_reg=5
0:	test: 0.6290381	best: 0.6290381 (0)	total: 421ms	remaining: 3m 29s
100:	test: 0.7129121	best: 0.7129121 (100)	total: 40.7s	remaining: 2m 40s
200:	test: 0.7207947	best: 0.7207947 (200)	total: 1m 21s	remaining: 2m 1s
300:	test: 0.7242610	best: 0.7242610 (300)	total: 2m 1s	remaining: 1m 20s
400:	test: 0.7263519	best: 0.7263531 (399)	total: 2m 41s	remaining: 39.9s
499:	test: 0.7274506	best: 0.7274506 (499)	total: 3m 19s	remaining: 0us

bestTest = 0.7274506344
bestIteration = 499

AUC: 0.7274506343590732

Testing: depth=8, lr=0.05, l2_leaf_reg=7
0:	test: 0.6290492	best: 0.6290492 (0)	total: 426ms	remaining: 3m 32s
100:	test: 0.7128089	best: 0.7128089 (100)	total: 40.8s	remaining: 2m 41s
200:	test: 0.7208004	best: 0.7208004 (200)	total: 1m 22s	remaining: 2m 2s
300:	test: 0.7241041	best: 0.7241041 (300)	total: 2m 2s	remaining: 1m 20s
400:	test: 0.7262324	best: 0.7262324 (400)	total: 2m 41s	remaining: 39.9s
499:	test: 0.7276017	best: 0.7276017 (499)	total: 3m 20s	remaining: 0us

bestTest = 0.7276016922
bestIteration = 499

AUC: 0.7276016922411365

Best AUC: 0.7276016922411365 with params {'depth': 8, 'learning_rate': 0.05, 'l2_leaf_reg': 7}

## model

In [18]:
model = CatBoostClassifier(
    iterations=1000,
    depth=6,
    learning_rate=0.03,
    loss_function="Logloss",
    eval_metric="AUC",
    verbose=100
)

model.fit(X_train, y_train,
          eval_set=(X_val, y_val))

0:	test: 0.6101524	best: 0.6101524 (0)	total: 365ms	remaining: 6m 4s
100:	test: 0.7025626	best: 0.7025626 (100)	total: 33.4s	remaining: 4m 57s
200:	test: 0.7106542	best: 0.7106542 (200)	total: 1m 8s	remaining: 4m 30s
300:	test: 0.7154525	best: 0.7154525 (300)	total: 1m 42s	remaining: 3m 58s
400:	test: 0.7186004	best: 0.7186004 (400)	total: 2m 17s	remaining: 3m 24s
500:	test: 0.7207682	best: 0.7207682 (500)	total: 2m 51s	remaining: 2m 50s
600:	test: 0.7225753	best: 0.7225753 (600)	total: 3m 25s	remaining: 2m 16s
700:	test: 0.7239624	best: 0.7239624 (700)	total: 4m 6s	remaining: 1m 44s
800:	test: 0.7249017	best: 0.7249017 (800)	total: 4m 45s	remaining: 1m 10s
900:	test: 0.7257138	best: 0.7257138 (900)	total: 5m 22s	remaining: 35.5s
999:	test: 0.7263815	best: 0.7263815 (999)	total: 5m 58s	remaining: 0us

bestTest = 0.7263814622
bestIteration = 999

## modeling 17.03 - 18.03

In [9]:
data = pd.read_csv('full_data3')

In [29]:
X = data.drop(['flag', 'id'], axis=1)
y = data["flag"]

In [30]:
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y),
    y=y
)
class_weights_dict = {0: class_weights[0], 1: class_weights[1]}
print("Class weights:", class_weights_dict)

# stratify=y для сохранения распределения классов
X_train, X_val, y_train, y_val = train_test_split(
    X, y, 
    train_size=0.7, 
    stratify=y, 
    random_state=42
)

Class weights: {0: np.float64(0.5183929266321947), 1: np.float64(14.092181657616354)}

In [13]:
model = CatBoostClassifier(
    iterations=1000,
    depth=8,
    learning_rate=0.05,
    l2_leaf_reg=7,
    loss_function='Logloss',
    eval_metric='AUC',
    class_weights=class_weights_dict,
    early_stopping_rounds=50,
    verbose=100
)

model.fit(X_train, y_train,
          eval_set=(X_val, y_val))

0:	test: 0.6776694	best: 0.6776694 (0)	total: 778ms	remaining: 12m 57s
100:	test: 0.7203855	best: 0.7203855 (100)	total: 56.5s	remaining: 8m 23s
200:	test: 0.7268205	best: 0.7268205 (200)	total: 1m 54s	remaining: 7m 34s
300:	test: 0.7300951	best: 0.7300951 (300)	total: 2m 48s	remaining: 6m 32s
400:	test: 0.7326421	best: 0.7326421 (400)	total: 3m 45s	remaining: 5m 36s
500:	test: 0.7338162	best: 0.7338162 (500)	total: 4m 37s	remaining: 4m 36s
600:	test: 0.7345289	best: 0.7345607 (588)	total: 5m 32s	remaining: 3m 41s
700:	test: 0.7349805	best: 0.7349805 (700)	total: 6m 25s	remaining: 2m 44s
800:	test: 0.7351763	best: 0.7351845 (797)	total: 7m 24s	remaining: 1m 50s
900:	test: 0.7353139	best: 0.7353208 (892)	total: 8m 21s	remaining: 55.1s
999:	test: 0.7355614	best: 0.7355614 (999)	total: 9m 20s	remaining: 0us

bestTest = 0.7355614356
bestIteration = 999

In [19]:
importances = model.get_feature_importance()

importance_df = pd.DataFrame({
    'feature': X_train.columns,
    'importance': importances
}).sort_values('importance', ascending=False)

print("TOP 20 important features")
print(importance_df.head(20))

print("\nBOTTOM 20 least important features")
print(importance_df.tail(20))

TOP 20 important features
                             feature  importance
33             is_zero_loans530_mean    5.019822
21        pre_loans_outstanding_mean    3.781118
42                 is_zero_util_mean    3.752217
38                     pre_util_mean    3.572975
23   pre_loans_credit_cost_rate_mean    2.929762
123              paym_bad_count_mean    2.451683
39                      pre_util_max    2.356761
20         pre_loans_outstanding_max    2.249648
18      pre_loans_next_pay_summ_mean    2.081666
35            is_zero_loans3060_mean    2.037159
131        max_utilization_ratio_max    1.976335
16        pre_loans_credit_limit_max    1.964091
49                  pclose_flag_mean    1.963495
31               is_zero_loans5_mean    1.956893
47     enc_loans_credit_type_nunique    1.882100
19       pre_loans_next_pay_summ_max    1.695958
125          paym_nonzero_share_mean    1.686871
8                     pre_pterm_mean    1.682488
17       pre_loans_credit_limit_mean    1.579617
2              pre_since_opened_mean    1.500744

BOTTOM 20 least important features
               feature  importance
111    enc_paym_20_max    0.028648
25      pre_loans5_max    0.027386
117    enc_paym_22_max    0.024139
105    enc_paym_18_max    0.022018
30     pre_loans90_max    0.019181
90     enc_paym_13_max    0.017656
72      enc_paym_7_max    0.017060
114    enc_paym_21_max    0.015753
78      enc_paym_9_max    0.012378
81     enc_paym_10_max    0.008704
120    enc_paym_23_max    0.005304
96     enc_paym_15_max    0.001548
29   pre_loans6090_max    0.000000
99     enc_paym_16_max    0.000000
87     enc_paym_12_max    0.000000
84     enc_paym_11_max    0.000000
75      enc_paym_8_max    0.000000
93     enc_paym_14_max    0.000000
102    enc_paym_17_max    0.000000
108    enc_paym_19_max    0.000000

## modeling 19.03

In [81]:
X = data.drop(['flag', 'id'], axis=1)
y = data["flag"]

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y),
    y=y
)

class_weights_dict = {0: class_weights[0], 1: class_weights[1]}

skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

oof_preds = np.zeros(len(X))
fold_scores = []

for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):
    print(f"\n===== FOLD {fold} =====")

    X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
    y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

    model = CatBoostClassifier(
        iterations=1000,
        depth=8,
        learning_rate=0.05,
        l2_leaf_reg=7,
        loss_function='Logloss',
        eval_metric='AUC',
        class_weights=class_weights_dict,
        early_stopping_rounds=100,
        verbose=200
    )

    model.fit(
        X_train, y_train,
        eval_set=(X_val, y_val),
        use_best_model=True
    )

    preds = model.predict_proba(X_val)[:, 1]
    oof_preds[val_idx] = preds

    fold_auc = roc_auc_score(y_val, preds)
    fold_scores.append(fold_auc)

    print(f"FOLD {fold} AUC: {fold_auc:.6f}")

overall_auc = roc_auc_score(y, oof_preds)

===== FOLD 0 =====
0:	test: 0.6783225	best: 0.6783225 (0)	total: 624ms	remaining: 10m 23s

KeyboardInterrupt:

## feature importance

In [63]:
fi = model.get_feature_importance(prettified=True)

# переименуем для удобства
fi.columns = ['feature', 'importance']

# сортировка по убыванию
fi_sorted = fi.sort_values(by='importance', ascending=False)

# 20 лучших
top_20 = fi_sorted.head(20)
print("=== Top 20 features ===")
print(top_20)

# 20 худших
bottom_20 = fi_sorted.tail(20)
print("\n=== Bottom 20 features ===")
print(bottom_20)

# отдельно проверим новые фичи
new_features = ["util_per_loan", "bad_payment_ratio", "util_stability"]
print("\n=== New features importance ===")
for f in new_features:
    if f in fi_sorted['feature'].values:
        imp = fi_sorted.loc[fi_sorted['feature'] == f, 'importance'].values[0]
        print(f"{f}: {imp:.6f}")
    else:
        print(f"{f}: not found")

=== Top 20 features ===
                               feature  importance
0                is_zero_loans530_mean    4.866229
1           pre_loans_outstanding_mean    3.685992
2                    is_zero_util_mean    3.022558
3      pre_loans_credit_cost_rate_mean    2.904668
4            max_utilization_ratio_max    2.373087
5            pre_loans_outstanding_max    2.303073
6                        util_per_loan    2.257056
7                         pre_util_max    2.232053
8         pre_loans_next_pay_summ_mean    2.073881
9   client_mean_bad_months_per_product    1.996439
10              is_zero_loans3060_mean    1.982344
11                 is_zero_loans5_mean    1.977211
12      client_mean_nonzero_paym_share    1.949083
13          pre_loans_credit_limit_max    1.874081
14                      util_stability    1.840551
15                       pre_util_mean    1.823789
16         pre_loans_credit_limit_mean    1.778194
17                    pclose_flag_mean    1.745844
18                 pre_till_fclose_min    1.642720
19         pre_loans_next_pay_summ_max    1.617804

=== Bottom 20 features ===
                       feature  importance
96              pre_loans5_sum    0.216252
97              enc_paym_4_sum    0.206545
98             enc_paym_15_sum    0.191424
99              enc_paym_9_sum    0.188533
100  client_products_count_max    0.186422
101             enc_paym_6_sum    0.186013
102             enc_paym_5_sum    0.179309
103             enc_paym_8_sum    0.178468
104            enc_paym_17_sum    0.175715
105             enc_paym_1_max    0.164871
106             enc_paym_7_sum    0.153330
107            enc_paym_12_sum    0.116746
108          pre_loans3060_max    0.092950
109             enc_paym_2_max    0.067111
110      pre_maxover2limit_max    0.064318
111             enc_paym_5_max    0.028944
112             enc_paym_3_max    0.028686
113             enc_paym_4_max    0.011670
114             enc_paym_6_max    0.007547
115          bad_payment_ratio    0.000000

=== New features importance ===
util_per_loan: 2.257056
bad_payment_ratio: 0.000000
util_stability: 1.840551

## ансамбль с lightgbm и xgboost (переобучение)

In [28]:
median_val = data["bad_payment_ratio"].median()
data["bad_payment_ratio"] = data["bad_payment_ratio"].replace([np.inf, -np.inf], median_val)

In [32]:
for col in X.columns:
    if X[col].dtype.kind in 'f':  # только float колонки
        median_val = X[col].replace([np.inf, -np.inf], np.nan).median()
        X[col] = X[col].replace([np.inf, -np.inf], median_val)

In [33]:
cat_model = CatBoostClassifier(
    iterations=1000,
    depth=8,
    learning_rate=0.05,
    l2_leaf_reg=7,
    loss_function='Logloss',
    eval_metric='AUC',
    class_weights=class_weights_dict,
    early_stopping_rounds=100,
    verbose=200
)
cat_model.fit(X, y, use_best_model=True)
cat_preds = cat_model.predict_proba(X)[:, 1]

lgb_model = lgb.LGBMClassifier(
    n_estimators=1000,
    learning_rate=0.05,
    max_depth=-1,
    random_state=42
)
lgb_model.fit(X, y)
lgb_preds = lgb_model.predict_proba(X)[:, 1]

xgb_model = xgb.XGBClassifier(
    n_estimators=1000,
    learning_rate=0.05,
    max_depth=6,
    use_label_encoder=False,
    eval_metric='auc',
    random_state=42
)
xgb_model.fit(X, y)
xgb_preds = xgb_model.predict_proba(X)[:, 1]

You should provide test set for use best model. use_best_model parameter has been switched to false value.

0:	total: 689ms	remaining: 11m 28s
200:	total: 2m 49s	remaining: 11m 14s
400:	total: 5m 22s	remaining: 8m 2s
600:	total: 7m 38s	remaining: 5m 4s
800:	total: 9m 55s	remaining: 2m 27s
999:	total: 12m 37s	remaining: 0us
[LightGBM] [Info] Number of positive: 106442, number of negative: 2893558
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.288632 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14820
[LightGBM] [Info] Number of data points in the train set: 3000000, number of used features: 115
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.035481 -> initscore=-3.302642
[LightGBM] [Info] Start training from score -3.302642

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [18:09:44] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

In [34]:
ensemble_preds = (cat_preds + lgb_preds + xgb_preds) / 3

# AUC для каждой модели и ансамбля
print("CatBoost AUC:", roc_auc_score(y, cat_preds))
print("LightGBM AUC:", roc_auc_score(y, lgb_preds))
print("XGBoost AUC:", roc_auc_score(y, xgb_preds))
print("Ensemble AUC:", roc_auc_score(y, ensemble_preds))

CatBoost AUC: 0.7773442764733353
LightGBM AUC: 0.7796894363536342
XGBoost AUC: 0.7833135827541727
Ensemble AUC: 0.7823242004945576

## ансамбль с K-fold

In [35]:
cat_params = {
    'iterations': 1000,
    'depth': 8,
    'learning_rate': 0.05,
    'l2_leaf_reg': 7,
    'loss_function': 'Logloss',
    'eval_metric': 'AUC',
    'class_weights': class_weights_dict,
    'early_stopping_rounds': 100,
    'verbose': 200
}

lgb_params = {
    'n_estimators': 1000,
    'learning_rate': 0.05,
    'max_depth': -1,
    'random_state': 42
}

xgb_params = {
    'n_estimators': 1000,
    'learning_rate': 0.05,
    'max_depth': 6,
    'use_label_encoder': False,
    'eval_metric': 'auc',
    'random_state': 42
}

In [36]:
skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

oof_cat = np.zeros(len(X))
oof_lgb = np.zeros(len(X))
oof_xgb = np.zeros(len(X))

for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):
    print(f"\n===== FOLD {fold} =====")
    X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
    y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

    # CatBoost
    cat_model = CatBoostClassifier(**cat_params)
    cat_model.fit(X_train, y_train, eval_set=(X_val, y_val), use_best_model=True)
    oof_cat[val_idx] = cat_model.predict_proba(X_val)[:, 1]

    # LightGBM
    lgb_model = lgb.LGBMClassifier(**lgb_params)
    lgb_model.fit(X_train, y_train)
    oof_lgb[val_idx] = lgb_model.predict_proba(X_val)[:, 1]

    # XGBoost
    xgb_model = xgb.XGBClassifier(**xgb_params)
    xgb_model.fit(X_train, y_train)
    oof_xgb[val_idx] = xgb_model.predict_proba(X_val)[:, 1]

===== FOLD 0 =====
0:	test: 0.6778513	best: 0.6778513 (0)	total: 509ms	remaining: 8m 28s
200:	test: 0.7249495	best: 0.7249495 (200)	total: 1m 41s	remaining: 6m 41s
400:	test: 0.7305285	best: 0.7305285 (400)	total: 3m 21s	remaining: 5m
600:	test: 0.7325758	best: 0.7325758 (600)	total: 5m 1s	remaining: 3m 19s
800:	test: 0.7332035	best: 0.7332198 (740)	total: 6m 40s	remaining: 1m 39s
999:	test: 0.7334622	best: 0.7335565 (955)	total: 8m 20s	remaining: 0us

bestTest = 0.7335564962
bestIteration = 955

Shrink model to first 956 iterations.
[LightGBM] [Info] Number of positive: 70962, number of negative: 1929038
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.784445 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14816
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 115
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.035481 -> initscore=-3.302632
[LightGBM] [Info] Start training from score -3.302632

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [23:49:47] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

===== FOLD 1 =====
0:	test: 0.6846925	best: 0.6846925 (0)	total: 521ms	remaining: 8m 40s
200:	test: 0.7302694	best: 0.7302694 (200)	total: 1m 41s	remaining: 6m 44s
400:	test: 0.7352928	best: 0.7352928 (400)	total: 3m 27s	remaining: 5m 10s
600:	test: 0.7371545	best: 0.7371545 (600)	total: 5m 10s	remaining: 3m 26s
800:	test: 0.7375080	best: 0.7375108 (799)	total: 6m 51s	remaining: 1m 42s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.7376187485
bestIteration = 828

Shrink model to first 829 iterations.
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.775680 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14821
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 115
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.035480 -> initscore=-3.302647
[LightGBM] [Info] Start training from score -3.302647

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [00:04:55] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

===== FOLD 2 =====
0:	test: 0.6774138	best: 0.6774138 (0)	total: 550ms	remaining: 9m 9s
200:	test: 0.7261050	best: 0.7261050 (200)	total: 1m 41s	remaining: 6m 43s
400:	test: 0.7321057	best: 0.7321057 (400)	total: 3m 23s	remaining: 5m 3s
600:	test: 0.7341327	best: 0.7341327 (600)	total: 5m 5s	remaining: 3m 22s
800:	test: 0.7348560	best: 0.7348560 (800)	total: 6m 46s	remaining: 1m 41s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.734912895
bestIteration = 870

Shrink model to first 871 iterations.
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.819345 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14857
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 115
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.035480 -> initscore=-3.302647
[LightGBM] [Info] Start training from score -3.302647

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [00:20:14] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

In [37]:
auc_cat = roc_auc_score(y, oof_cat)
auc_lgb = roc_auc_score(y, oof_lgb)
auc_xgb = roc_auc_score(y, oof_xgb)

# простой ансамбль - среднее предсказаний
ensemble_preds = (oof_cat + oof_lgb + oof_xgb) / 3
auc_ensemble = roc_auc_score(y, ensemble_preds)

print(f"\nCatBoost OOF AUC: {auc_cat:.6f}")
print(f"LightGBM OOF AUC: {auc_lgb:.6f}")
print(f"XGBoost OOF AUC: {auc_xgb:.6f}")
print(f"Ensemble OOF AUC: {auc_ensemble:.6f}")

CatBoost OOF AUC: 0.735336
LightGBM OOF AUC: 0.733697
XGBoost OOF AUC: 0.735600
Ensemble OOF AUC: 0.736681

In [40]:
rank_cat = rankdata(oof_cat)
rank_lgb = rankdata(oof_lgb)
rank_xgb = rankdata(oof_xgb)

ensemble_rank = (rank_cat + rank_lgb + rank_xgb) / 3

roc_auc_score(y, ensemble_rank)

0.7371091806315032

In [41]:
stack_X = np.vstack([
    oof_cat,
    oof_lgb,
    oof_xgb
]).T

meta_model = meta_model = CatBoostClassifier(
    iterations=300,
    depth=4,
    learning_rate=0.05,
    verbose=0
)
meta_model.fit(stack_X, y)

stack_preds = meta_model.predict_proba(stack_X)[:, 1]

print("Stacking AUC:", roc_auc_score(y, stack_preds))

Stacking AUC: 0.7377119222006876

## feature importance

**Изучим ценность фич, чтобы двигаться дальше**

In [43]:
feature_auc = []

for col in X.columns:
    try:
        auc = roc_auc_score(y, X[col])
    except:
        auc = 0.5
        
    feature_auc.append((col, auc))

feature_auc_df = pd.DataFrame(feature_auc, columns=['feature', 'auc'])
feature_auc_df = feature_auc_df.sort_values('auc', ascending=False)

feature_auc_df.head(20)

                                feature       auc
103  client_mean_bad_months_per_product  0.638736
105      client_mean_nonzero_paym_share  0.638736
107     client_mean_weighted_paym_score  0.614978
106             client_mean_paym_status  0.614978
104       client_mean_severe_bad_months  0.605064
58                      enc_paym_3_mean  0.604221
55                      enc_paym_2_mean  0.603623
61                      enc_paym_4_mean  0.601843
52                      enc_paym_1_mean  0.601438
64                      enc_paym_5_mean  0.598777
67                      enc_paym_6_mean  0.595305
69                      enc_paym_7_mean  0.594183
71                      enc_paym_8_mean  0.593371
73                      enc_paym_9_mean  0.592704
85                     enc_paym_15_mean  0.590589
83                     enc_paym_14_mean  0.590390
87                     enc_paym_16_mean  0.590182
75                     enc_paym_10_mean  0.590031
81                     enc_paym_13_mean  0.589891
77                     enc_paym_11_mean  0.589282

In [44]:
importances = cat_model.get_feature_importance()

importance_df = pd.DataFrame({
    'feature': X.columns,
    'importance': importances
}).sort_values('importance', ascending=False)

In [51]:
importance_df.head(20)

                                feature  importance
30                is_zero_loans530_mean    5.790033
21           pre_loans_outstanding_mean    3.665130
39                    is_zero_util_mean    3.623703
23      pre_loans_credit_cost_rate_mean    2.683089
36                         pre_util_max    2.546032
20            pre_loans_outstanding_max    2.531198
103  client_mean_bad_months_per_product    2.483325
105      client_mean_nonzero_paym_share    2.193993
28                  is_zero_loans5_mean    2.178622
32               is_zero_loans3060_mean    2.174839
16           pre_loans_credit_limit_max    2.162106
111           max_utilization_ratio_max    2.160523
35                        pre_util_mean    2.088007
113                       util_per_loan    2.017832
44        enc_loans_credit_type_nunique    1.988820
18         pre_loans_next_pay_summ_mean    1.778645
46                     pclose_flag_mean    1.756037
19          pre_loans_next_pay_summ_max    1.673041
14                  pre_till_fclose_min    1.529823
12                  pre_till_pclose_min    1.503060

In [55]:
sample_idx = np.random.choice(len(X_val), size=100_000, replace=False)

X_val_sample = X_val.iloc[sample_idx]
y_val_sample = y_val.iloc[sample_idx]

perm = permutation_importance(
    cat_model,
    X_val,
    y_val,
    n_repeats=3,
    random_state=42,
    n_jobs=-1
)

perm_df = pd.DataFrame({
    'feature': X.columns,
    'perm_importance': perm.importances_mean
}).sort_values('perm_importance', ascending=False)

In [83]:
full_df = feature_auc_df.merge(importance_df, on='feature')
full_df = full_df.merge(perm_df, on='feature')

full_df = full_df.sort_values('importance', ascending=False)

full_df.head(40)

,feature,auc,importance,perm_importance
115,is_zero_loans530_mean,0.428651,5.790033,-0.007433
47,pre_loans_outstanding_mean,0.534555,3.665130,0.018679
113,is_zero_util_mean,0.433346,3.623703,-0.028709
74,pre_loans_credit_cost_rate_mean,0.495666,2.683089,-0.006602
72,pre_util_max,0.496575,2.546032,-0.005480
49,pre_loans_outstanding_max,0.528906,2.531198,-0.009390
0,client_mean_bad_months_per_product,0.638736,2.483325,-0.014898
1,client_mean_nonzero_paym_share,0.638736,2.193993,-0.011921
102,is_zero_loans5_mean,0.463584,2.178622,-0.002118
112,is_zero_loans3060_mean,0.438289,2.174839,0.000744
63,pre_loans_credit_limit_max,0.505961,2.162106,-0.011151
95,max_utilization_ratio_max,0.477360,2.160523,-0.012626
110,pre_util_mean,0.441310,2.088007,-0.006795
114,util_per_loan,0.432611,2.017832,-0.007055
105,enc_loans_credit_type_nunique,0.459537,1.988820,0.002044
79,pre_loans_next_pay_summ_mean,0.493048,1.778645,-0.008439
64,pclose_flag_mean,0.503696,1.756037,-0.004641
87,pre_loans_next_pay_summ_max,0.487017,1.673041,-0.013126
40,pre_till_fclose_min,0.539871,1.529823,-0.009437
41,pre_till_pclose_min,0.537340,1.503060,0.002638
46,util_stability,0.534792,1.490729,-0.011915
43,pre_loans_credit_limit_mean,0.536724,1.459969,-0.011936
82,mean_utilization_ratio_max,0.490314,1.385830,-0.012171
99,pre_till_pclose_max,0.465217,1.357676,-0.008796
61,pre_since_opened_max,0.509650,1.336545,-0.005911
89,pre_pterm_mean,0.485396,1.319157,-0.001295
44,pre_pterm_min,0.536007,1.293688,-0.005316
55,fclose_flag_mean,0.520052,1.242500,-0.000340
92,enc_loans_account_holder_type_nunique,0.482340,1.229051,-0.001983
52,pre_since_opened_mean,0.522554,1.221376,-0.001084
39,last_paym_status_max,0.542167,1.215850,0.002741
6,enc_paym_2_mean,0.603623,1.120146,-0.004922
108,is_zero_loans90_mean,0.452692,1.094785,0.007977
27,enc_paym_23_mean,0.580759,1.088264,-0.000474
78,is_zero_over2limit_mean,0.493109,1.083013,0.003238
35,pre_since_opened_min,0.548200,1.003549,-0.004575
8,enc_paym_1_mean,0.601438,0.989464,-0.001421
103,pre_pterm_max,0.462017,0.971018,-0.005230
111,is_zero_loans530_sum,0.439111,0.959543,-0.005470
93,pre_fterm_mean,0.481202,0.934744,-0.001803

In [53]:
corr = X.corr().abs()

high_corr = (
    corr.where(np.triu(np.ones(corr.shape), k=1).astype(bool))
    .stack()
    .reset_index()
)

high_corr.columns = ['feature_1', 'feature_2', 'corr']
high_corr = high_corr[high_corr['corr'] > 0.9]

high_corr.sort_values('corr', ascending=False).head(20)

,feature_1,feature_2,corr
6519,client_mean_paym_status,client_mean_weighted_paym_score,1.000000
6490,client_mean_bad_months_per_product,client_mean_nonzero_paym_share,1.000000
2544,pre_loans5_sum,client_products_count_max,0.999410
2633,pre_loans530_sum,client_products_count_max,0.999095
2460,pre_loans5_sum,pre_loans530_sum,0.998688
6420,enc_paym_21_sum,enc_paym_22_sum,0.997739
6451,enc_paym_22_sum,enc_paym_23_sum,0.997673
6303,enc_paym_18_sum,enc_paym_19_sum,0.996994
6205,enc_paym_16_sum,enc_paym_17_sum,0.996676
6256,enc_paym_17_sum,enc_paym_18_sum,0.996612
6150,enc_paym_15_sum,enc_paym_16_sum,0.996363
6502,client_mean_severe_bad_months,client_mean_weighted_paym_score,0.995937
6501,client_mean_severe_bad_months,client_mean_paym_status,0.995937
6091,enc_paym_14_sum,enc_paym_15_sum,0.995925
6422,enc_paym_21_sum,enc_paym_23_sum,0.995590
6348,enc_paym_19_sum,enc_paym_21_sum,0.995319
6385,enc_paym_20_sum,enc_paym_21_sum,0.994964
6028,enc_paym_13_sum,enc_paym_14_sum,0.994745
6387,enc_paym_20_sum,enc_paym_22_sum,0.994307
6258,enc_paym_17_sum,enc_paym_19_sum,0.993828

# 5. Ensemble Models & Error Analysis

This section focuses on:
- combining models into ensembles
- analyzing model errors
- identifying strengths and weaknesses of different approaches

## modeling 20.03

### базовый ансамбль

In [108]:
cat_params = {
    'iterations': 1000,
    'depth': 8,
    'learning_rate': 0.05,
    'l2_leaf_reg': 7,
    'loss_function': 'Logloss',
    'eval_metric': 'AUC',
    'class_weights': class_weights_dict,
    'early_stopping_rounds': 100,
    'verbose': 200
}

lgb_params = {
    'n_estimators': 1000,
    'learning_rate': 0.05,
    'max_depth': -1,
    'random_state': 42,
    'class_weight': class_weights_dict
}

pos_weight = class_weights_dict[1] / class_weights_dict[0]
xgb_params = {
    'n_estimators': 1000,
    'learning_rate': 0.05,
    'max_depth': 6,
    'use_label_encoder': False,
    'eval_metric': 'auc',
    'random_state': 42,
    'scale_pos_weight': pos_weight
}

In [109]:
skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

oof_cat = np.zeros(len(X))
oof_lgb = np.zeros(len(X))
oof_xgb = np.zeros(len(X))

for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):
    print(f"\n===== FOLD {fold} =====")
    
    X_train, X_val = X.iloc[train_idx].copy(), X.iloc[val_idx].copy()
    y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

    for col in X_train.columns:
        if X_train[col].dtype.kind in 'f':
            median_val = X_train[col].replace([np.inf, -np.inf], np.nan).median()
            
            X_train[col] = X_train[col].replace([np.inf, -np.inf], median_val)
            X_val[col] = X_val[col].replace([np.inf, -np.inf], median_val)

    # CatBoost
    cat_model = CatBoostClassifier(**cat_params)
    cat_model.fit(X_train, y_train, eval_set=(X_val, y_val), use_best_model=True)
    oof_cat[val_idx] = cat_model.predict_proba(X_val)[:, 1]

    # LightGBM
    lgb_model = lgb.LGBMClassifier(**lgb_params)
    lgb_model.fit(X_train, y_train)
    oof_lgb[val_idx] = lgb_model.predict_proba(X_val)[:, 1]

    # XGBoost
    xgb_model = xgb.XGBClassifier(**xgb_params)
    xgb_model.fit(X_train, y_train)
    oof_xgb[val_idx] = xgb_model.predict_proba(X_val)[:, 1]


rank_cat = rankdata(oof_cat)
rank_lgb = rankdata(oof_lgb)
rank_xgb = rankdata(oof_xgb)

ensemble_rank = (rank_cat + rank_lgb + rank_xgb) / 3

stack_X = np.vstack([
    oof_cat,
    oof_lgb,
    oof_xgb
]).T

meta_model = CatBoostClassifier(
    iterations=300,
    depth=4,
    learning_rate=0.05,
    verbose=0
)
meta_model.fit(stack_X, y)

stack_preds = meta_model.predict_proba(stack_X)[:, 1]

print("Stacking AUC:", roc_auc_score(y, stack_preds))

===== FOLD 0 =====
0:	test: 0.6783225	best: 0.6783225 (0)	total: 481ms	remaining: 8m
200:	test: 0.7249159	best: 0.7249159 (200)	total: 1m 42s	remaining: 6m 45s
400:	test: 0.7307831	best: 0.7307831 (400)	total: 3m 22s	remaining: 5m 2s
600:	test: 0.7328709	best: 0.7328709 (600)	total: 5m 3s	remaining: 3m 21s
800:	test: 0.7337269	best: 0.7337291 (799)	total: 6m 46s	remaining: 1m 41s
999:	test: 0.7340554	best: 0.7341207 (971)	total: 8m 28s	remaining: 0us

bestTest = 0.7341206983
bestIteration = 971

Shrink model to first 972 iterations.
[LightGBM] [Info] Number of positive: 70962, number of negative: 1929038
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.769538 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15702
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 119
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500002 -> initscore=0.000010
[LightGBM] [Info] Start training from score 0.000010

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [15:43:48] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

===== FOLD 1 =====
0:	test: 0.6868586	best: 0.6868586 (0)	total: 520ms	remaining: 8m 39s
200:	test: 0.7301273	best: 0.7301273 (200)	total: 1m 43s	remaining: 6m 52s
400:	test: 0.7355632	best: 0.7355632 (400)	total: 3m 28s	remaining: 5m 11s
600:	test: 0.7371962	best: 0.7371962 (600)	total: 5m 11s	remaining: 3m 27s
800:	test: 0.7375765	best: 0.7376100 (793)	total: 6m 55s	remaining: 1m 43s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.7376655539
bestIteration = 893

Shrink model to first 894 iterations.
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.802707 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15707
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 119
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499999 -> initscore=-0.000005
[LightGBM] [Info] Start training from score -0.000005

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [16:00:01] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

===== FOLD 2 =====
0:	test: 0.6819886	best: 0.6819886 (0)	total: 452ms	remaining: 7m 31s
200:	test: 0.7258046	best: 0.7258046 (200)	total: 1m 43s	remaining: 6m 52s
400:	test: 0.7317767	best: 0.7317767 (400)	total: 3m 28s	remaining: 5m 10s
600:	test: 0.7338715	best: 0.7338717 (598)	total: 5m 11s	remaining: 3m 26s
800:	test: 0.7343777	best: 0.7343841 (799)	total: 6m 54s	remaining: 1m 42s
999:	test: 0.7346971	best: 0.7347317 (977)	total: 8m 36s	remaining: 0us

bestTest = 0.7347316832
bestIteration = 977

Shrink model to first 978 iterations.
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.819697 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15740
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 119
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499999 -> initscore=-0.000005
[LightGBM] [Info] Start training from score -0.000005

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [16:16:12] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Stacking AUC: 0.7370911177859396

### lightgbm grid

In [128]:
grid = {
    'num_leaves': [31, 64, 128],
    'min_child_samples': [20, 50],
    'subsample': [0.7, 0.9],
    'colsample_bytree': [0.7, 0.9]
}

best_auc = 0
best_params = None

for num_leaves, min_child, subsample, colsample in product(
    grid['num_leaves'],
    grid['min_child_samples'],
    grid['subsample'],
    grid['colsample_bytree']
):
    print(f"Testing: num_leaves={num_leaves}, min_child_samples={min_child}, subsample={subsample}, colsample_bytree={colsample}")
    
    model = LGBMClassifier(
        n_estimators=1000,
        learning_rate=0.05,
        num_leaves=num_leaves,
        min_child_samples=min_child,
        subsample=subsample,
        colsample_bytree=colsample,
        random_state=42,
        class_weight=class_weights_dict,
        n_jobs=-1
    )

    model.fit(
        X_train,
        y_train,
        eval_set=[(X_val, y_val)],
        eval_metric='auc',
        callbacks=[early_stopping(stopping_rounds=50), log_evaluation(period=100)]
    )
    
    preds = model.predict_proba(X_val)[:, 1]
    auc = roc_auc_score(y_val, preds)
    print(f"AUC: {auc}\n")
    
    if auc > best_auc:
        best_auc = auc
        best_params = {
            'num_leaves': num_leaves,
            'min_child_samples': min_child,
            'subsample': subsample,
            'colsample_bytree': colsample
        }

print(f"Best AUC: {best_auc} with params {best_params}")

Testing: num_leaves=31, min_child_samples=20, subsample=0.7, colsample_bytree=0.7
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.533224 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15740
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 119
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499999 -> initscore=-0.000005
[LightGBM] [Info] Start training from score -0.000005
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.723825	valid_0's binary_logloss: 0.610751
[200]	valid_0's auc: 0.730575	valid_0's binary_logloss: 0.601841
[300]	valid_0's auc: 0.732112	valid_0's binary_logloss: 0.596665
[400]	valid_0's auc: 0.732996	valid_0's binary_logloss: 0.592269
[500]	valid_0's auc: 0.733421	valid_0's binary_logloss: 0.588193
[600]	valid_0's auc: 0.733618	valid_0's binary_logloss: 0.584403
[700]	valid_0's auc: 0.73391	valid_0's binary_logloss: 0.580709
[800]	valid_0's auc: 0.734016	valid_0's binary_logloss: 0.577182
Early stopping, best iteration is:
[806]	valid_0's auc: 0.734029	valid_0's binary_logloss: 0.576944
AUC: 0.7340288442998313

Testing: num_leaves=31, min_child_samples=20, subsample=0.7, colsample_bytree=0.9
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.558198 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15740
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 119
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499999 -> initscore=-0.000005
[LightGBM] [Info] Start training from score -0.000005
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.723885	valid_0's binary_logloss: 0.610589
[200]	valid_0's auc: 0.73053	valid_0's binary_logloss: 0.601586
[300]	valid_0's auc: 0.732179	valid_0's binary_logloss: 0.596341
[400]	valid_0's auc: 0.732833	valid_0's binary_logloss: 0.591923
[500]	valid_0's auc: 0.733399	valid_0's binary_logloss: 0.587794
[600]	valid_0's auc: 0.733531	valid_0's binary_logloss: 0.583917
[700]	valid_0's auc: 0.733631	valid_0's binary_logloss: 0.580174
Early stopping, best iteration is:
[672]	valid_0's auc: 0.733668	valid_0's binary_logloss: 0.581203
AUC: 0.7336680846886153

Testing: num_leaves=31, min_child_samples=20, subsample=0.9, colsample_bytree=0.7
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.565380 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15740
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 119
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499999 -> initscore=-0.000005
[LightGBM] [Info] Start training from score -0.000005
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.723825	valid_0's binary_logloss: 0.610751
[200]	valid_0's auc: 0.730575	valid_0's binary_logloss: 0.601841
[300]	valid_0's auc: 0.732112	valid_0's binary_logloss: 0.596665
[400]	valid_0's auc: 0.732996	valid_0's binary_logloss: 0.592269
[500]	valid_0's auc: 0.733421	valid_0's binary_logloss: 0.588193
[600]	valid_0's auc: 0.733618	valid_0's binary_logloss: 0.584403
[700]	valid_0's auc: 0.73391	valid_0's binary_logloss: 0.580709
[800]	valid_0's auc: 0.734016	valid_0's binary_logloss: 0.577182
Early stopping, best iteration is:
[806]	valid_0's auc: 0.734029	valid_0's binary_logloss: 0.576944
AUC: 0.7340288442998313

Testing: num_leaves=31, min_child_samples=20, subsample=0.9, colsample_bytree=0.9
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.574277 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15740
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 119
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499999 -> initscore=-0.000005
[LightGBM] [Info] Start training from score -0.000005
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.723885	valid_0's binary_logloss: 0.610589
[200]	valid_0's auc: 0.73053	valid_0's binary_logloss: 0.601586
[300]	valid_0's auc: 0.732179	valid_0's binary_logloss: 0.596341
[400]	valid_0's auc: 0.732833	valid_0's binary_logloss: 0.591923
[500]	valid_0's auc: 0.733399	valid_0's binary_logloss: 0.587794
[600]	valid_0's auc: 0.733531	valid_0's binary_logloss: 0.583917
[700]	valid_0's auc: 0.733631	valid_0's binary_logloss: 0.580174
Early stopping, best iteration is:
[672]	valid_0's auc: 0.733668	valid_0's binary_logloss: 0.581203
AUC: 0.7336680846886153

Testing: num_leaves=31, min_child_samples=50, subsample=0.7, colsample_bytree=0.7
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.647246 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15740
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 119
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499999 -> initscore=-0.000005
[LightGBM] [Info] Start training from score -0.000005
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.723825	valid_0's binary_logloss: 0.610751
[200]	valid_0's auc: 0.730577	valid_0's binary_logloss: 0.601855
[300]	valid_0's auc: 0.732279	valid_0's binary_logloss: 0.596608
[400]	valid_0's auc: 0.733119	valid_0's binary_logloss: 0.592232
[500]	valid_0's auc: 0.733727	valid_0's binary_logloss: 0.588167
[600]	valid_0's auc: 0.733994	valid_0's binary_logloss: 0.584346
[700]	valid_0's auc: 0.734139	valid_0's binary_logloss: 0.580617
[800]	valid_0's auc: 0.734214	valid_0's binary_logloss: 0.577054
Early stopping, best iteration is:
[828]	valid_0's auc: 0.734256	valid_0's binary_logloss: 0.576088
AUC: 0.734256343322674

Testing: num_leaves=31, min_child_samples=50, subsample=0.7, colsample_bytree=0.9
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.559800 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15740
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 119
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499999 -> initscore=-0.000005
[LightGBM] [Info] Start training from score -0.000005
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.723885	valid_0's binary_logloss: 0.610589
[200]	valid_0's auc: 0.730362	valid_0's binary_logloss: 0.601695
[300]	valid_0's auc: 0.732017	valid_0's binary_logloss: 0.596389
[400]	valid_0's auc: 0.73286	valid_0's binary_logloss: 0.591855
[500]	valid_0's auc: 0.733371	valid_0's binary_logloss: 0.587697
[600]	valid_0's auc: 0.733637	valid_0's binary_logloss: 0.583762
[700]	valid_0's auc: 0.733927	valid_0's binary_logloss: 0.580042
Early stopping, best iteration is:
[716]	valid_0's auc: 0.733993	valid_0's binary_logloss: 0.579467
AUC: 0.7339927288057746

Testing: num_leaves=31, min_child_samples=50, subsample=0.9, colsample_bytree=0.7
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.577304 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15740
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 119
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499999 -> initscore=-0.000005
[LightGBM] [Info] Start training from score -0.000005
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.723825	valid_0's binary_logloss: 0.610751
[200]	valid_0's auc: 0.730577	valid_0's binary_logloss: 0.601855
[300]	valid_0's auc: 0.732279	valid_0's binary_logloss: 0.596608
[400]	valid_0's auc: 0.733119	valid_0's binary_logloss: 0.592232
[500]	valid_0's auc: 0.733727	valid_0's binary_logloss: 0.588167
[600]	valid_0's auc: 0.733994	valid_0's binary_logloss: 0.584346
[700]	valid_0's auc: 0.734139	valid_0's binary_logloss: 0.580617
[800]	valid_0's auc: 0.734214	valid_0's binary_logloss: 0.577054
Early stopping, best iteration is:
[828]	valid_0's auc: 0.734256	valid_0's binary_logloss: 0.576088
AUC: 0.734256343322674

Testing: num_leaves=31, min_child_samples=50, subsample=0.9, colsample_bytree=0.9
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.581208 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15740
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 119
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499999 -> initscore=-0.000005
[LightGBM] [Info] Start training from score -0.000005
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.723885	valid_0's binary_logloss: 0.610589
[200]	valid_0's auc: 0.730362	valid_0's binary_logloss: 0.601695
[300]	valid_0's auc: 0.732017	valid_0's binary_logloss: 0.596389
[400]	valid_0's auc: 0.73286	valid_0's binary_logloss: 0.591855
[500]	valid_0's auc: 0.733371	valid_0's binary_logloss: 0.587697
[600]	valid_0's auc: 0.733637	valid_0's binary_logloss: 0.583762
[700]	valid_0's auc: 0.733927	valid_0's binary_logloss: 0.580042
Early stopping, best iteration is:
[716]	valid_0's auc: 0.733993	valid_0's binary_logloss: 0.579467
AUC: 0.7339927288057746

Testing: num_leaves=64, min_child_samples=20, subsample=0.7, colsample_bytree=0.7
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.574714 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15740
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 119
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499999 -> initscore=-0.000005
[LightGBM] [Info] Start training from score -0.000005
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.727475	valid_0's binary_logloss: 0.603851
[200]	valid_0's auc: 0.732124	valid_0's binary_logloss: 0.592189
[300]	valid_0's auc: 0.73308	valid_0's binary_logloss: 0.583512
[400]	valid_0's auc: 0.733443	valid_0's binary_logloss: 0.57558
Early stopping, best iteration is:
[411]	valid_0's auc: 0.733535	valid_0's binary_logloss: 0.574718
AUC: 0.7335350541562677

Testing: num_leaves=64, min_child_samples=20, subsample=0.7, colsample_bytree=0.9
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.589185 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15740
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 119
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499999 -> initscore=-0.000005
[LightGBM] [Info] Start training from score -0.000005
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.727812	valid_0's binary_logloss: 0.603419
[200]	valid_0's auc: 0.732492	valid_0's binary_logloss: 0.591348
[300]	valid_0's auc: 0.733045	valid_0's binary_logloss: 0.582614
[400]	valid_0's auc: 0.733191	valid_0's binary_logloss: 0.574616
Early stopping, best iteration is:
[418]	valid_0's auc: 0.733223	valid_0's binary_logloss: 0.573159
AUC: 0.7332226556060567

Testing: num_leaves=64, min_child_samples=20, subsample=0.9, colsample_bytree=0.7
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.649892 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15740
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 119
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499999 -> initscore=-0.000005
[LightGBM] [Info] Start training from score -0.000005
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.727475	valid_0's binary_logloss: 0.603851
[200]	valid_0's auc: 0.732124	valid_0's binary_logloss: 0.592189
[300]	valid_0's auc: 0.73308	valid_0's binary_logloss: 0.583512
[400]	valid_0's auc: 0.733443	valid_0's binary_logloss: 0.57558
Early stopping, best iteration is:
[411]	valid_0's auc: 0.733535	valid_0's binary_logloss: 0.574718
AUC: 0.7335350541562677

Testing: num_leaves=64, min_child_samples=20, subsample=0.9, colsample_bytree=0.9
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.570965 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15740
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 119
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499999 -> initscore=-0.000005
[LightGBM] [Info] Start training from score -0.000005
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.727812	valid_0's binary_logloss: 0.603419
[200]	valid_0's auc: 0.732492	valid_0's binary_logloss: 0.591348
[300]	valid_0's auc: 0.733045	valid_0's binary_logloss: 0.582614
[400]	valid_0's auc: 0.733191	valid_0's binary_logloss: 0.574616
Early stopping, best iteration is:
[418]	valid_0's auc: 0.733223	valid_0's binary_logloss: 0.573159
AUC: 0.7332226556060567

Testing: num_leaves=64, min_child_samples=50, subsample=0.7, colsample_bytree=0.7
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.620878 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15740
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 119
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499999 -> initscore=-0.000005
[LightGBM] [Info] Start training from score -0.000005
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.72747	valid_0's binary_logloss: 0.603847
[200]	valid_0's auc: 0.732111	valid_0's binary_logloss: 0.59202
[300]	valid_0's auc: 0.732992	valid_0's binary_logloss: 0.583212
[400]	valid_0's auc: 0.733289	valid_0's binary_logloss: 0.575338
[500]	valid_0's auc: 0.733232	valid_0's binary_logloss: 0.567938
Early stopping, best iteration is:
[477]	valid_0's auc: 0.733328	valid_0's binary_logloss: 0.56954
AUC: 0.7333284288094533

Testing: num_leaves=64, min_child_samples=50, subsample=0.7, colsample_bytree=0.9
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.885156 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15740
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 119
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499999 -> initscore=-0.000005
[LightGBM] [Info] Start training from score -0.000005
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.727751	valid_0's binary_logloss: 0.603408
[200]	valid_0's auc: 0.732496	valid_0's binary_logloss: 0.591449
[300]	valid_0's auc: 0.733154	valid_0's binary_logloss: 0.582631
Early stopping, best iteration is:
[335]	valid_0's auc: 0.733206	valid_0's binary_logloss: 0.579773
AUC: 0.7332060220703404

Testing: num_leaves=64, min_child_samples=50, subsample=0.9, colsample_bytree=0.7
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.597561 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15740
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 119
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499999 -> initscore=-0.000005
[LightGBM] [Info] Start training from score -0.000005
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.72747	valid_0's binary_logloss: 0.603847
[200]	valid_0's auc: 0.732111	valid_0's binary_logloss: 0.59202
[300]	valid_0's auc: 0.732992	valid_0's binary_logloss: 0.583212
[400]	valid_0's auc: 0.733289	valid_0's binary_logloss: 0.575338
[500]	valid_0's auc: 0.733232	valid_0's binary_logloss: 0.567938
Early stopping, best iteration is:
[477]	valid_0's auc: 0.733328	valid_0's binary_logloss: 0.56954
AUC: 0.7333284288094533

Testing: num_leaves=64, min_child_samples=50, subsample=0.9, colsample_bytree=0.9
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.571895 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15740
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 119
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499999 -> initscore=-0.000005
[LightGBM] [Info] Start training from score -0.000005
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.727751	valid_0's binary_logloss: 0.603408
[200]	valid_0's auc: 0.732496	valid_0's binary_logloss: 0.591449
[300]	valid_0's auc: 0.733154	valid_0's binary_logloss: 0.582631
Early stopping, best iteration is:
[335]	valid_0's auc: 0.733206	valid_0's binary_logloss: 0.579773
AUC: 0.7332060220703404

Testing: num_leaves=128, min_child_samples=20, subsample=0.7, colsample_bytree=0.7
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.614581 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15740
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 119
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499999 -> initscore=-0.000005
[LightGBM] [Info] Start training from score -0.000005
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.729533	valid_0's binary_logloss: 0.594122
[200]	valid_0's auc: 0.732936	valid_0's binary_logloss: 0.575243
[300]	valid_0's auc: 0.733172	valid_0's binary_logloss: 0.559921
Early stopping, best iteration is:
[260]	valid_0's auc: 0.733256	valid_0's binary_logloss: 0.565859
AUC: 0.7332563795898537

Testing: num_leaves=128, min_child_samples=20, subsample=0.7, colsample_bytree=0.9
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.591836 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 15740
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 119
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499999 -> initscore=-0.000005
[LightGBM] [Info] Start training from score -0.000005
Training until validation scores don't improve for 50 rounds
[100]	valid_0's auc: 0.729909	valid_0's binary_logloss: 0.593235
[200]	valid_0's auc: 0.732967	valid_0's binary_logloss: 0.574339

### xgboost grid

In [142]:
pos_weight = class_weights_dict[0] / class_weights_dict[1]

sample_frac = 0.1

idx_0 = np.where(y_train == 0)[0]
idx_1 = np.where(y_train == 1)[0]

n_0 = int(len(idx_0) * sample_frac)
n_1 = int(len(idx_1) * sample_frac)

sample_idx_0 = np.random.choice(idx_0, size=n_0, replace=False)
sample_idx_1 = np.random.choice(idx_1, size=n_1, replace=False)

sample_idx = np.concatenate([sample_idx_0, sample_idx_1])
np.random.shuffle(sample_idx)

X_train_sample = X_train.iloc[sample_idx]
y_train_sample = y_train.iloc[sample_idx]

idx_val_0 = np.where(y_val == 0)[0]
idx_val_1 = np.where(y_val == 1)[0]

n_val_0 = int(len(idx_val_0) * sample_frac)
n_val_1 = int(len(idx_val_1) * sample_frac)

sample_val_idx_0 = np.random.choice(idx_val_0, size=n_val_0, replace=False)
sample_val_idx_1 = np.random.choice(idx_val_1, size=n_val_1, replace=False)

sample_val_idx = np.concatenate([sample_val_idx_0, sample_val_idx_1])
np.random.shuffle(sample_val_idx)

X_val_sample = X_val.iloc[sample_val_idx]
y_val_sample = y_val.iloc[sample_val_idx]

In [143]:
grid = {
    'max_depth': [4, 6, 8],
    'reg_lambda': [1, 5, 10],
    'reg_alpha': [0, 1, 5],
    'subsample': [0.6, 0.8],
    'colsample_bytree': [0.6, 0.8]
}

param_grid = list(product(
    grid['max_depth'],
    grid['reg_lambda'],
    grid['reg_alpha'],
    grid['subsample'],
    grid['colsample_bytree']
))

best_auc = 0
best_params = None

dtrain = xgb.DMatrix(X_train_sample, label=y_train_sample)
dval = xgb.DMatrix(X_val_sample, label=y_val_sample)

In [144]:
for i, (max_depth, reg_lambda, reg_alpha, subsample, colsample) in enumerate(param_grid, 1):
    print(f"[{i}/{len(param_grid)}] Testing: depth={max_depth}, lambda={reg_lambda}, alpha={reg_alpha}, subsample={subsample}, colsample={colsample}")

    params = {
        'objective': 'binary:logistic',
        'eval_metric': 'auc',
        'max_depth': max_depth,
        'subsample': subsample,
        'colsample_bytree': colsample,
        'reg_lambda': reg_lambda,
        'reg_alpha': reg_alpha,
        'eta': 0.05,
        'scale_pos_weight': pos_weight,
        'seed': 42,
        'nthread': 12,
        'tree_method': 'hist'
    }

    model = xgb.train(
        params,
        dtrain,
        num_boost_round=300,
        evals=[(dval, 'eval')],
        early_stopping_rounds=50,
        verbose_eval=False
    )

    preds = model.predict(dval)
    auc = roc_auc_score(y_val_sample, preds)
    print(f"AUC: {auc:.6f}")

    if auc > best_auc:
        best_auc = auc
        best_params = {
            'max_depth': max_depth,
            'reg_lambda': reg_lambda,
            'reg_alpha': reg_alpha,
            'subsample': subsample,
            'colsample_bytree': colsample
        }
        print(">>> NEW BEST <<<")

print("\nBest AUC:", best_auc)
print("Best params:", best_params)

[1/108] Testing: depth=4, lambda=1, alpha=0, subsample=0.6, colsample=0.6
AUC: 0.720375
>>> NEW BEST <<<
[2/108] Testing: depth=4, lambda=1, alpha=0, subsample=0.6, colsample=0.8
AUC: 0.720291
[3/108] Testing: depth=4, lambda=1, alpha=0, subsample=0.8, colsample=0.6
AUC: 0.721702
>>> NEW BEST <<<
[4/108] Testing: depth=4, lambda=1, alpha=0, subsample=0.8, colsample=0.8
AUC: 0.722051
>>> NEW BEST <<<
[5/108] Testing: depth=4, lambda=1, alpha=1, subsample=0.6, colsample=0.6
AUC: 0.719384
[6/108] Testing: depth=4, lambda=1, alpha=1, subsample=0.6, colsample=0.8
AUC: 0.719952
[7/108] Testing: depth=4, lambda=1, alpha=1, subsample=0.8, colsample=0.6
AUC: 0.720347
[8/108] Testing: depth=4, lambda=1, alpha=1, subsample=0.8, colsample=0.8
AUC: 0.720357
[9/108] Testing: depth=4, lambda=1, alpha=5, subsample=0.6, colsample=0.6
AUC: 0.711882
[10/108] Testing: depth=4, lambda=1, alpha=5, subsample=0.6, colsample=0.8
AUC: 0.712369
[11/108] Testing: depth=4, lambda=1, alpha=5, subsample=0.8, colsample=0.6
AUC: 0.713773
[12/108] Testing: depth=4, lambda=1, alpha=5, subsample=0.8, colsample=0.8
AUC: 0.713759
[13/108] Testing: depth=4, lambda=5, alpha=0, subsample=0.6, colsample=0.6
AUC: 0.720293
[14/108] Testing: depth=4, lambda=5, alpha=0, subsample=0.6, colsample=0.8
AUC: 0.720976
[15/108] Testing: depth=4, lambda=5, alpha=0, subsample=0.8, colsample=0.6
AUC: 0.721044
[16/108] Testing: depth=4, lambda=5, alpha=0, subsample=0.8, colsample=0.8
AUC: 0.721865
[17/108] Testing: depth=4, lambda=5, alpha=1, subsample=0.6, colsample=0.6
AUC: 0.718501
[18/108] Testing: depth=4, lambda=5, alpha=1, subsample=0.6, colsample=0.8
AUC: 0.719261
[19/108] Testing: depth=4, lambda=5, alpha=1, subsample=0.8, colsample=0.6
AUC: 0.719493
[20/108] Testing: depth=4, lambda=5, alpha=1, subsample=0.8, colsample=0.8
AUC: 0.720080
[21/108] Testing: depth=4, lambda=5, alpha=5, subsample=0.6, colsample=0.6
AUC: 0.711793
[22/108] Testing: depth=4, lambda=5, alpha=5, subsample=0.6, colsample=0.8
AUC: 0.712232
[23/108] Testing: depth=4, lambda=5, alpha=5, subsample=0.8, colsample=0.6
AUC: 0.713224
[24/108] Testing: depth=4, lambda=5, alpha=5, subsample=0.8, colsample=0.8
AUC: 0.713243
[25/108] Testing: depth=4, lambda=10, alpha=0, subsample=0.6, colsample=0.6
AUC: 0.719302
[26/108] Testing: depth=4, lambda=10, alpha=0, subsample=0.6, colsample=0.8
AUC: 0.719810
[27/108] Testing: depth=4, lambda=10, alpha=0, subsample=0.8, colsample=0.6
AUC: 0.720479
[28/108] Testing: depth=4, lambda=10, alpha=0, subsample=0.8, colsample=0.8
AUC: 0.720708
[29/108] Testing: depth=4, lambda=10, alpha=1, subsample=0.6, colsample=0.6
AUC: 0.716425
[30/108] Testing: depth=4, lambda=10, alpha=1, subsample=0.6, colsample=0.8
AUC: 0.718362
[31/108] Testing: depth=4, lambda=10, alpha=1, subsample=0.8, colsample=0.6
AUC: 0.718574
[32/108] Testing: depth=4, lambda=10, alpha=1, subsample=0.8, colsample=0.8
AUC: 0.718787
[33/108] Testing: depth=4, lambda=10, alpha=5, subsample=0.6, colsample=0.6
AUC: 0.710857
[34/108] Testing: depth=4, lambda=10, alpha=5, subsample=0.6, colsample=0.8
AUC: 0.711638
[35/108] Testing: depth=4, lambda=10, alpha=5, subsample=0.8, colsample=0.6
AUC: 0.712680
[36/108] Testing: depth=4, lambda=10, alpha=5, subsample=0.8, colsample=0.8
AUC: 0.712702
[37/108] Testing: depth=6, lambda=1, alpha=0, subsample=0.6, colsample=0.6
AUC: 0.720422
[38/108] Testing: depth=6, lambda=1, alpha=0, subsample=0.6, colsample=0.8
AUC: 0.720273
[39/108] Testing: depth=6, lambda=1, alpha=0, subsample=0.8, colsample=0.6
AUC: 0.722597
>>> NEW BEST <<<
[40/108] Testing: depth=6, lambda=1, alpha=0, subsample=0.8, colsample=0.8
AUC: 0.721695
[41/108] Testing: depth=6, lambda=1, alpha=1, subsample=0.6, colsample=0.6
AUC: 0.719784
[42/108] Testing: depth=6, lambda=1, alpha=1, subsample=0.6, colsample=0.8
AUC: 0.721185
[43/108] Testing: depth=6, lambda=1, alpha=1, subsample=0.8, colsample=0.6
AUC: 0.721951
[44/108] Testing: depth=6, lambda=1, alpha=1, subsample=0.8, colsample=0.8
AUC: 0.721339
[45/108] Testing: depth=6, lambda=1, alpha=5, subsample=0.6, colsample=0.6
AUC: 0.713053
[46/108] Testing: depth=6, lambda=1, alpha=5, subsample=0.6, colsample=0.8
AUC: 0.713318
[47/108] Testing: depth=6, lambda=1, alpha=5, subsample=0.8, colsample=0.6
AUC: 0.714232
[48/108] Testing: depth=6, lambda=1, alpha=5, subsample=0.8, colsample=0.8
AUC: 0.714277
[49/108] Testing: depth=6, lambda=5, alpha=0, subsample=0.6, colsample=0.6
AUC: 0.720903
[50/108] Testing: depth=6, lambda=5, alpha=0, subsample=0.6, colsample=0.8
AUC: 0.722216
[51/108] Testing: depth=6, lambda=5, alpha=0, subsample=0.8, colsample=0.6
AUC: 0.722190
[52/108] Testing: depth=6, lambda=5, alpha=0, subsample=0.8, colsample=0.8
AUC: 0.722314
[53/108] Testing: depth=6, lambda=5, alpha=1, subsample=0.6, colsample=0.6
AUC: 0.719311
[54/108] Testing: depth=6, lambda=5, alpha=1, subsample=0.6, colsample=0.8
AUC: 0.719487
[55/108] Testing: depth=6, lambda=5, alpha=1, subsample=0.8, colsample=0.6
AUC: 0.720552
[56/108] Testing: depth=6, lambda=5, alpha=1, subsample=0.8, colsample=0.8
AUC: 0.720854
[57/108] Testing: depth=6, lambda=5, alpha=5, subsample=0.6, colsample=0.6
AUC: 0.712185
[58/108] Testing: depth=6, lambda=5, alpha=5, subsample=0.6, colsample=0.8
AUC: 0.712561
[59/108] Testing: depth=6, lambda=5, alpha=5, subsample=0.8, colsample=0.6
AUC: 0.713761
[60/108] Testing: depth=6, lambda=5, alpha=5, subsample=0.8, colsample=0.8
AUC: 0.714542
[61/108] Testing: depth=6, lambda=10, alpha=0, subsample=0.6, colsample=0.6
AUC: 0.720710
[62/108] Testing: depth=6, lambda=10, alpha=0, subsample=0.6, colsample=0.8
AUC: 0.720939
[63/108] Testing: depth=6, lambda=10, alpha=0, subsample=0.8, colsample=0.6
AUC: 0.721338
[64/108] Testing: depth=6, lambda=10, alpha=0, subsample=0.8, colsample=0.8
AUC: 0.723028
>>> NEW BEST <<<
[65/108] Testing: depth=6, lambda=10, alpha=1, subsample=0.6, colsample=0.6
AUC: 0.717612
[66/108] Testing: depth=6, lambda=10, alpha=1, subsample=0.6, colsample=0.8
AUC: 0.718578
[67/108] Testing: depth=6, lambda=10, alpha=1, subsample=0.8, colsample=0.6
AUC: 0.719422
[68/108] Testing: depth=6, lambda=10, alpha=1, subsample=0.8, colsample=0.8
AUC: 0.720284
[69/108] Testing: depth=6, lambda=10, alpha=5, subsample=0.6, colsample=0.6
AUC: 0.711625
[70/108] Testing: depth=6, lambda=10, alpha=5, subsample=0.6, colsample=0.8
AUC: 0.712005
[71/108] Testing: depth=6, lambda=10, alpha=5, subsample=0.8, colsample=0.6
AUC: 0.713317
[72/108] Testing: depth=6, lambda=10, alpha=5, subsample=0.8, colsample=0.8
AUC: 0.713502
[73/108] Testing: depth=8, lambda=1, alpha=0, subsample=0.6, colsample=0.6
AUC: 0.718598
[74/108] Testing: depth=8, lambda=1, alpha=0, subsample=0.6, colsample=0.8
AUC: 0.719757
[75/108] Testing: depth=8, lambda=1, alpha=0, subsample=0.8, colsample=0.6
AUC: 0.721679
[76/108] Testing: depth=8, lambda=1, alpha=0, subsample=0.8, colsample=0.8
AUC: 0.720433
[77/108] Testing: depth=8, lambda=1, alpha=1, subsample=0.6, colsample=0.6
AUC: 0.720249
[78/108] Testing: depth=8, lambda=1, alpha=1, subsample=0.6, colsample=0.8
AUC: 0.721551
[79/108] Testing: depth=8, lambda=1, alpha=1, subsample=0.8, colsample=0.6
AUC: 0.720735
[80/108] Testing: depth=8, lambda=1, alpha=1, subsample=0.8, colsample=0.8
AUC: 0.721671
[81/108] Testing: depth=8, lambda=1, alpha=5, subsample=0.6, colsample=0.6
AUC: 0.712965
[82/108] Testing: depth=8, lambda=1, alpha=5, subsample=0.6, colsample=0.8
AUC: 0.713206
[83/108] Testing: depth=8, lambda=1, alpha=5, subsample=0.8, colsample=0.6
AUC: 0.714189
[84/108] Testing: depth=8, lambda=1, alpha=5, subsample=0.8, colsample=0.8
AUC: 0.714377
[85/108] Testing: depth=8, lambda=5, alpha=0, subsample=0.6, colsample=0.6
AUC: 0.721062
[86/108] Testing: depth=8, lambda=5, alpha=0, subsample=0.6, colsample=0.8
AUC: 0.721822
[87/108] Testing: depth=8, lambda=5, alpha=0, subsample=0.8, colsample=0.6
AUC: 0.721972
[88/108] Testing: depth=8, lambda=5, alpha=0, subsample=0.8, colsample=0.8
AUC: 0.723005
[89/108] Testing: depth=8, lambda=5, alpha=1, subsample=0.6, colsample=0.6
AUC: 0.719111
[90/108] Testing: depth=8, lambda=5, alpha=1, subsample=0.6, colsample=0.8
AUC: 0.719754
[91/108] Testing: depth=8, lambda=5, alpha=1, subsample=0.8, colsample=0.6
AUC: 0.720419
[92/108] Testing: depth=8, lambda=5, alpha=1, subsample=0.8, colsample=0.8
AUC: 0.720851
[93/108] Testing: depth=8, lambda=5, alpha=5, subsample=0.6, colsample=0.6
AUC: 0.711989
[94/108] Testing: depth=8, lambda=5, alpha=5, subsample=0.6, colsample=0.8
AUC: 0.712974
[95/108] Testing: depth=8, lambda=5, alpha=5, subsample=0.8, colsample=0.6
AUC: 0.713618
[96/108] Testing: depth=8, lambda=5, alpha=5, subsample=0.8, colsample=0.8
AUC: 0.714118
[97/108] Testing: depth=8, lambda=10, alpha=0, subsample=0.6, colsample=0.6
AUC: 0.719479
[98/108] Testing: depth=8, lambda=10, alpha=0, subsample=0.6, colsample=0.8
AUC: 0.720121
[99/108] Testing: depth=8, lambda=10, alpha=0, subsample=0.8, colsample=0.6
AUC: 0.721163
[100/108] Testing: depth=8, lambda=10, alpha=0, subsample=0.8, colsample=0.8
AUC: 0.721707
[101/108] Testing: depth=8, lambda=10, alpha=1, subsample=0.6, colsample=0.6
AUC: 0.717476
[102/108] Testing: depth=8, lambda=10, alpha=1, subsample=0.6, colsample=0.8
AUC: 0.718051
[103/108] Testing: depth=8, lambda=10, alpha=1, subsample=0.8, colsample=0.6
AUC: 0.719216
[104/108] Testing: depth=8, lambda=10, alpha=1, subsample=0.8, colsample=0.8
AUC: 0.719369
[105/108] Testing: depth=8, lambda=10, alpha=5, subsample=0.6, colsample=0.6
AUC: 0.711393
[106/108] Testing: depth=8, lambda=10, alpha=5, subsample=0.6, colsample=0.8
AUC: 0.712157
[107/108] Testing: depth=8, lambda=10, alpha=5, subsample=0.8, colsample=0.6
AUC: 0.713028
[108/108] Testing: depth=8, lambda=10, alpha=5, subsample=0.8, colsample=0.8
AUC: 0.713590

Best AUC: 0.7230283540764786
Best params: {'max_depth': 6, 'reg_lambda': 10, 'reg_alpha': 0, 'subsample': 0.8, 'colsample_bytree': 0.8}

### ансамбль с гиперпараметрами

In [173]:
cat_params = {
    'iterations': 1000,
    'depth': 8,
    'learning_rate': 0.05,
    'l2_leaf_reg': 7,
    'loss_function': 'Logloss',
    'eval_metric': 'AUC',
    'class_weights': class_weights_dict,
    'early_stopping_rounds': 100,
    'verbose': 200
}

{'num_leaves': 31, 'min_child_samples': 50, 'subsample': 0.7, 'colsample_bytree': 0.7}

lgb_params = {
    'n_estimators': 1000,
    'num_leaves': 31,
    'colsample_bytree': 0.7,
    'min_child_samples': 50,
    'subsample': 0.7,
    'learning_rate': 0.05,
    'max_depth': -1,
    'random_state': 42,
    'class_weight': class_weights_dict
}

pos_weight = class_weights_dict[1] / class_weights_dict[0]
xgb_params = {
    'n_estimators': 1000,
    'learning_rate': 0.05,
    'max_depth': 6,
    'reg_lambda': 10, 
    'reg_alpha': 0, 
    'subsample': 0.8, 
    'colsample_bytree': 0.8,
    'eval_metric': 'auc',
    'random_state': 42,
    'scale_pos_weight': pos_weight
}

In [174]:
skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

oof_cat = np.zeros(len(X))
oof_lgb = np.zeros(len(X))
oof_xgb = np.zeros(len(X))

for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):
    print(f"\n===== FOLD {fold} =====")
    
    X_train, X_val = X.iloc[train_idx].copy(), X.iloc[val_idx].copy()
    y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

    for col in X_train.columns:
        if X_train[col].dtype.kind in 'f':
            median_val = X_train[col].replace([np.inf, -np.inf], np.nan).median()
            
            X_train[col] = X_train[col].replace([np.inf, -np.inf], median_val)
            X_val[col] = X_val[col].replace([np.inf, -np.inf], median_val)

    # CatBoost
    cat_model = CatBoostClassifier(**cat_params)
    cat_model.fit(X_train, y_train, eval_set=(X_val, y_val), use_best_model=True)
    oof_cat[val_idx] = cat_model.predict_proba(X_val)[:, 1]

    # LightGBM
    lgb_model = lgb.LGBMClassifier(**lgb_params)
    lgb_model.fit(X_train, y_train)
    oof_lgb[val_idx] = lgb_model.predict_proba(X_val)[:, 1]

    # XGBoost
    xgb_model = xgb.XGBClassifier(**xgb_params)
    xgb_model.fit(X_train, y_train)
    oof_xgb[val_idx] = xgb_model.predict_proba(X_val)[:, 1]


rank_cat = rankdata(oof_cat)
rank_lgb = rankdata(oof_lgb)
rank_xgb = rankdata(oof_xgb)

ensemble_rank = (rank_cat + rank_lgb + rank_xgb) / 3

stack_X = np.vstack([
    oof_cat,
    oof_lgb,
    oof_xgb
]).T

meta_model = CatBoostClassifier(
    iterations=300,
    depth=4,
    learning_rate=0.05,
    verbose=0
)
meta_model.fit(stack_X, y)

stack_preds = meta_model.predict_proba(stack_X)[:, 1]

print("Stacking AUC:", roc_auc_score(y, stack_preds))

===== FOLD 0 =====
0:	test: 0.6808578	best: 0.6808578 (0)	total: 518ms	remaining: 8m 37s
200:	test: 0.7257704	best: 0.7257704 (200)	total: 1m 42s	remaining: 6m 46s
400:	test: 0.7315526	best: 0.7315526 (400)	total: 3m 23s	remaining: 5m 3s
600:	test: 0.7334004	best: 0.7334004 (600)	total: 5m 4s	remaining: 3m 21s
800:	test: 0.7339334	best: 0.7339334 (800)	total: 6m 44s	remaining: 1m 40s
999:	test: 0.7342772	best: 0.7342772 (999)	total: 8m 25s	remaining: 0us

bestTest = 0.7342772286
bestIteration = 999

[LightGBM] [Info] Number of positive: 70962, number of negative: 1929038
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.837383 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 17560
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 128
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500002 -> initscore=0.000010
[LightGBM] [Info] Start training from score 0.000010

===== FOLD 1 =====
0:	test: 0.6838635	best: 0.6838635 (0)	total: 508ms	remaining: 8m 27s
200:	test: 0.7311603	best: 0.7311603 (200)	total: 1m 42s	remaining: 6m 48s
400:	test: 0.7364143	best: 0.7364143 (400)	total: 3m 26s	remaining: 5m 8s
600:	test: 0.7380691	best: 0.7380792 (599)	total: 5m 8s	remaining: 3m 24s
800:	test: 0.7383201	best: 0.7384307 (726)	total: 6m 49s	remaining: 1m 41s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.7384307389
bestIteration = 726

Shrink model to first 727 iterations.
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.857579 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 17563
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 128
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499999 -> initscore=-0.000005
[LightGBM] [Info] Start training from score -0.000005

===== FOLD 2 =====
0:	test: 0.6833766	best: 0.6833766 (0)	total: 480ms	remaining: 7m 59s
200:	test: 0.7271628	best: 0.7271628 (200)	total: 1m 42s	remaining: 6m 46s
400:	test: 0.7332792	best: 0.7332857 (399)	total: 3m 25s	remaining: 5m 6s
600:	test: 0.7353183	best: 0.7353204 (598)	total: 5m 6s	remaining: 3m 23s
800:	test: 0.7360598	best: 0.7361116 (789)	total: 6m 46s	remaining: 1m 41s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.7361115902
bestIteration = 789

Shrink model to first 790 iterations.
[LightGBM] [Info] Number of positive: 70961, number of negative: 1929039
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.823652 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 17602
[LightGBM] [Info] Number of data points in the train set: 2000000, number of used features: 128
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499999 -> initscore=-0.000005
[LightGBM] [Info] Start training from score -0.000005
Stacking AUC: 0.7385339657686977

### feature importance

In [146]:
feature_auc = []

for col in X.columns:
    vals = X[col].replace([np.inf, -np.inf], np.nan).fillna(0)
    
    auc = roc_auc_score(y, vals)
    auc_inv = roc_auc_score(y, -vals)
    
    feature_auc.append((col, max(auc, auc_inv)))

feature_auc = sorted(feature_auc, key=lambda x: x[1], reverse=True)

for col, auc in feature_auc[:30]:
    print(f"{col}: {auc:.6f}")

client_mean_bad_months_per_product: 0.638736
client_mean_nonzero_paym_share: 0.638736
bad_months_score: 0.627133
client_mean_weighted_paym_score: 0.614978
client_mean_paym_status: 0.614978
client_mean_severe_bad_months: 0.605064
enc_paym_3_mean: 0.604221
enc_paym_2_mean: 0.603623
enc_paym_4_mean: 0.601843
enc_paym_1_mean: 0.601438
enc_paym_5_mean: 0.598777
enc_paym_6_mean: 0.595305
enc_paym_7_mean: 0.594183
enc_paym_8_mean: 0.593371
recent_paym_mean: 0.592972
enc_paym_9_mean: 0.592704
enc_paym_15_mean: 0.590589
enc_paym_14_mean: 0.590390
enc_paym_16_mean: 0.590182
enc_paym_10_mean: 0.590031
enc_paym_13_mean: 0.589891
enc_paym_11_mean: 0.589282
enc_paym_17_mean: 0.589158
zero_loan_score: 0.588319
enc_paym_12_mean: 0.588315
enc_paym_18_mean: 0.588268
enc_paym_19_mean: 0.587206
enc_paym_20_mean: 0.585861
enc_paym_21_mean: 0.584146
enc_paym_22_mean: 0.582374

In [147]:
for col, auc in feature_auc[30:]:
    print(f"{col}: {auc:.6f}")

enc_paym_23_mean: 0.580759
enc_paym_0_mean: 0.572855
enc_paym_1_sum: 0.572804
is_zero_loans530_mean: 0.571349
util_per_loan: 0.567389
is_zero_util_mean: 0.566654
enc_paym_2_sum: 0.565492
enc_paym_0_sum: 0.562994
is_zero_loans3060_mean: 0.561711
is_zero_loans530_sum: 0.560889
pre_util_mean: 0.558690
enc_paym_3_sum: 0.556406
enc_paym_0_max: 0.555560
enc_paym_1_max: 0.554150
is_zero_loans6090_mean: 0.549696
pre_since_opened_min: 0.548200
is_zero_loans90_mean: 0.547308
enc_paym_4_sum: 0.545887
client_max_weighted_paym_score: 0.545398
is_zero_loans5_sum: 0.543351
enc_paym_2_max: 0.542854
last_paym_status_max: 0.542167
pre_fterm_max: 0.540958
enc_loans_credit_type_nunique: 0.540463
is_zero_maxover2limit_mean: 0.540373
pre_till_fclose_min: 0.539871
pre_pterm_max: 0.537983
pre_till_pclose_min: 0.537340
enc_paym_5_sum: 0.536896
pre_loans_credit_limit_mean: 0.536724
is_zero_loans5_mean: 0.536416
pre_pterm_min: 0.536007
pre_fterm_min: 0.535720
pre_loans530_sum: 0.535686
pre_loans5_sum: 0.535320
util_stability: 0.534792
pre_till_pclose_max: 0.534783
pre_loans_outstanding_mean: 0.534555
enc_paym_3_max: 0.534197
client_products_count_max: 0.534108
pre_loans_outstanding_max: 0.528906
pre_since_confirmed_max: 0.527252
enc_paym_6_sum: 0.526964
enc_paym_4_max: 0.526376
pre_till_fclose_max: 0.525272
mean_utilization_ratio_max: 0.524374
pre_since_opened_mean: 0.522554
recent_paym_trend: 0.521643
enc_paym_5_max: 0.520548
enc_paym_7_sum: 0.520311
max_utilization_ratio_max: 0.520109
fclose_flag_mean: 0.520052
enc_paym_20_sum: 0.519476
pre_fterm_mean: 0.518798
enc_loans_account_holder_type_nunique: 0.517660
enc_loans_credit_status_nunique: 0.517579
enc_paym_8_sum: 0.515817
enc_paym_6_max: 0.515378
enc_paym_23_sum: 0.515293
pre_loans_max_overdue_sum_max: 0.514897
pre_pterm_mean: 0.514604
enc_paym_22_sum: 0.514159
pre_since_confirmed_min: 0.513265
pre_loans_next_pay_summ_max: 0.512983
enc_paym_21_sum: 0.512969
enc_paym_9_sum: 0.511917
enc_paym_11_sum: 0.511487
pre_since_confirmed_mean: 0.511116
enc_paym_19_sum: 0.510516
pre_since_opened_max: 0.509650
enc_paym_18_sum: 0.509292
enc_paym_17_sum: 0.507988
pre_loans_next_pay_summ_mean: 0.506952
is_zero_over2limit_mean: 0.506891
enc_paym_16_sum: 0.506720
enc_paym_10_sum: 0.506667
pre_loans_credit_limit_max: 0.505961
enc_paym_15_sum: 0.505523
enc_paym_14_sum: 0.504388
pre_loans_credit_cost_rate_mean: 0.504334
enc_loans_account_cur_nunique: 0.503947
pclose_flag_mean: 0.503696
pre_util_max: 0.503425
pre_loans3060_max: 0.503194
enc_paym_13_sum: 0.503181
pre_maxover2limit_max: 0.503040
pre_over2limit_max: 0.501940
enc_paym_12_sum: 0.501019
pre_loans530_max: 0.500735

In [148]:
feature_importance = cat_model.get_feature_importance()
feature_names = X.columns

fi_df = pd.DataFrame({
    "feature": feature_names,
    "importance": feature_importance
}).sort_values(by="importance", ascending=False)

print(fi_df.tail(30))

                             feature  importance
94                   enc_paym_19_sum    0.293732
107  client_mean_weighted_paym_score    0.269750
24                    pre_loans5_sum    0.245819
26                  pre_loans530_max    0.244170
96                   enc_paym_20_sum    0.236175
59                    enc_paym_3_sum    0.226496
90                   enc_paym_17_sum    0.225375
82                   enc_paym_13_sum    0.216299
68                    enc_paym_6_sum    0.214585
84                   enc_paym_14_sum    0.196824
74                    enc_paym_9_sum    0.194060
72                    enc_paym_8_sum    0.188039
109        client_products_count_max    0.187010
98                   enc_paym_21_sum    0.173042
65                    enc_paym_5_sum    0.169605
51                    enc_paym_1_max    0.169473
88                   enc_paym_16_sum    0.168096
76                   enc_paym_10_sum    0.166629
70                    enc_paym_7_sum    0.148177
92                   enc_paym_18_sum    0.145548
86                   enc_paym_15_sum    0.130766
27                 pre_loans3060_max    0.112872
62                    enc_paym_4_sum    0.109614
80                   enc_paym_12_sum    0.106110
66                    enc_paym_6_max    0.084200
38             pre_maxover2limit_max    0.063879
63                    enc_paym_5_max    0.051196
57                    enc_paym_3_max    0.044960
60                    enc_paym_4_max    0.029805
54                    enc_paym_2_max    0.010984

In [150]:
print(fi_df.head(30))

                                feature  importance
118                     zero_loan_score    6.175080
21           pre_loans_outstanding_mean    3.714530
39                    is_zero_util_mean    3.128657
23      pre_loans_credit_cost_rate_mean    2.800118
20            pre_loans_outstanding_max    2.262751
36                         pre_util_max    2.135839
111           max_utilization_ratio_max    2.099523
16           pre_loans_credit_limit_max    1.966642
113                       util_per_loan    1.946068
105      client_mean_nonzero_paym_share    1.921919
18         pre_loans_next_pay_summ_mean    1.890411
35                        pre_util_mean    1.883610
114                      util_stability    1.802261
17          pre_loans_credit_limit_mean    1.706610
14                  pre_till_fclose_min    1.692305
44        enc_loans_credit_type_nunique    1.665300
46                     pclose_flag_mean    1.649465
19          pre_loans_next_pay_summ_max    1.649278
110          mean_utilization_ratio_max    1.637752
8                        pre_pterm_mean    1.461882
13                  pre_till_pclose_max    1.455046
103  client_mean_bad_months_per_product    1.415465
30                is_zero_loans530_mean    1.398506
12                  pre_till_pclose_min    1.389871
2                 pre_since_opened_mean    1.335528
47                     fclose_flag_mean    1.310340
1                  pre_since_opened_max    1.230320
101                    enc_paym_23_mean    1.218429
6                         pre_pterm_min    1.214643
55                      enc_paym_2_mean    1.196889

#

## modeling 22.03

In [23]:
cat_params = {
    'iterations': 5000,
    'depth': 8,
    'learning_rate': 0.03,
    'l2_leaf_reg': 7,
    'loss_function': 'Logloss',
    'eval_metric': 'AUC',
    'class_weights': class_weights_dict,
    'early_stopping_rounds': 200,
    'verbose': 200
}

lgb_params = {
    'n_estimators': 5000,
    'num_leaves': 31,
    'colsample_bytree': 0.7,
    'min_child_samples': 50,
    'subsample': 0.7,
    'learning_rate': 0.03,
    'max_depth': -1,
    'random_state': 42,
    'class_weight': class_weights_dict
}

pos_weight = class_weights_dict[1] / class_weights_dict[0]
xgb_params = {
    'n_estimators': 5000,
    'learning_rate': 0.03,
    'max_depth': 6,
    'reg_lambda': 10,
    'reg_alpha': 0,
    'subsample': 0.8,
    'colsample_bytree': 0.8,
    'eval_metric': 'auc',
    'random_state': 42,
    'scale_pos_weight': pos_weight,
    'early_stopping_rounds': 200
}

In [24]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

oof_cat = np.zeros(len(X))
oof_lgb = np.zeros(len(X))
oof_xgb = np.zeros(len(X))

for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):
    print(f"\n===== FOLD {fold} =====")

    X_train, X_val = X.iloc[train_idx].copy(), X.iloc[val_idx].copy()
    y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

    # === обработка inf ===
    for col in X_train.columns:
        if X_train[col].dtype.kind in 'f':
            median_val = X_train[col].replace([np.inf, -np.inf], np.nan).median()
            X_train[col] = X_train[col].replace([np.inf, -np.inf], median_val)
            X_val[col] = X_val[col].replace([np.inf, -np.inf], median_val)

    # === CatBoost ===
    cat_model = CatBoostClassifier(**cat_params)
    cat_model.fit(X_train, y_train, eval_set=(X_val, y_val), use_best_model=True)
    oof_cat[val_idx] = cat_model.predict_proba(X_val)[:, 1]

    # === LightGBM (с early stopping) ===
    lgb_model = lgb.LGBMClassifier(**lgb_params)
    lgb_model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        eval_metric='auc',
        callbacks=[lgb.early_stopping(200, verbose=False)]
    )
    oof_lgb[val_idx] = lgb_model.predict_proba(X_val)[:, 1]

    # === XGBoost (с early stopping) ===
    xgb_model = xgb.XGBClassifier(**xgb_params)
    xgb_model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        verbose=False
    )
    oof_xgb[val_idx] = xgb_model.predict_proba(X_val)[:, 1]
    

stack_X = np.vstack([
    oof_cat,
    oof_lgb,
    oof_xgb
]).T

stack_oof = np.zeros(len(X))

for fold, (train_idx, val_idx) in enumerate(skf.split(stack_X, y)):
    print(f"\n===== META FOLD {fold} =====")

    X_train_meta, X_val_meta = stack_X[train_idx], stack_X[val_idx]
    y_train_meta, y_val_meta = y.iloc[train_idx], y.iloc[val_idx]

    meta_model = CatBoostClassifier(
        iterations=1000,
        depth=4,
        learning_rate=0.03,
        loss_function='Logloss',
        eval_metric='AUC',
        verbose=0
    )

    meta_model.fit(
        X_train_meta, y_train_meta,
        eval_set=(X_val_meta, y_val_meta),
        use_best_model=True
    )

    stack_oof[val_idx] = meta_model.predict_proba(X_val_meta)[:, 1]


print("OOF Cat AUC:", roc_auc_score(y, oof_cat))
print("OOF LGB AUC:", roc_auc_score(y, oof_lgb))
print("OOF XGB AUC:", roc_auc_score(y, oof_xgb))
print("STACKING AUC:", roc_auc_score(y, stack_oof))

===== FOLD 0 =====
0:	test: 0.6805462	best: 0.6805462 (0)	total: 759ms	remaining: 1h 3m 16s
200:	test: 0.7230387	best: 0.7230387 (200)	total: 2m 16s	remaining: 54m 10s
400:	test: 0.7295469	best: 0.7295469 (400)	total: 4m 36s	remaining: 52m 50s
600:	test: 0.7335819	best: 0.7335819 (600)	total: 6m 49s	remaining: 49m 56s
800:	test: 0.7358406	best: 0.7358413 (799)	total: 8m 59s	remaining: 47m 8s
1000:	test: 0.7368310	best: 0.7368310 (1000)	total: 11m 14s	remaining: 44m 53s
1200:	test: 0.7373757	best: 0.7373765 (1184)	total: 13m 29s	remaining: 42m 40s
1400:	test: 0.7377066	best: 0.7377066 (1400)	total: 15m 41s	remaining: 40m 17s
1600:	test: 0.7378976	best: 0.7379069 (1572)	total: 17m 55s	remaining: 38m 3s
1800:	test: 0.7379944	best: 0.7380362 (1771)	total: 20m 11s	remaining: 35m 52s
2000:	test: 0.7380065	best: 0.7380512 (1905)	total: 22m 22s	remaining: 33m 32s
2200:	test: 0.7379178	best: 0.7380976 (2081)	total: 24m 20s	remaining: 30m 57s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7380975752
bestIteration = 2081

Shrink model to first 2082 iterations.
[LightGBM] [Info] Number of positive: 85154, number of negative: 2314846
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.007037 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 18125
[LightGBM] [Info] Number of data points in the train set: 2400000, number of used features: 131
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500001 -> initscore=0.000005
[LightGBM] [Info] Start training from score 0.000005

===== FOLD 1 =====
0:	test: 0.6816077	best: 0.6816077 (0)	total: 606ms	remaining: 50m 27s
200:	test: 0.7213459	best: 0.7213459 (200)	total: 1m 55s	remaining: 46m 1s
400:	test: 0.7277925	best: 0.7277925 (400)	total: 3m 51s	remaining: 44m 14s
600:	test: 0.7315222	best: 0.7315222 (600)	total: 5m 48s	remaining: 42m 31s
800:	test: 0.7336436	best: 0.7336436 (800)	total: 7m 45s	remaining: 40m 42s
1000:	test: 0.7347262	best: 0.7347262 (1000)	total: 9m 41s	remaining: 38m 42s
1200:	test: 0.7353998	best: 0.7353998 (1200)	total: 11m 35s	remaining: 36m 38s
1400:	test: 0.7358473	best: 0.7358512 (1392)	total: 13m 28s	remaining: 34m 36s
1600:	test: 0.7361192	best: 0.7361399 (1582)	total: 15m 21s	remaining: 32m 36s
1800:	test: 0.7362267	best: 0.7362267 (1800)	total: 17m 15s	remaining: 30m 39s
2000:	test: 0.7361880	best: 0.7362435 (1876)	total: 19m 9s	remaining: 28m 43s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.736243544
bestIteration = 1876

Shrink model to first 1877 iterations.
[LightGBM] [Info] Number of positive: 85154, number of negative: 2314846
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.016947 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 18094
[LightGBM] [Info] Number of data points in the train set: 2400000, number of used features: 131
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500001 -> initscore=0.000005
[LightGBM] [Info] Start training from score 0.000005

===== FOLD 2 =====
0:	test: 0.6855610	best: 0.6855610 (0)	total: 649ms	remaining: 54m 3s
200:	test: 0.7278419	best: 0.7278419 (200)	total: 2m	remaining: 48m 2s
400:	test: 0.7340398	best: 0.7340398 (400)	total: 4m 10s	remaining: 47m 57s
600:	test: 0.7377002	best: 0.7377002 (600)	total: 6m 17s	remaining: 46m 4s
800:	test: 0.7395560	best: 0.7395560 (800)	total: 8m 19s	remaining: 43m 40s
1000:	test: 0.7405560	best: 0.7405560 (1000)	total: 10m 19s	remaining: 41m 15s
1200:	test: 0.7410277	best: 0.7410277 (1200)	total: 12m 17s	remaining: 38m 53s
1400:	test: 0.7415611	best: 0.7415736 (1391)	total: 14m 17s	remaining: 36m 43s
1600:	test: 0.7417160	best: 0.7417345 (1592)	total: 16m 17s	remaining: 34m 35s
1800:	test: 0.7417317	best: 0.7417530 (1714)	total: 18m 15s	remaining: 32m 25s
2000:	test: 0.7417171	best: 0.7418171 (1903)	total: 20m 9s	remaining: 30m 12s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7418171169
bestIteration = 1903

Shrink model to first 1904 iterations.
[LightGBM] [Info] Number of positive: 85154, number of negative: 2314846
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.028687 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 18121
[LightGBM] [Info] Number of data points in the train set: 2400000, number of used features: 131
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500001 -> initscore=0.000005
[LightGBM] [Info] Start training from score 0.000005

===== FOLD 3 =====
0:	test: 0.6807020	best: 0.6807020 (0)	total: 707ms	remaining: 58m 51s
200:	test: 0.7225922	best: 0.7225922 (200)	total: 2m 2s	remaining: 48m 39s
400:	test: 0.7292435	best: 0.7292435 (400)	total: 4m 4s	remaining: 46m 48s
600:	test: 0.7332124	best: 0.7332124 (600)	total: 6m 8s	remaining: 44m 58s
800:	test: 0.7354940	best: 0.7354940 (800)	total: 8m 11s	remaining: 42m 55s
1000:	test: 0.7367375	best: 0.7367379 (999)	total: 10m 15s	remaining: 40m 59s
1200:	test: 0.7373126	best: 0.7373126 (1200)	total: 12m 15s	remaining: 38m 46s
1400:	test: 0.7377612	best: 0.7377612 (1400)	total: 14m 25s	remaining: 37m 3s
1600:	test: 0.7379339	best: 0.7379485 (1559)	total: 16m 34s	remaining: 35m 10s
1800:	test: 0.7379033	best: 0.7379534 (1631)	total: 18m 34s	remaining: 32m 59s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7379533539
bestIteration = 1631

Shrink model to first 1632 iterations.
[LightGBM] [Info] Number of positive: 85153, number of negative: 2314847
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.009364 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 18147
[LightGBM] [Info] Number of data points in the train set: 2400000, number of used features: 131
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499998 -> initscore=-0.000007
[LightGBM] [Info] Start training from score -0.000007

===== FOLD 4 =====
0:	test: 0.6809443	best: 0.6809443 (0)	total: 602ms	remaining: 50m 10s
200:	test: 0.7235389	best: 0.7235389 (200)	total: 2m 1s	remaining: 48m 24s
400:	test: 0.7299677	best: 0.7299677 (400)	total: 4m 2s	remaining: 46m 22s
600:	test: 0.7337922	best: 0.7337922 (600)	total: 6m 5s	remaining: 44m 33s
800:	test: 0.7357800	best: 0.7357800 (800)	total: 8m 6s	remaining: 42m 28s
1000:	test: 0.7368831	best: 0.7368831 (1000)	total: 10m 7s	remaining: 40m 27s
1200:	test: 0.7376023	best: 0.7376023 (1200)	total: 12m 5s	remaining: 38m 15s
1400:	test: 0.7379476	best: 0.7380049 (1359)	total: 14m 3s	remaining: 36m 8s
1600:	test: 0.7381693	best: 0.7381693 (1600)	total: 16m 8s	remaining: 34m 15s
1800:	test: 0.7382757	best: 0.7383344 (1753)	total: 18m 23s	remaining: 32m 40s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7383343811
bestIteration = 1753

Shrink model to first 1754 iterations.
[LightGBM] [Info] Number of positive: 85153, number of negative: 2314847
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.171131 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 18051
[LightGBM] [Info] Number of data points in the train set: 2400000, number of used features: 131
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499998 -> initscore=-0.000007
[LightGBM] [Info] Start training from score -0.000007

===== META FOLD 0 =====

===== META FOLD 1 =====

===== META FOLD 2 =====

===== META FOLD 3 =====

===== META FOLD 4 =====
OOF Cat AUC: 0.7384742627612181
OOF LGB AUC: 0.7373023636162136
OOF XGB AUC: 0.7384973921546917
STACKING AUC: 0.7394439187662235

In [26]:
print(np.corrcoef(oof_cat, oof_xgb))
print(np.corrcoef(oof_cat, oof_lgb))
print(np.corrcoef(oof_xgb, oof_lgb))

[[1.         0.98285169]
 [0.98285169 1.        ]]
[[1.         0.97956222]
 [0.97956222 1.        ]]
[[1.         0.98583012]
 [0.98583012 1.        ]]

## feature importance

In [28]:
cat_model = CatBoostClassifier(**cat_params)
cat_model.fit(X, y, verbose=200)

fi = pd.DataFrame({
    "feature": X.columns,
    "importance": cat_model.get_feature_importance()
}).sort_values("importance", ascending=False)

0:	total: 909ms	remaining: 1h 15m 43s
200:	total: 2m 38s	remaining: 1h 3m 13s
400:	total: 5m 36s	remaining: 1h 4m 17s
600:	total: 8m 32s	remaining: 1h 2m 30s
800:	total: 11m 12s	remaining: 58m 42s
1000:	total: 13m 41s	remaining: 54m 43s
1200:	total: 16m 3s	remaining: 50m 48s
1400:	total: 18m 25s	remaining: 47m 20s
1600:	total: 20m 55s	remaining: 44m 24s
1800:	total: 23m 16s	remaining: 41m 20s
2000:	total: 25m 39s	remaining: 38m 27s
2200:	total: 28m 6s	remaining: 35m 44s
2400:	total: 30m 36s	remaining: 33m 7s
2600:	total: 33m 25s	remaining: 30m 49s
2800:	total: 36m 16s	remaining: 28m 28s
3000:	total: 39m 5s	remaining: 26m 2s
3200:	total: 41m 48s	remaining: 23m 30s
3400:	total: 44m 29s	remaining: 20m 54s
3600:	total: 47m 25s	remaining: 18m 25s
3800:	total: 49m 57s	remaining: 15m 45s
4000:	total: 52m 12s	remaining: 13m 2s
4200:	total: 54m 28s	remaining: 10m 21s
4400:	total: 56m 44s	remaining: 7m 43s
4600:	total: 59m 6s	remaining: 5m 7s
4800:	total: 1h 1m 22s	remaining: 2m 32s
4999:	total: 1h 3m 38s	remaining: 0us

In [30]:
fi.head(10)

                             feature  importance
123               bad_to_total_ratio    4.132404
23   pre_loans_credit_cost_rate_mean    2.707723
21        pre_loans_outstanding_mean    2.704404
39                 is_zero_util_mean    2.509935
30             is_zero_loans530_mean    2.420276
114              client_util_std_max    2.024737
18      pre_loans_next_pay_summ_mean    1.877560
16        pre_loans_credit_limit_max    1.877338
8                     pre_pterm_mean    1.852799
35                     pre_util_mean    1.832878

In [31]:
feature_auc = []

for col in X.columns:
    vals = X[col].values

    mask = np.isfinite(vals)
    if mask.sum() == 0:
        auc = 0.5
    else:
        try:
            auc = roc_auc_score(y[mask], vals[mask])
        except:
            auc = 0.5

    auc = max(auc, 1 - auc)

    feature_auc.append((col, auc))

df_auc = pd.DataFrame(feature_auc, columns=["feature", "auc"])

df_full = df_auc.merge(fi, on="feature", how="left")

df_full = df_full.sort_values("importance", ascending=False)

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

print(df_full)

                                   feature       auc  importance
123                     bad_to_total_ratio  0.657572    4.132404
23         pre_loans_credit_cost_rate_mean  0.504334    2.707723
21              pre_loans_outstanding_mean  0.534555    2.704404
39                       is_zero_util_mean  0.566654    2.509935
30                   is_zero_loans530_mean  0.571349    2.420276
114                    client_util_std_max  0.549568    2.024737
18            pre_loans_next_pay_summ_mean  0.506952    1.877560
16              pre_loans_credit_limit_max  0.505961    1.877338
8                           pre_pterm_mean  0.514604    1.852799
35                           pre_util_mean  0.558690    1.832878
120                          util_per_loan  0.567389    1.817325
11                          pre_fterm_mean  0.518798    1.808169
111              max_utilization_ratio_max  0.546079    1.807023
110             mean_utilization_ratio_max  0.543065    1.728997
2                    pre_since_opened_mean  0.522554    1.682003
17             pre_loans_credit_limit_mean  0.536724    1.655874
20               pre_loans_outstanding_max  0.528906    1.652737
121                         util_stability  0.534792    1.593358
116                   recent_bad_ratio_max  0.603630    1.563290
46                        pclose_flag_mean  0.503696    1.514195
5                 pre_since_confirmed_mean  0.511116    1.406996
36                            pre_util_max  0.503425    1.393858
47                        fclose_flag_mean  0.520052    1.302312
19             pre_loans_next_pay_summ_max  0.512983    1.300286
13                     pre_till_pclose_max  0.534783    1.288685
44           enc_loans_credit_type_nunique  0.540463    1.279739
14                     pre_till_fclose_min  0.539871    1.261012
115                   max_credit_share_max  0.526724    1.233763
28                     is_zero_loans5_mean  0.536416    1.229046
1                     pre_since_opened_max  0.509650    1.130220
6                            pre_pterm_min  0.536007    1.114819
126                          recent_vs_old  0.534709    1.100668
32                  is_zero_loans3060_mean  0.561711    1.056316
12                     pre_till_pclose_min  0.537340    1.010393
7                            pre_pterm_max  0.537983    1.004813
127                    recent_vs_old_early  0.502920    0.956056
40                 is_zero_over2limit_mean  0.506891    0.953662
55                         enc_paym_2_mean  0.603623    0.943714
31                    is_zero_loans530_sum  0.560889    0.931333
0                     pre_since_opened_min  0.548200    0.930741
41              is_zero_maxover2limit_mean  0.540373    0.921381
52                         enc_paym_1_mean  0.601438    0.908024
15                     pre_till_fclose_max  0.525272    0.840899
42   enc_loans_account_holder_type_nunique  0.517660    0.840846
3                  pre_since_confirmed_min  0.513265    0.818879
34                    is_zero_loans90_mean  0.547308    0.807713
131                           last_vs_mean  0.544694    0.803727
9                            pre_fterm_min  0.535720    0.787603
101                       enc_paym_23_mean  0.580759    0.770569
58                         enc_paym_3_mean  0.604221    0.714465
4                  pre_since_confirmed_max  0.527252    0.697342
67                         enc_paym_6_mean  0.595305    0.664289
25                        pre_loans530_sum  0.535686    0.652610
29                      is_zero_loans5_sum  0.543351    0.628584
10                           pre_fterm_max  0.540958    0.620939
64                         enc_paym_5_mean  0.598777    0.603241
73                         enc_paym_9_mean  0.592704    0.603186
128                               paym_std  0.527669    0.590775
71                         enc_paym_8_mean  0.593371    0.582436
97                        enc_paym_21_mean  0.584146    0.553196
118                decayed_paym_score_mean  0.622662    0.548900
61                         enc_paym_4_mean  0.601843    0.529570
77                        enc_paym_11_mean  0.589282    0.524278
112                   last_paym_status_max  0.542167    0.521172
22           pre_loans_max_overdue_sum_max  0.514897    0.510477
99                        enc_paym_22_mean  0.582374    0.500638
33                  is_zero_loans6090_mean  0.549696    0.500540
43         enc_loans_credit_status_nunique  0.517579    0.471654
81                        enc_paym_13_mean  0.589891    0.444721
83                        enc_paym_14_mean  0.590390    0.441287
37                      pre_over2limit_max  0.501940    0.440450
122                          paym_trend_lr  0.506276    0.438634
49                         enc_paym_0_mean  0.572855    0.437435
78                         enc_paym_11_sum  0.511487    0.435020
85                        enc_paym_15_mean  0.590589    0.430634
104          client_mean_severe_bad_months  0.608774    0.429241
79                        enc_paym_12_mean  0.588315    0.428306
124                         paym_trend_abs  0.506813    0.421661
74                          enc_paym_9_sum  0.511917    0.414093
69                         enc_paym_7_mean  0.594183    0.411167
103     client_mean_bad_months_per_product  0.636035    0.409381
56                          enc_paym_2_sum  0.565492    0.398669
50                          enc_paym_0_sum  0.562994    0.396377
89                        enc_paym_17_mean  0.589158    0.376750
129                        worst_paym_ever  0.588791    0.368011
96                         enc_paym_20_sum  0.519476    0.363590
105         client_mean_nonzero_paym_share  0.636035    0.361005
59                          enc_paym_3_sum  0.556406    0.359476
76                         enc_paym_10_sum  0.506667    0.353993
68                          enc_paym_6_sum  0.526964    0.352877
100                        enc_paym_22_sum  0.514159    0.352338
75                        enc_paym_10_mean  0.590031    0.352324
87                        enc_paym_16_mean  0.590182    0.350899
65                          enc_paym_5_sum  0.536896    0.347282
53                          enc_paym_1_sum  0.572804    0.341248
102                        enc_paym_23_sum  0.515293    0.340009
119                 decayed_paym_score_max  0.545290    0.334798
70                          enc_paym_7_sum  0.520311    0.330108
62                          enc_paym_4_sum  0.545887    0.329870
90                         enc_paym_17_sum  0.507988    0.323366
108         client_max_weighted_paym_score  0.539896    0.309104
94                         enc_paym_19_sum  0.510516    0.297618
48                          enc_paym_0_max  0.555560    0.292528
95                        enc_paym_20_mean  0.585861    0.290100
91                        enc_paym_18_mean  0.588268    0.288806
24                          pre_loans5_sum  0.535320    0.285716
82                         enc_paym_13_sum  0.503181    0.284393
93                        enc_paym_19_mean  0.587206    0.280280
84                         enc_paym_14_sum  0.504388    0.268180
80                         enc_paym_12_sum  0.501019    0.266764
72                          enc_paym_8_sum  0.515817    0.239697
106                client_mean_paym_status  0.615411    0.223970
51                          enc_paym_1_max  0.554150    0.222875
88                         enc_paym_16_sum  0.506720    0.221755
117                  client_worst_loan_max  0.550237    0.217170
130                          paym_switches  0.544528    0.216861
86                         enc_paym_15_sum  0.505523    0.203943
92                         enc_paym_18_sum  0.509292    0.201441
45           enc_loans_account_cur_nunique  0.503947    0.186244
107        client_mean_weighted_paym_score  0.615413    0.173325
98                         enc_paym_21_sum  0.512969    0.172655
26                        pre_loans530_max  0.500735    0.124084
27                       pre_loans3060_max  0.503194    0.092868
109              client_products_count_max  0.534108    0.066284
38                   pre_maxover2limit_max  0.503040    0.058945
54                          enc_paym_2_max  0.542854    0.027101
63                          enc_paym_5_max  0.520548    0.021044
57                          enc_paym_3_max  0.534197    0.018480
60                          enc_paym_4_max  0.526376    0.017770
66                          enc_paym_6_max  0.515378    0.005593
113              client_bad_loan_ratio_max  0.500000    0.000000
125                         last_bad_month  0.506282    0.000000

## modeling 23.03

### ансамбль на разных наборах данных

#### списки фич

In [7]:
xgb_features = [
    # --- core payment behavior ---
    "enc_paym_0_mean", "enc_paym_1_mean", "enc_paym_2_mean", "enc_paym_3_mean",
    "enc_paym_4_mean", "enc_paym_5_mean", "enc_paym_6_mean", "enc_paym_7_mean",
    "enc_paym_8_mean", "enc_paym_9_mean", "enc_paym_10_mean", "enc_paym_11_mean",
    "enc_paym_12_mean", "enc_paym_13_mean", "enc_paym_14_mean", "enc_paym_15_mean",
    "enc_paym_16_mean", "enc_paym_17_mean", "enc_paym_18_mean", "enc_paym_19_mean",
    "enc_paym_20_mean", "enc_paym_21_mean", "enc_paym_22_mean", "enc_paym_23_mean",

    # --- sums (динамика накопления) ---
    "enc_paym_0_sum", "enc_paym_1_sum", "enc_paym_2_sum", "enc_paym_3_sum",
    "enc_paym_4_sum", "enc_paym_5_sum", "enc_paym_6_sum", "enc_paym_7_sum",
    "enc_paym_8_sum", "enc_paym_9_sum", "enc_paym_10_sum", "enc_paym_11_sum",
    "enc_paym_19_sum", "enc_paym_20_sum", "enc_paym_21_sum", "enc_paym_22_sum",
    "enc_paym_23_sum",

    # --- max (локальные пики поведения) ---
    "enc_paym_0_max", "enc_paym_1_max",

    # --- aggregated behavioral features ---
    "client_mean_bad_months_per_product",
    "client_mean_nonzero_paym_share",
    "client_mean_weighted_paym_score",
    "client_mean_paym_status",
    "client_mean_severe_bad_months",
    "client_max_weighted_paym_score",
    "client_worst_loan_max",

    # --- advanced behavior ---
    "recent_bad_ratio_max",
    "decayed_paym_score_mean",
    "decayed_paym_score_max",
    "worst_paym_ever",

    # --- dynamics ---
    "paym_std",
    "paym_switches",
    "paym_trend_lr",
    "paym_trend_abs",

    # --- relative behavior ---
    "recent_vs_old",
    "recent_vs_old_early",
    "last_vs_mean"
]

lgb_features = [
    # --- core ratios / meta ---
    "bad_to_total_ratio",
    "util_per_loan",
    "util_stability",

    # --- credit structure ---
    "pre_loans_credit_cost_rate_mean",
    "pre_loans_outstanding_mean",
    "pre_loans_outstanding_max",
    "pre_loans_credit_limit_mean",
    "pre_loans_credit_limit_max",
    "pre_loans_next_pay_summ_mean",
    "pre_loans_next_pay_summ_max",
    "pre_loans_max_overdue_sum_max",

    # --- time-related credit features ---
    "pre_since_opened_min",
    "pre_since_opened_max",
    "pre_since_opened_mean",
    "pre_since_confirmed_min",
    "pre_since_confirmed_max",
    "pre_since_confirmed_mean",

    "pre_pterm_min",
    "pre_pterm_max",
    "pre_pterm_mean",
    "pre_fterm_min",
    "pre_fterm_max",
    "pre_fterm_mean",

    "pre_till_pclose_min",
    "pre_till_pclose_max",
    "pre_till_fclose_min",
    "pre_till_fclose_max",

    # --- utilization ---
    "pre_util_mean",
    "pre_util_max",
    "mean_utilization_ratio_max",
    "max_utilization_ratio_max",
    "client_util_std_max",

    # --- flags ---
    "pclose_flag_mean",
    "fclose_flag_mean",

    # --- categorical diversity ---
    "enc_loans_credit_type_nunique",
    "enc_loans_account_holder_type_nunique",
    "enc_loans_credit_status_nunique",
    "enc_loans_account_cur_nunique",

    # --- loan counts ---
    "pre_loans5_sum",
    "pre_loans530_sum",

    # --- zero indicators ---
    "is_zero_util_mean",
    "is_zero_loans5_mean",
    "is_zero_loans5_sum",
    "is_zero_loans530_mean",
    "is_zero_loans530_sum",
    "is_zero_loans3060_mean",
    "is_zero_loans6090_mean",
    "is_zero_loans90_mean",

    "is_zero_over2limit_mean",
    "is_zero_maxover2limit_mean",

    # --- limits ---
    "pre_over2limit_max",

    # --- client level ---
    "max_credit_share_max",
    "client_products_count_max",

    # --- misc ---
    "last_paym_status_max"
]

#### модель

In [8]:
cat_params = {
    'iterations': 3000,
    'depth': 8,
    'learning_rate': 0.03,
    'l2_leaf_reg': 7,
    'loss_function': 'Logloss',
    'eval_metric': 'AUC',
    'class_weights': class_weights_dict,
    'early_stopping_rounds': 200,
    'verbose': 200
}

lgb_params = {
    'n_estimators': 5000,
    'num_leaves': 31,
    'colsample_bytree': 0.7,
    'min_child_samples': 50,
    'subsample': 0.7,
    'learning_rate': 0.03,
    'max_depth': -1,
    'random_state': 42,
    'class_weight': class_weights_dict,
    'verbosity': -1
}

pos_weight = class_weights_dict[1] / class_weights_dict[0]
xgb_params = {
    'n_estimators': 5000,
    'learning_rate': 0.03,
    'max_depth': 6,
    'reg_lambda': 10,
    'reg_alpha': 0,
    'subsample': 0.8,
    'colsample_bytree': 0.8,
    'eval_metric': 'auc',
    'random_state': 42,
    'scale_pos_weight': pos_weight,
    'early_stopping_rounds': 200,
    'verbosity': 1
}

In [9]:
X = data.drop(['flag', 'id'], axis=1)
X_lgb = data[lgb_features]
X_xgb = data[xgb_features]

y = data["flag"]

X_np = X.to_numpy(dtype=np.float32)
X_lgb_np = X_lgb.to_numpy(dtype=np.float32)
X_xgb_np = X_xgb.to_numpy(dtype=np.float32)
y_np = y.to_numpy(dtype=np.int8)

print(set(lgb_features) & set(xgb_features))

print(X_lgb.shape)
print(X_xgb.shape)

set()
(3000000, 54)
(3000000, 61)

In [16]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

oof_cat = np.zeros(len(X))
oof_lgb = np.zeros(len(X))
oof_xgb = np.zeros(len(X))

cat_models_auc = []
lgb_models_auc = []
xgb_models_auc = []

for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):
    print(f"\n========== FOLD {fold} ==========")

    X_train, X_val = X_np[train_idx], X_np[val_idx]
    X_train_lgb, X_val_lgb = X_lgb_np[train_idx], X_lgb_np[val_idx]
    X_train_xgb, X_val_xgb = X_xgb_np[train_idx], X_xgb_np[val_idx]
    y_train, y_val = y_np[train_idx], y_np[val_idx]

    # ===== Обработка inf =====
    for arr_train, arr_val in [(X_train, X_val), (X_train_lgb, X_val_lgb), (X_train_xgb, X_val_xgb)]:
        for i in range(arr_train.shape[1]):
            col_train = arr_train[:, i]
            col_val = arr_val[:, i]

            median_val = np.nanmedian(col_train[np.isfinite(col_train)])

            col_train[~np.isfinite(col_train)] = median_val
            col_val[~np.isfinite(col_val)] = median_val

    # ===== CatBoost =====
    cat_model = CatBoostClassifier(**cat_params)
    cat_model.fit(
        X_train, y_train,
        eval_set=(X_val, y_val),
        use_best_model=True,
        verbose=200
    )

    oof_cat[val_idx] = cat_model.predict_proba(X_val)[:, 1]
    auc_cat = roc_auc_score(y_val, oof_cat[val_idx])
    best_iter_cat = cat_model.get_best_iteration()

    print(f"[CatBoost]  AUC: {auc_cat:.6f} | best_iter: {best_iter_cat}")

    cat_models_auc.append((auc_cat, cat_model))

    # ===== LightGBM =====
    lgb_model = lgb.LGBMClassifier(**lgb_params)
    lgb_model.fit(
        X_train_lgb, y_train,
        eval_set=[(X_val_lgb, y_val)],
        eval_metric='auc',
        callbacks=[
            lgb.early_stopping(200),
            lgb.log_evaluation(200)
        ]
    )

    oof_lgb[val_idx] = lgb_model.predict_proba(X_val_lgb)[:, 1]
    auc_lgb = roc_auc_score(y_val, oof_lgb[val_idx])
    best_iter_lgb = lgb_model.best_iteration_

    print(f"[LightGBM] AUC: {auc_lgb:.6f} | best_iter: {best_iter_lgb}")

    lgb_models_auc.append((auc_lgb, lgb_model))

    # ===== XGBoost =====
    xgb_model = xgb.XGBClassifier(**xgb_params)
    xgb_model.fit(
        X_train_xgb, y_train,
        eval_set=[(X_val_xgb, y_val)],
        verbose=200
    )

    oof_xgb[val_idx] = xgb_model.predict_proba(X_val_xgb)[:, 1]
    auc_xgb = roc_auc_score(y_val, oof_xgb[val_idx])
    best_iter_xgb = xgb_model.best_iteration

    print(f"[XGBoost]  AUC: {auc_xgb:.6f} | best_iter: {best_iter_xgb}")

    xgb_models_auc.append((auc_xgb, xgb_model))


print("\n========== OOF RESULTS ==========")
print("CatBoost AUC:", roc_auc_score(y, oof_cat))
print("LightGBM AUC:", roc_auc_score(y, oof_lgb))
print("XGBoost AUC:", roc_auc_score(y, oof_xgb))


# ===== STACKING =====
stack_X = np.vstack([oof_cat, oof_lgb, oof_xgb]).T
stack_oof = np.zeros(len(X))

for fold, (train_idx, val_idx) in enumerate(skf.split(stack_X, y)):
    print(f"\n===== META FOLD {fold} =====")

    X_train_meta, X_val_meta = stack_X[train_idx], stack_X[val_idx]
    y_train_meta, y_val_meta = y.iloc[train_idx], y.iloc[val_idx]

    meta_model = CatBoostClassifier(
        iterations=1000,
        depth=4,
        learning_rate=0.03,
        loss_function='Logloss',
        eval_metric='AUC',
        verbose=200
    )

    meta_model.fit(
        X_train_meta, y_train_meta,
        eval_set=(X_val_meta, y_val_meta),
        use_best_model=True
    )

    stack_oof[val_idx] = meta_model.predict_proba(X_val_meta)[:, 1]
    auc_meta = roc_auc_score(y_val_meta, stack_oof[val_idx])

    print(f"[META] AUC: {auc_meta:.6f}")


print("\n========== FINAL ==========")
print("STACKING AUC:", roc_auc_score(y, stack_oof))

========== FOLD 0 ==========
0:	test: 0.6834537	best: 0.6834537 (0)	total: 714ms	remaining: 35m 40s
200:	test: 0.7231019	best: 0.7231019 (200)	total: 1m 49s	remaining: 25m 20s
400:	test: 0.7297244	best: 0.7297244 (400)	total: 3m 38s	remaining: 23m 36s
600:	test: 0.7336456	best: 0.7336456 (600)	total: 5m 28s	remaining: 21m 51s
800:	test: 0.7356999	best: 0.7356999 (800)	total: 7m 19s	remaining: 20m 6s
1000:	test: 0.7366919	best: 0.7366919 (1000)	total: 9m 9s	remaining: 18m 17s
1200:	test: 0.7373700	best: 0.7373700 (1200)	total: 10m 59s	remaining: 16m 27s
1400:	test: 0.7378742	best: 0.7378786 (1398)	total: 12m 49s	remaining: 14m 38s
1600:	test: 0.7380361	best: 0.7380653 (1587)	total: 14m 39s	remaining: 12m 48s
1800:	test: 0.7379986	best: 0.7380893 (1726)	total: 16m 30s	remaining: 10m 59s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7380893298
bestIteration = 1726

Shrink model to first 1727 iterations.
[CatBoost]  AUC: 0.738089 | best_iter: 1726
Training until validation scores don't improve for 200 rounds
[200]	valid_0's auc: 0.725595	valid_0's binary_logloss: 0.610622
[400]	valid_0's auc: 0.731407	valid_0's binary_logloss: 0.602589
[600]	valid_0's auc: 0.732876	valid_0's binary_logloss: 0.598072
[800]	valid_0's auc: 0.733797	valid_0's binary_logloss: 0.594102
[1000]	valid_0's auc: 0.734326	valid_0's binary_logloss: 0.59048
[1200]	valid_0's auc: 0.734762	valid_0's binary_logloss: 0.587001
[1400]	valid_0's auc: 0.734967	valid_0's binary_logloss: 0.583779
[1600]	valid_0's auc: 0.735227	valid_0's binary_logloss: 0.580645
[1800]	valid_0's auc: 0.735289	valid_0's binary_logloss: 0.577684
[2000]	valid_0's auc: 0.735287	valid_0's binary_logloss: 0.574747
[2200]	valid_0's auc: 0.73517	valid_0's binary_logloss: 0.571892
Early stopping, best iteration is:
[2043]	valid_0's auc: 0.735313	valid_0's binary_logloss: 0.574135

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] AUC: 0.735313 | best_iter: 2043
[0]	validation_0-auc:0.65911
[200]	validation_0-auc:0.67886
[400]	validation_0-auc:0.67936
[600]	validation_0-auc:0.67926
[656]	validation_0-auc:0.67908
[XGBoost]  AUC: 0.679438 | best_iter: 456

========== FOLD 1 ==========
0:	test: 0.6810752	best: 0.6810752 (0)	total: 578ms	remaining: 28m 53s
200:	test: 0.7215847	best: 0.7215847 (200)	total: 1m 53s	remaining: 26m 15s
400:	test: 0.7281368	best: 0.7281368 (400)	total: 3m 46s	remaining: 24m 26s
600:	test: 0.7319052	best: 0.7319052 (600)	total: 5m 39s	remaining: 22m 33s
800:	test: 0.7339128	best: 0.7339198 (799)	total: 7m 31s	remaining: 20m 39s
1000:	test: 0.7349123	best: 0.7349123 (1000)	total: 9m 21s	remaining: 18m 41s
1200:	test: 0.7354124	best: 0.7354348 (1166)	total: 11m 13s	remaining: 16m 48s
1400:	test: 0.7357615	best: 0.7357623 (1399)	total: 13m 2s	remaining: 14m 53s
1600:	test: 0.7360310	best: 0.7360310 (1600)	total: 14m 53s	remaining: 13m 1s
1800:	test: 0.7361526	best: 0.7361560 (1787)	total: 16m 44s	remaining: 11m 8s
2000:	test: 0.7362519	best: 0.7362822 (1968)	total: 18m 34s	remaining: 9m 16s
2200:	test: 0.7361853	best: 0.7362902 (2019)	total: 20m 25s	remaining: 7m 24s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7362902408
bestIteration = 2019

Shrink model to first 2020 iterations.
[CatBoost]  AUC: 0.736290 | best_iter: 2019
Training until validation scores don't improve for 200 rounds
[200]	valid_0's auc: 0.72373	valid_0's binary_logloss: 0.610227
[400]	valid_0's auc: 0.72926	valid_0's binary_logloss: 0.602306
[600]	valid_0's auc: 0.730614	valid_0's binary_logloss: 0.597722
[800]	valid_0's auc: 0.731391	valid_0's binary_logloss: 0.593763
[1000]	valid_0's auc: 0.731818	valid_0's binary_logloss: 0.590111
[1200]	valid_0's auc: 0.732261	valid_0's binary_logloss: 0.586611
[1400]	valid_0's auc: 0.732422	valid_0's binary_logloss: 0.583303
[1600]	valid_0's auc: 0.732463	valid_0's binary_logloss: 0.580181
[1800]	valid_0's auc: 0.732509	valid_0's binary_logloss: 0.577131
Early stopping, best iteration is:
[1749]	valid_0's auc: 0.732554	valid_0's binary_logloss: 0.577857

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] AUC: 0.732554 | best_iter: 1749
[0]	validation_0-auc:0.65838
[200]	validation_0-auc:0.67890
[400]	validation_0-auc:0.67966
[600]	validation_0-auc:0.67971
[738]	validation_0-auc:0.67951
[XGBoost]  AUC: 0.679792 | best_iter: 538

========== FOLD 2 ==========
0:	test: 0.6888447	best: 0.6888447 (0)	total: 560ms	remaining: 28m
200:	test: 0.7282154	best: 0.7282154 (200)	total: 1m 54s	remaining: 26m 35s
400:	test: 0.7342952	best: 0.7342952 (400)	total: 3m 53s	remaining: 25m 13s
600:	test: 0.7377291	best: 0.7377291 (600)	total: 5m 50s	remaining: 23m 19s
800:	test: 0.7395938	best: 0.7395938 (800)	total: 7m 46s	remaining: 21m 21s
1000:	test: 0.7404211	best: 0.7404211 (1000)	total: 9m 45s	remaining: 19m 28s
1200:	test: 0.7408593	best: 0.7408599 (1199)	total: 11m 37s	remaining: 17m 25s
1400:	test: 0.7412992	best: 0.7413009 (1398)	total: 13m 32s	remaining: 15m 27s
1600:	test: 0.7413864	best: 0.7413959 (1537)	total: 15m 25s	remaining: 13m 28s
1800:	test: 0.7414234	best: 0.7414234 (1800)	total: 17m 18s	remaining: 11m 31s
2000:	test: 0.7412939	best: 0.7414234 (1800)	total: 19m 10s	remaining: 9m 34s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7414233798
bestIteration = 1800

Shrink model to first 1801 iterations.
[CatBoost]  AUC: 0.741423 | best_iter: 1800
Training until validation scores don't improve for 200 rounds
[200]	valid_0's auc: 0.729784	valid_0's binary_logloss: 0.61212
[400]	valid_0's auc: 0.735254	valid_0's binary_logloss: 0.604216
[600]	valid_0's auc: 0.736783	valid_0's binary_logloss: 0.59964
[800]	valid_0's auc: 0.73752	valid_0's binary_logloss: 0.595734
[1000]	valid_0's auc: 0.738035	valid_0's binary_logloss: 0.592135
[1200]	valid_0's auc: 0.738358	valid_0's binary_logloss: 0.58872
[1400]	valid_0's auc: 0.738471	valid_0's binary_logloss: 0.58553
[1600]	valid_0's auc: 0.738486	valid_0's binary_logloss: 0.582376
[1800]	valid_0's auc: 0.738531	valid_0's binary_logloss: 0.579349
Early stopping, best iteration is:
[1743]	valid_0's auc: 0.73859	valid_0's binary_logloss: 0.580177

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] AUC: 0.738590 | best_iter: 1743
[0]	validation_0-auc:0.66322
[200]	validation_0-auc:0.68189
[400]	validation_0-auc:0.68248
[600]	validation_0-auc:0.68238
[613]	validation_0-auc:0.68233
[XGBoost]  AUC: 0.682544 | best_iter: 413

========== FOLD 3 ==========
0:	test: 0.6814706	best: 0.6814706 (0)	total: 566ms	remaining: 28m 16s
200:	test: 0.7226057	best: 0.7226057 (200)	total: 1m 52s	remaining: 26m 2s
400:	test: 0.7293950	best: 0.7293950 (400)	total: 3m 44s	remaining: 24m 15s
600:	test: 0.7334452	best: 0.7334452 (600)	total: 5m 38s	remaining: 22m 31s
800:	test: 0.7356744	best: 0.7356744 (800)	total: 7m 30s	remaining: 20m 37s
1000:	test: 0.7368393	best: 0.7368393 (1000)	total: 9m 21s	remaining: 18m 40s
1200:	test: 0.7374594	best: 0.7374594 (1200)	total: 11m 13s	remaining: 16m 48s
1400:	test: 0.7377014	best: 0.7377014 (1400)	total: 13m 1s	remaining: 14m 51s
1600:	test: 0.7378732	best: 0.7378841 (1551)	total: 14m 53s	remaining: 13m
1800:	test: 0.7379071	best: 0.7379181 (1620)	total: 16m 42s	remaining: 11m 7s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7379181441
bestIteration = 1620

Shrink model to first 1621 iterations.
[CatBoost]  AUC: 0.737918 | best_iter: 1620
Training until validation scores don't improve for 200 rounds
[200]	valid_0's auc: 0.725091	valid_0's binary_logloss: 0.610077
[400]	valid_0's auc: 0.730954	valid_0's binary_logloss: 0.602297
[600]	valid_0's auc: 0.732746	valid_0's binary_logloss: 0.597623
[800]	valid_0's auc: 0.733773	valid_0's binary_logloss: 0.593587
[1000]	valid_0's auc: 0.734304	valid_0's binary_logloss: 0.589986
[1200]	valid_0's auc: 0.734683	valid_0's binary_logloss: 0.586584
[1400]	valid_0's auc: 0.734853	valid_0's binary_logloss: 0.583356
[1600]	valid_0's auc: 0.734816	valid_0's binary_logloss: 0.580232
Early stopping, best iteration is:
[1401]	valid_0's auc: 0.734857	valid_0's binary_logloss: 0.583339

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] AUC: 0.734857 | best_iter: 1401
[0]	validation_0-auc:0.65701
[200]	validation_0-auc:0.67700
[400]	validation_0-auc:0.67753
[600]	validation_0-auc:0.67727
[608]	validation_0-auc:0.67730
[XGBoost]  AUC: 0.677578 | best_iter: 408

========== FOLD 4 ==========
0:	test: 0.6828252	best: 0.6828252 (0)	total: 536ms	remaining: 26m 46s
200:	test: 0.7233731	best: 0.7233731 (200)	total: 1m 52s	remaining: 26m 4s
400:	test: 0.7297631	best: 0.7297631 (400)	total: 3m 45s	remaining: 24m 22s
600:	test: 0.7337004	best: 0.7337004 (600)	total: 5m 39s	remaining: 22m 35s
800:	test: 0.7357986	best: 0.7357986 (800)	total: 7m 31s	remaining: 20m 38s
1000:	test: 0.7369424	best: 0.7369424 (1000)	total: 9m 22s	remaining: 18m 43s
1200:	test: 0.7376149	best: 0.7376149 (1200)	total: 11m 14s	remaining: 16m 50s
1400:	test: 0.7380087	best: 0.7380087 (1400)	total: 13m 4s	remaining: 14m 55s
1600:	test: 0.7381566	best: 0.7381613 (1599)	total: 14m 57s	remaining: 13m 3s
1800:	test: 0.7382060	best: 0.7382717 (1709)	total: 16m 55s	remaining: 11m 16s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7382716879
bestIteration = 1709

Shrink model to first 1710 iterations.
[CatBoost]  AUC: 0.738272 | best_iter: 1709
Training until validation scores don't improve for 200 rounds
[200]	valid_0's auc: 0.726078	valid_0's binary_logloss: 0.61057
[400]	valid_0's auc: 0.731577	valid_0's binary_logloss: 0.602732
[600]	valid_0's auc: 0.733189	valid_0's binary_logloss: 0.598135
[800]	valid_0's auc: 0.734131	valid_0's binary_logloss: 0.594097
[1000]	valid_0's auc: 0.734808	valid_0's binary_logloss: 0.590407
[1200]	valid_0's auc: 0.735226	valid_0's binary_logloss: 0.58696
[1400]	valid_0's auc: 0.735637	valid_0's binary_logloss: 0.583664
[1600]	valid_0's auc: 0.735854	valid_0's binary_logloss: 0.58044
[1800]	valid_0's auc: 0.735909	valid_0's binary_logloss: 0.577434
[2000]	valid_0's auc: 0.736022	valid_0's binary_logloss: 0.574428
[2200]	valid_0's auc: 0.736089	valid_0's binary_logloss: 0.571484
[2400]	valid_0's auc: 0.736159	valid_0's binary_logloss: 0.568635
[2600]	valid_0's auc: 0.736149	valid_0's binary_logloss: 0.56586
Early stopping, best iteration is:
[2495]	valid_0's auc: 0.7362	valid_0's binary_logloss: 0.567281

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] AUC: 0.736200 | best_iter: 2495
[0]	validation_0-auc:0.65780
[200]	validation_0-auc:0.67922
[400]	validation_0-auc:0.68000
[600]	validation_0-auc:0.67991
[672]	validation_0-auc:0.67979
[XGBoost]  AUC: 0.680077 | best_iter: 472

========== OOF RESULTS ==========
CatBoost AUC: 0.7383799287438716
LightGBM AUC: 0.735461521776563
XGBoost AUC: 0.6798668074956296

===== META FOLD 0 =====
0:	test: 0.7185058	best: 0.7185058 (0)	total: 196ms	remaining: 3m 16s
200:	test: 0.7386652	best: 0.7386652 (200)	total: 37.4s	remaining: 2m 28s
400:	test: 0.7387962	best: 0.7387979 (378)	total: 1m 14s	remaining: 1m 50s
600:	test: 0.7388186	best: 0.7388254 (543)	total: 1m 50s	remaining: 1m 13s
800:	test: 0.7388164	best: 0.7388260 (668)	total: 2m 28s	remaining: 36.9s
999:	test: 0.7387874	best: 0.7388260 (668)	total: 3m 5s	remaining: 0us

bestTest = 0.7388260252
bestIteration = 668

Shrink model to first 669 iterations.
[META] AUC: 0.738826

===== META FOLD 1 =====
0:	test: 0.7169945	best: 0.7169945 (0)	total: 188ms	remaining: 3m 7s
200:	test: 0.7367565	best: 0.7367565 (200)	total: 37.6s	remaining: 2m 29s
400:	test: 0.7368311	best: 0.7368317 (399)	total: 1m 14s	remaining: 1m 50s
600:	test: 0.7368315	best: 0.7368368 (506)	total: 1m 50s	remaining: 1m 13s
800:	test: 0.7368256	best: 0.7368517 (695)	total: 2m 28s	remaining: 36.8s
999:	test: 0.7367871	best: 0.7368517 (695)	total: 3m 5s	remaining: 0us

bestTest = 0.7368517338
bestIteration = 695

Shrink model to first 696 iterations.
[META] AUC: 0.736852

===== META FOLD 2 =====
0:	test: 0.7211629	best: 0.7211629 (0)	total: 196ms	remaining: 3m 15s
200:	test: 0.7422111	best: 0.7422111 (200)	total: 37.8s	remaining: 2m 30s
400:	test: 0.7423715	best: 0.7423715 (400)	total: 1m 15s	remaining: 1m 52s
600:	test: 0.7424156	best: 0.7424164 (597)	total: 1m 54s	remaining: 1m 15s
800:	test: 0.7424392	best: 0.7424429 (752)	total: 2m 34s	remaining: 38.5s
999:	test: 0.7424143	best: 0.7424429 (752)	total: 3m 15s	remaining: 0us

bestTest = 0.7424428691
bestIteration = 752

Shrink model to first 753 iterations.
[META] AUC: 0.742443

===== META FOLD 3 =====
0:	test: 0.7175491	best: 0.7175491 (0)	total: 215ms	remaining: 3m 34s
200:	test: 0.7381850	best: 0.7381850 (200)	total: 39s	remaining: 2m 35s
400:	test: 0.7384242	best: 0.7384245 (399)	total: 1m 16s	remaining: 1m 53s
600:	test: 0.7384475	best: 0.7384491 (598)	total: 1m 53s	remaining: 1m 15s
800:	test: 0.7384602	best: 0.7384635 (739)	total: 2m 31s	remaining: 37.7s
999:	test: 0.7384401	best: 0.7384640 (827)	total: 3m 9s	remaining: 0us

bestTest = 0.7384640148
bestIteration = 827

Shrink model to first 828 iterations.
[META] AUC: 0.738464

===== META FOLD 4 =====
0:	test: 0.7178369	best: 0.7178369 (0)	total: 204ms	remaining: 3m 24s
200:	test: 0.7392888	best: 0.7392888 (200)	total: 38.1s	remaining: 2m 31s
400:	test: 0.7394256	best: 0.7394287 (366)	total: 1m 15s	remaining: 1m 52s
600:	test: 0.7394299	best: 0.7394324 (565)	total: 1m 53s	remaining: 1m 15s
800:	test: 0.7394098	best: 0.7394324 (565)	total: 2m 32s	remaining: 37.8s
999:	test: 0.7393875	best: 0.7394324 (565)	total: 3m 10s	remaining: 0us

bestTest = 0.7394323562
bestIteration = 565

Shrink model to first 566 iterations.
[META] AUC: 0.739432

========== FINAL ==========
STACKING AUC: 0.739146620974755

In [19]:
models_dir = "models"
os.makedirs(models_dir, exist_ok=True)

# ===== Сохраняем CatBoost модели =====
for i, (auc, model) in enumerate(cat_models_auc):
    filename = os.path.join(models_dir, f"catboost_fold{i}.cbm")
    model.save_model(filename)
    print(f"Saved CatBoost fold {i} -> {filename}")

# ===== Сохраняем LightGBM модели =====
for i, (auc, model) in enumerate(lgb_models_auc):
    filename = os.path.join(models_dir, f"lgbm_fold{i}.pkl")
    joblib.dump(model, filename)
    print(f"Saved LightGBM fold {i} -> {filename}")

# ===== Сохраняем XGBoost модели =====
for i, (auc, model) in enumerate(xgb_models_auc):
    filename = os.path.join(models_dir, f"xgb_fold{i}.json")
    model.save_model(filename)
    print(f"Saved XGBoost fold {i} -> {filename}")

# ===== Сохраняем метамодель =====
meta_filename = os.path.join(models_dir, "meta_model.cbm")
meta_model.save_model(meta_filename)
print(f"Saved meta model -> {meta_filename}")

Saved CatBoost fold 0 -> models\catboost_fold0.cbm
Saved CatBoost fold 1 -> models\catboost_fold1.cbm
Saved CatBoost fold 2 -> models\catboost_fold2.cbm
Saved CatBoost fold 3 -> models\catboost_fold3.cbm
Saved CatBoost fold 4 -> models\catboost_fold4.cbm
Saved LightGBM fold 0 -> models\lgbm_fold0.pkl
Saved LightGBM fold 1 -> models\lgbm_fold1.pkl
Saved LightGBM fold 2 -> models\lgbm_fold2.pkl
Saved LightGBM fold 3 -> models\lgbm_fold3.pkl
Saved LightGBM fold 4 -> models\lgbm_fold4.pkl
Saved XGBoost fold 0 -> models\xgb_fold0.json
Saved XGBoost fold 1 -> models\xgb_fold1.json
Saved XGBoost fold 2 -> models\xgb_fold2.json
Saved XGBoost fold 3 -> models\xgb_fold3.json
Saved XGBoost fold 4 -> models\xgb_fold4.json
Saved meta model -> models\meta_model.cbm

## modeling 03.04

### загружаем модели, восстанавливаем данные предсказаний

In [4]:
models_dir = "models"

cat_models = []
lgb_models = []
xgb_models = []

# CatBoost
for i in range(5):
    model = CatBoostClassifier()
    model.load_model(os.path.join(models_dir, f"catboost_fold{i}.cbm"))
    cat_models.append(model)

# LightGBM
for i in range(5):
    model = joblib.load(os.path.join(models_dir, f"lgbm_fold{i}.pkl"))
    lgb_models.append(model)

# XGBoost
for i in range(5):
    model = xgb.XGBClassifier()
    model.load_model(os.path.join(models_dir, f"xgb_fold{i}.json"))
    xgb_models.append(model)

In [10]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

oof_cat = np.zeros(len(X))
oof_lgb = np.zeros(len(X))
oof_xgb = np.zeros(len(X))

for fold, (_, val_idx) in enumerate(skf.split(X, y)):
    print(f"Restoring fold {fold}")
    
    # CatBoost
    oof_cat[val_idx] = cat_models[fold].predict_proba(X_np[val_idx])[:, 1]
    
    # LightGBM
    oof_lgb[val_idx] = lgb_models[fold].predict_proba(X_lgb_np[val_idx])[:, 1]
    
    # XGBoost
    oof_xgb[val_idx] = xgb_models[fold].predict_proba(X_xgb_np[val_idx])[:, 1]

Restoring fold 0

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

Restoring fold 1

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

Restoring fold 2

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

Restoring fold 3

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

Restoring fold 4

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

In [11]:
print("CatBoost OOF AUC:", roc_auc_score(y, oof_cat))
print("LightGBM OOF AUC:", roc_auc_score(y, oof_lgb))
print("XGBoost OOF AUC:", roc_auc_score(y, oof_xgb))

CatBoost OOF AUC: 0.7383799287438716
LightGBM OOF AUC: 0.735461521776563
XGBoost OOF AUC: 0.6798668074956296

### выясняем ошибки

In [12]:
df = data.copy()

df["target"] = y

df["oof_cat"] = oof_cat
df["oof_lgb"] = oof_lgb
df["oof_xgb"] = oof_xgb

df["oof_mean"] = (oof_cat + oof_lgb) / 2

df["error"] = abs(df["target"] - df["oof_mean"])

df["residual"] = df["target"] - df["oof_mean"]

df["confidence"] = abs(df["oof_mean"] - 0.5)

df["model_disagreement"] = (
    abs(df["oof_cat"] - df["oof_lgb"]) +
    abs(df["oof_cat"] - df["oof_xgb"]) +
    abs(df["oof_lgb"] - df["oof_xgb"])
)

In [13]:
df["bin"] = pd.qcut(df["oof_mean"], 10, duplicates="drop")

analysis = df.groupby("bin").agg({
    "target": "mean",
    "oof_mean": "mean",
    "error": "mean",
    "residual": "mean",
    "confidence": "mean",
    "model_disagreement": "mean"
}).reset_index()

print(analysis)

               bin    target  oof_mean     error  residual  confidence  \
0  (0.0093, 0.157]  0.004787  0.114493  0.118107 -0.109706    0.385507
1    (0.157, 0.22]  0.008270  0.189605  0.194694 -0.181335    0.310395
2    (0.22, 0.278]  0.012340  0.249391  0.255534 -0.237051    0.250609
3   (0.278, 0.336]  0.017007  0.306890  0.313408 -0.289883    0.193110
4   (0.336, 0.394]  0.022323  0.364715  0.370686 -0.342391    0.135285
5   (0.394, 0.454]  0.028687  0.423876  0.428158 -0.395189    0.076124
6   (0.454, 0.517]  0.037140  0.485108  0.486117 -0.447968    0.019314
7   (0.517, 0.586]  0.047477  0.550625  0.545683 -0.503148    0.050625
8    (0.586, 0.67]  0.064287  0.625740  0.609257 -0.561454    0.125740
9    (0.67, 0.977]  0.112490  0.740428  0.682700 -0.627938    0.240428

   model_disagreement
0            0.377319
1            0.323880
2            0.281809
3            0.248528
4            0.226809
5            0.218339
6            0.220794
7            0.230034
8            0.241497
9            0.245169

C:\Users\User\AppData\Local\Temp\ipykernel_19640\3548515041.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  analysis = df.groupby("bin").agg({

In [14]:
calibrator = LogisticRegression(max_iter=1000)
calibrator.fit(df["oof_mean"].values.reshape(-1, 1), df["target"])

df["oof_calibrated"] = calibrator.predict_proba(
    df["oof_mean"].values.reshape(-1, 1)
)[:, 1]

In [15]:
df["bin_calibrated"] = pd.qcut(df["oof_calibrated"], 10, duplicates="drop")

analysis_calibrated = df.groupby("bin_calibrated").agg({
    "target": "mean",
    "oof_calibrated": "mean",
    "error": "mean",
    "residual": "mean",
    "confidence": "mean"
}).reset_index()

print(analysis_calibrated)

       bin_calibrated    target  oof_calibrated     error  residual  \
0  (0.00288, 0.00777]  0.004787        0.006407  0.118107 -0.109706
1   (0.00777, 0.0104]  0.008270        0.009063  0.194694 -0.181335
2    (0.0104, 0.0137]  0.012340        0.011987  0.255534 -0.237051
3    (0.0137, 0.0179]  0.017007        0.015676  0.313408 -0.289883
4    (0.0179, 0.0234]  0.022323        0.020512  0.370686 -0.342391
5    (0.0234, 0.0309]  0.028687        0.026966  0.428158 -0.395189
6    (0.0309, 0.0411]  0.037140        0.035718  0.486117 -0.447968
7    (0.0411, 0.0561]  0.047477        0.048106  0.545683 -0.503148
8    (0.0561, 0.0813]  0.064287        0.067373  0.609257 -0.561454
9     (0.0813, 0.274]  0.112490        0.112480  0.682700 -0.627938

   confidence
0    0.385507
1    0.310395
2    0.250609
3    0.193110
4    0.135285
5    0.076124
6    0.019314
7    0.050625
8    0.125740
9    0.240428

C:\Users\User\AppData\Local\Temp\ipykernel_19640\3605508851.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  analysis_calibrated = df.groupby("bin_calibrated").agg({

In [16]:
df.sort_values("error", ascending=False).head(50)

,id,pre_since_opened_min,pre_since_opened_max,pre_since_opened_mean,pre_since_confirmed_min,pre_since_confirmed_max,pre_since_confirmed_mean,pre_pterm_min,pre_pterm_max,pre_pterm_mean,...,oof_lgb,oof_xgb,oof_mean,error,residual,confidence,model_disagreement,bin,oof_calibrated,bin_calibrated
824981,2824981,8,16,12.000,1,17,7.727,1,13,7.637,...,0.015737,0.206148,0.016884,0.983116,0.983116,0.483116,0.380824,"(0.0093, 0.157]",0.004007,"(0.00288, 0.00777]"
1948814,1448814,12,19,12.710,2,16,9.190,3,14,3.975,...,0.976090,0.826998,0.976731,0.976731,-0.976731,0.476731,0.300748,"(0.67, 0.977]",0.274492,"(0.0813, 0.274]"
2103828,1603828,7,18,13.664,6,16,10.664,0,12,5.168,...,0.021151,0.158201,0.025598,0.974402,0.974402,0.474402,0.274100,"(0.0093, 0.157]",0.004175,"(0.00288, 0.00777]"
2523230,2023230,4,18,11.000,0,17,8.500,0,17,7.750,...,0.025324,0.140955,0.029331,0.970669,0.970669,0.470669,0.231261,"(0.0093, 0.157]",0.004250,"(0.00288, 0.00777]"
2910075,2410075,3,19,12.930,0,16,6.105,3,14,4.320,...,0.969878,0.779866,0.970597,0.970597,-0.970597,0.470597,0.382900,"(0.67, 0.977]",0.268747,"(0.0813, 0.274]"
1991164,1491164,3,15,8.700,7,12,9.300,1,14,3.000,...,0.019584,0.219688,0.029754,0.970246,0.970246,0.470246,0.400207,"(0.0093, 0.157]",0.004258,"(0.00288, 0.00777]"
2936945,2436945,2,19,12.880,0,16,7.560,0,14,4.500,...,0.963157,0.808360,0.968720,0.968720,-0.968720,0.468720,0.331845,"(0.67, 0.977]",0.267005,"(0.0813, 0.274]"
1320099,820099,4,17,10.500,9,9,9.000,4,4,4.000,...,0.022629,0.274379,0.032436,0.967564,0.967564,0.467564,0.503499,"(0.0093, 0.157]",0.004312,"(0.00288, 0.00777]"
1413586,913586,2,19,12.860,2,16,9.690,0,13,4.277,...,0.957016,0.780019,0.966591,0.966591,-0.966591,0.466591,0.392291,"(0.67, 0.977]",0.265037,"(0.0813, 0.274]"
919399,2919399,3,16,6.500,3,9,5.500,4,16,10.500,...,0.046133,0.393994,0.037676,0.962324,0.962324,0.462324,0.729547,"(0.0093, 0.157]",0.004420,"(0.00288, 0.00777]"
1485260,985260,9,19,12.970,0,16,6.780,0,14,3.688,...,0.954718,0.770418,0.961460,0.961460,-0.961460,0.461460,0.395566,"(0.67, 0.977]",0.260333,"(0.0813, 0.274]"
2457077,1957077,4,18,11.000,3,17,9.290,2,13,6.715,...,0.048920,0.241308,0.038883,0.961117,0.961117,0.461117,0.424921,"(0.0093, 0.157]",0.004445,"(0.00288, 0.00777]"
1688413,1188413,7,12,11.734,0,16,10.570,3,17,4.566,...,0.968236,0.860076,0.960325,0.960325,-0.960325,0.460325,0.216320,"(0.67, 0.977]",0.259300,"(0.0813, 0.274]"
1149803,649803,12,19,12.630,0,16,5.970,3,15,4.184,...,0.957977,0.821393,0.960220,0.960220,-0.960220,0.460220,0.282140,"(0.67, 0.977]",0.259204,"(0.0813, 0.274]"
2646023,2146023,7,19,12.740,6,16,9.610,0,9,4.066,...,0.959878,0.778002,0.959859,0.959859,-0.959859,0.459859,0.363752,"(0.67, 0.977]",0.258877,"(0.0813, 0.274]"
2390520,1890520,0,18,9.000,2,12,6.400,0,14,7.200,...,0.040998,0.301453,0.044422,0.955578,0.955578,0.455578,0.520910,"(0.0093, 0.157]",0.004563,"(0.00288, 0.00777]"
1961319,1461319,2,19,12.445,0,16,6.973,1,14,3.584,...,0.945699,0.816678,0.955275,0.955275,-0.955275,0.455275,0.296348,"(0.67, 0.977]",0.254735,"(0.0813, 0.274]"
621694,2621694,0,18,7.727,3,17,9.730,0,14,7.273,...,0.043137,0.222279,0.044879,0.955121,0.955121,0.455121,0.358283,"(0.0093, 0.157]",0.004573,"(0.00288, 0.00777]"
45483,45483,0,18,9.860,9,13,9.570,1,17,5.430,...,0.035474,0.275181,0.045079,0.954921,0.954921,0.454921,0.479414,"(0.0093, 0.157]",0.004577,"(0.00288, 0.00777]"
2397001,1897001,10,17,13.336,0,17,10.336,0,15,5.000,...,0.043092,0.271553,0.046592,0.953408,0.953408,0.453408,0.456922,"(0.0093, 0.157]",0.004610,"(0.00288, 0.00777]"
2874030,2374030,2,17,7.445,1,17,7.332,4,9,5.555,...,0.057841,0.731638,0.046880,0.953120,0.953120,0.453120,1.391440,"(0.0093, 0.157]",0.004616,"(0.00288, 0.00777]"
11879,11879,1,17,13.250,3,14,8.500,0,17,8.250,...,0.041958,0.259896,0.047586,0.952414,0.952414,0.452414,0.435874,"(0.0093, 0.157]",0.004631,"(0.00288, 0.00777]"
107991,107991,3,19,13.850,0,16,8.125,0,10,4.152,...,0.945539,0.768190,0.951138,0.951138,-0.951138,0.451138,0.377093,"(0.67, 0.977]",0.251035,"(0.0813, 0.274]"
2871981,2371981,0,18,10.570,1,17,10.500,0,17,8.500,...,0.068485,0.410420,0.049180,0.950820,0.950820,0.450820,0.761090,"(0.0093, 0.157]",0.004666,"(0.00288, 0.00777]"
2130890,1630890,9,19,15.060,0,9,2.871,3,4,3.387,...,0.942204,0.842128,0.950746,0.950746,-0.950746,0.450746,0.234322,"(0.67, 0.977]",0.250687,"(0.0813, 0.274]"
4338,4338,2,13,6.800,2,9,7.200,4,12,7.400,...,0.043222,0.279934,0.049803,0.950197,0.950197,0.450197,0.473424,"(0.0093, 0.157]",0.004680,"(0.00288, 0.00777]"
1359545,859545,5,19,12.970,0,16,7.970,0,14,3.970,...,0.952951,0.821348,0.949939,0.949939,-0.949939,0.449939,0.263206,"(0.67, 0.977]",0.249970,"(0.0813, 0.274]"
1918483,1418483,3,3,3.000,17,17,17.000,3,3,3.000,...,0.948561,0.869446,0.949570,0.949570,-0.949570,0.449570,0.162264,"(0.67, 0.977]",0.249642,"(0.0813, 0.274]"
1646309,1146309,1,19,11.500,2,16,8.500,2,14,4.680,...,0.931258,0.795072,0.948851,0.948851,-0.948851,0.448851,0.342747,"(0.67, 0.977]",0.249006,"(0.0813, 0.274]"
1380679,880679,0,18,9.870,3,16,6.780,0,17,10.260,...,0.050509,0.227065,0.051574,0.948426,0.948426,0.448426,0.353111,"(0.0093, 0.157]",0.004719,"(0.00288, 0.00777]"
516409,2516409,2,19,12.040,0,16,7.645,3,17,6.605,...,0.941928,0.751145,0.948317,0.948317,-0.948317,0.448317,0.407122,"(0.67, 0.977]",0.248533,"(0.0813, 0.274]"
1907613,1407613,0,16,12.000,4,13,7.445,1,13,5.332,...,0.051461,0.239857,0.051876,0.948124,0.948124,0.448124,0.376792,"(0.0093, 0.157]",0.004726,"(0.00288, 0.00777]"
1094111,594111,7,19,13.420,0,16,4.652,2,14,4.080,...,0.946807,0.793618,0.947431,0.947431,-0.947431,0.447431,0.308873,"(0.67, 0.977]",0.247750,"(0.0813, 0.274]"
1302537,802537,0,18,5.400,9,16,10.100,1,14,4.800,...,0.054933,0.221564,0.053271,0.946729,0.946729,0.446729,0.339911,"(0.0093, 0.157]",0.004757,"(0.00288, 0.00777]"
1167012,667012,1,19,12.340,0,16,9.410,0,15,4.220,...,0.947957,0.792523,0.946404,0.946404,-0.946404,0.446404,0.310868,"(0.67, 0.977]",0.246846,"(0.0813, 0.274]"
590189,2590189,1,19,12.484,0,16,5.574,3,14,5.000,...,0.944195,0.816469,0.946296,0.946296,-0.946296,0.446296,0.263856,"(0.67, 0.977]",0.246750,"(0.0813, 0.274]"
1168667,668667,1,12,11.090,0,16,8.350,1,17,3.936,...,0.948993,0.841538,0.945990,0.945990,-0.945990,0.445990,0.214911,"(0.67, 0.977]",0.246481,"(0.0813, 0.274]"
2356195,1856195,10,15,12.500,7,16,11.500,6,12,9.000,...,0.042314,0.268180,0.054181,0.945819,0.945819,0.445819,0.451733,"(0.0093, 0.157]",0.004778,"(0.00288, 0.00777]"
2735736,2235736,12,12,12.000,2,16,9.125,3,4,3.625,...,0.944968,0.850479,0.945480,0.945480,-0.945480,0.445480,0.191025,"(0.67, 0.977]",0.246033,"(0.0813, 0.274]"
336088,336088,4,19,13.266,0,16,8.060,0,14,5.530,...,0.937435,0.765355,0.945324,0.945324,-0.945324,0.445324,0.375717,"(0.67, 0.977]",0.245896,"(0.0813, 0.274]"
1826531,1326531,1,19,11.430,1,13,7.367,3,14,4.965,...,0.956952,0.758667,0.945218,0.945218,-0.945218,0.445218,0.396570,"(0.67, 0.977]",0.245803,"(0.0813, 0.274]"
2552130,2052130,3,17,9.000,2,14,8.290,0,17,10.860,...,0.067093,0.235700,0.054840,0.945160,0.945160,0.445160,0.386228,"(0.0093, 0.157]",0.004792,"(0.00288, 0.00777]"
2123335,1623335,0,16,8.000,1,10,6.000,1,4,2.250,...,0.041115,0.212583,0.055089,0.944911,0.944911,0.444911,0.342937,"(0.0093, 0.157]",0.004798,"(0.00288, 0.00777]"
2023675,1523675,12,19,13.000,0,16,8.914,3,17,7.418,...,0.935273,0.766903,0.944899,0.944899,-0.944899,0.444899,0.375243,"(0.67, 0.977]",0.245523,"(0.0813, 0.274]"
667963,2667963,7,19,13.610,0,16,5.934,0,8,3.355,...,0.938444,0.802855,0.944597,0.944597,-0.944597,0.444597,0.295792,"(0.67, 0.977]",0.245259,"(0.0813, 0.274]"
165799,165799,1,19,11.164,0,16,9.860,1,16,4.640,...,0.942190,0.821443,0.944250,0.944250,-0.944250,0.444250,0.249733,"(0.67, 0.977]",0.244954,"(0.0813, 0.274]"
2756478,2256478,5,19,14.580,0,16,6.883,3,14,5.190,...,0.940812,0.763330,0.944028,0.944028,-0.944028,0.444028,0.367829,"(0.67, 0.977]",0.244760,"(0.0813, 0.274]"
954333,2954333,4,19,12.234,4,16,9.840,1,17,8.380,...,0.041613,0.251027,0.056184,0.943816,0.943816,0.443816,0.418827,"(0.0093, 0.157]",0.004823,"(0.00288, 0.00777]"
2966468,2466468,13,13,13.000,16,16,16.000,11,11,11.000,...,0.933765,0.361298,0.943793,0.943793,-0.943793,0.443793,1.185045,"(0.67, 0.977]",0.244555,"(0.0813, 0.274]"
2977217,2477217,7,14,11.760,0,16,8.410,2,14,4.027,...,0.941050,0.790714,0.943608,0.943608,-0.943608,0.443608,0.310905,"(0.67, 0.977]",0.244393,"(0.0813, 0.274]"

### ещё больше метрик

In [17]:
threshold = 0.5

df["error_type"] = "TN"

df.loc[(df["target"] == 1) & (df["oof_mean"] >= threshold), "error_type"] = "TP"
df.loc[(df["target"] == 1) & (df["oof_mean"] < threshold), "error_type"] = "FN"
df.loc[(df["target"] == 0) & (df["oof_mean"] >= threshold), "error_type"] = "FP"

In [18]:
error_stats = df.groupby("error_type").agg({
    "target": "mean",
    "oof_mean": "mean",
    "error": "mean",
    "residual": "mean",
    "confidence": "mean",
    "model_disagreement": "mean"
}).sort_values("error", ascending=False)

print("\n=== ERROR STATS ===")
print(error_stats)

=== ERROR STATS ===
            target  oof_mean     error  residual  confidence  \
error_type
FN             1.0  0.363166  0.636834  0.636834    0.136834
FP             0.0  0.625300  0.625300 -0.625300    0.125300
TP             1.0  0.668867  0.331133  0.331133    0.168867
TN             0.0  0.295743  0.295743 -0.295743    0.204257

            model_disagreement
error_type
FN                    0.244924
FP                    0.237364
TP                    0.241511
TN                    0.273427

In [19]:
error_counts = df["error_type"].value_counts(normalize=True)

print("\n=== ERROR DISTRIBUTION ===")
print(error_counts)

=== ERROR DISTRIBUTION ===
error_type
TN    0.661779
FP    0.302741
TP    0.023491
FN    0.011989
Name: proportion, dtype: float64

In [24]:
# Выбираем только числовые признаки (исключаем служебные)
exclude_cols = [
    "target", "oof_cat", "oof_lgb", "oof_xgb",
    "oof_mean", "error", "residual", "confidence",
    "model_disagreement", "error_type",
    "bin", "bin_calibrated"
]

feature_cols = [col for col in df.columns if col not in exclude_cols and df[col].dtype != "object"]

# Средние значения признаков по типам ошибок
feature_analysis = df.groupby("error_type")[feature_cols].mean()

print("\n=== FEATURE MEAN BY ERROR TYPE ===")
print(feature_analysis)

=== FEATURE MEAN BY ERROR TYPE ===
                      id  pre_since_opened_min  pre_since_opened_max  \
error_type
FN          1.586132e+06              2.458074             15.867299
FP          1.478092e+06              3.742802             15.855054
TN          1.510030e+06              2.418896             15.903067
TP          1.455790e+06              4.190240             15.722465

            pre_since_opened_mean  pre_since_confirmed_min  \
error_type
FN                       9.093937                 2.912561
FP                       9.657073                 3.332025
TN                       9.164279                 2.919392
TP                       9.846623                 3.501376

            pre_since_confirmed_max  pre_since_confirmed_mean  pre_pterm_min  \
error_type
FN                        13.782640                  8.217750       2.344250
FP                        13.169223                  8.100171       2.916735
TN                        13.832653                  8.257872       2.183826
TP                        12.950194                  8.070849       3.049976

            pre_pterm_max  pre_pterm_mean  ...  bad_to_total_ratio  \
error_type                                 ...
FN              14.601145        8.455562  ...            4.986642
FP              13.836222        8.222903  ...            5.459786
TN              14.558116        8.301976  ...            4.870045
TP              13.438999        8.016137  ...            5.513994

            paym_trend_abs  recent_vs_old  recent_vs_old_early  paym_std  \
error_type
FN                0.165969       1.254249             1.117141  0.760010
FP                0.173618       1.126859             1.175303  0.817971
TN                0.160842       1.213732             1.083815  0.736256
TP                0.167342       1.045416             1.123017  0.806121

            worst_paym_ever  paym_switches  last_vs_mean  flag  oof_calibrated
error_type
FN                 3.359420       1.035226     -1.387495   1.0        0.022330
FP                 3.585527       0.826963     -1.501481   0.0        0.071893
TN                 3.284954       1.028467     -1.339903   0.0        0.017115
TP                 3.625311       0.775520     -1.466729   1.0        0.088102

[4 rows x 118 columns]

In [25]:
if "FN" in df["error_type"].values and "TP" in df["error_type"].values:
    fn_mean = df[df["error_type"] == "FN"][feature_cols].mean()
    tp_mean = df[df["error_type"] == "TP"][feature_cols].mean()
    
    diff_fn_tp = (fn_mean - tp_mean).abs().sort_values(ascending=False)

    print("\n=== TOP FEATURES: FN vs TP (model misses positives) ===")
    print(diff_fn_tp.head(20))

=== TOP FEATURES: FN vs TP (model misses positives) ===
max_utilization_ratio_max             580287.997579
client_util_std_max                   204006.460197
id                                    130341.266766
mean_utilization_ratio_max             94118.276886
pre_loans530_sum                          25.663539
client_mean_weighted_paym_score           10.657897
pre_loans5_sum                             9.567960
decayed_paym_score_mean                    4.583526
client_mean_bad_months_per_product         3.720217
enc_paym_2_sum                             3.482076
client_mean_severe_bad_months              3.419420
enc_paym_3_sum                             3.401044
client_max_weighted_paym_score             3.219564
enc_paym_4_sum                             3.192154
enc_paym_20_sum                            3.131614
enc_paym_1_sum                             2.938739
enc_paym_5_sum                             2.877022
enc_paym_6_sum                             2.413448
decayed_paym_score_max                     2.178622
is_zero_loans530_sum                       2.070142
dtype: float64

In [22]:
hypothesis_check = df.groupby("error_type")[[
    "model_disagreement",
    "confidence",
    "oof_mean"
]].mean()

print("\n=== HYPOTHESIS CHECK ===")
print(hypothesis_check)

=== HYPOTHESIS CHECK ===
            model_disagreement  confidence  oof_mean
error_type
FN                    0.244924    0.136834  0.363166
FP                    0.237364    0.125300  0.625300
TN                    0.273427    0.204257  0.295743
TP                    0.241511    0.168867  0.668867

In [28]:
abs(df.groupby("error_type").mean(numeric_only=True).loc["FP"] -
    df.groupby("error_type").mean(numeric_only=True).loc["TN"]).sort_values(ascending=False).head(20)

max_utilization_ratio_max             564369.320434
client_util_std_max                   215543.825239
mean_utilization_ratio_max            109653.219973
id                                     31938.337638
pre_loans530_sum                          16.792884
client_mean_weighted_paym_score           10.147324
pre_loans5_sum                             6.113615
decayed_paym_score_mean                    3.975303
client_mean_bad_months_per_product         3.633835
client_max_weighted_paym_score             3.287662
client_mean_severe_bad_months              3.200703
enc_paym_3_sum                             2.998331
enc_paym_2_sum                             2.965600
enc_paym_4_sum                             2.893129
enc_paym_5_sum                             2.689523
enc_paym_1_sum                             2.498426
enc_paym_6_sum                             2.391644
enc_paym_7_sum                             2.184223
decayed_paym_score_max                     1.987949
enc_paym_8_sum                             1.978283
dtype: float64

## modeling 6.04-7.04

In [13]:
cat_params = {
    'iterations': 3000,
    'depth': 8,
    'learning_rate': 0.03,
    'l2_leaf_reg': 7,
    'loss_function': 'Logloss',
    'eval_metric': 'AUC',
    'class_weights': class_weights_dict,
    'early_stopping_rounds': 200,
    'verbose': 200
}

In [14]:
X = data.drop(['flag', 'id'], axis=1)
y = data["flag"]

skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

oof_preds = np.zeros(len(X))
scores = []

for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):
    print(f"\n===== FOLD {fold} =====")

    X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
    y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

    model = CatBoostClassifier(**cat_params)

    model.fit(X_train, y_train, eval_set=(X_val, y_val))

    preds = model.predict_proba(X_val)[:, 1]
    oof_preds[val_idx] = preds

    fold_auc = roc_auc_score(y_val, preds)
    scores.append(fold_auc)

    print(f"Fold AUC: {fold_auc:.5f}")

print("\nMean AUC:", np.mean(scores))
print("OOF AUC:", roc_auc_score(y, oof_preds))

===== FOLD 0 =====
0:	test: 0.6834223	best: 0.6834223 (0)	total: 705ms	remaining: 35m 14s
200:	test: 0.7237164	best: 0.7237164 (200)	total: 1m 46s	remaining: 24m 41s
400:	test: 0.7303229	best: 0.7303229 (400)	total: 3m 35s	remaining: 23m 16s
600:	test: 0.7341564	best: 0.7341564 (600)	total: 5m 32s	remaining: 22m 7s
800:	test: 0.7362640	best: 0.7362640 (800)	total: 7m 38s	remaining: 20m 59s
1000:	test: 0.7371618	best: 0.7371618 (1000)	total: 9m 39s	remaining: 19m 17s
1200:	test: 0.7378215	best: 0.7378301 (1192)	total: 11m 25s	remaining: 17m 7s
1400:	test: 0.7380649	best: 0.7380694 (1396)	total: 13m 16s	remaining: 15m 9s
1600:	test: 0.7381901	best: 0.7381932 (1565)	total: 15m 14s	remaining: 13m 19s
1800:	test: 0.7381919	best: 0.7382488 (1677)	total: 17m 14s	remaining: 11m 29s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7382487702
bestIteration = 1677

Shrink model to first 1678 iterations.
Fold AUC: 0.73825

===== FOLD 1 =====
0:	test: 0.6876390	best: 0.6876390 (0)	total: 571ms	remaining: 28m 33s
200:	test: 0.7286269	best: 0.7286269 (200)	total: 1m 57s	remaining: 27m 9s
400:	test: 0.7349373	best: 0.7349373 (400)	total: 4m 1s	remaining: 26m 3s
600:	test: 0.7383190	best: 0.7383190 (600)	total: 6m 5s	remaining: 24m 18s
800:	test: 0.7401786	best: 0.7401786 (800)	total: 8m 9s	remaining: 22m 22s
1000:	test: 0.7411575	best: 0.7411623 (997)	total: 10m 8s	remaining: 20m 14s
1200:	test: 0.7415727	best: 0.7415775 (1198)	total: 12m 9s	remaining: 18m 12s
1400:	test: 0.7417510	best: 0.7417769 (1369)	total: 14m 7s	remaining: 16m 6s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7417769134
bestIteration = 1369

Shrink model to first 1370 iterations.
Fold AUC: 0.74178

===== FOLD 2 =====
0:	test: 0.6851181	best: 0.6851181 (0)	total: 668ms	remaining: 33m 22s
200:	test: 0.7245209	best: 0.7245209 (200)	total: 1m 55s	remaining: 26m 49s
400:	test: 0.7309403	best: 0.7309403 (400)	total: 3m 55s	remaining: 25m 27s
600:	test: 0.7348101	best: 0.7348101 (600)	total: 5m 52s	remaining: 23m 26s
800:	test: 0.7368156	best: 0.7368156 (800)	total: 7m 51s	remaining: 21m 34s
1000:	test: 0.7379139	best: 0.7379139 (1000)	total: 9m 49s	remaining: 19m 36s
1200:	test: 0.7386250	best: 0.7386250 (1200)	total: 11m 50s	remaining: 17m 44s
1400:	test: 0.7389144	best: 0.7389144 (1400)	total: 13m 48s	remaining: 15m 45s
1600:	test: 0.7390161	best: 0.7390246 (1585)	total: 15m 42s	remaining: 13m 43s
1800:	test: 0.7391615	best: 0.7391615 (1800)	total: 17m 42s	remaining: 11m 47s
2000:	test: 0.7391802	best: 0.7392268 (1945)	total: 19m 36s	remaining: 9m 47s
2200:	test: 0.7390998	best: 0.7392374 (2060)	total: 21m 33s	remaining: 7m 49s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7392373708
bestIteration = 2060

Shrink model to first 2061 iterations.
Fold AUC: 0.73924

Mean AUC: 0.7397543514747905
OOF AUC: 0.7396820045028566

In [17]:
new_features = [
    # worst loan
    "worst_loan_paym_mean",
    "worst_loan_util",
    "worst_loan_overdue",
    "worst_loan_paym_to_mean",
    "worst_loan_util_to_mean_util",

    # last loan
    "last_loan_paym_mean",
    "last_loan_util",
    "last_loan_outstanding",
    "last_vs_mean_paym",
    "last_vs_mean_util",
    "last_vs_worst_paym",

    # dispersion
    "loan_paym_std",
    "loan_util_std",
    "loan_overdue_std",
    "loan_paym_max_minus_mean",
    "loan_util_max_minus_mean",
]

In [18]:
feature_importance = pd.DataFrame({
    "feature": X.columns,
    "importance": model.get_feature_importance()
})

# только новые фичи
new_feat_importance = feature_importance[
    feature_importance["feature"].isin(new_features)
].sort_values("importance", ascending=False)

print(new_feat_importance)

                          feature  importance
114                last_loan_util    2.108120
131            last_vs_worst_paym    1.950424
116         last_loan_outstanding    1.590421
127      loan_util_max_minus_mean    1.478892
129             last_vs_mean_util    1.231421
130             last_vs_mean_paym    1.104118
126      loan_paym_max_minus_mean    0.960508
117                 loan_paym_std    0.819798
112           last_loan_paym_mean    0.807143
132  worst_loan_util_to_mean_util    0.718279
120                 loan_util_std    0.533657
107               worst_loan_util    0.520324
123              loan_overdue_std    0.419157
105          worst_loan_paym_mean    0.277581
108            worst_loan_overdue    0.069445

In [19]:
total_importance = feature_importance["importance"].sum()
new_importance = new_feat_importance["importance"].sum()

print("New features total importance:", new_importance)
print("Share of total importance:", new_importance / total_importance)

New features total importance: 14.589289065109323
Share of total importance: 0.14589289065109315

In [20]:
for col in new_features:
    if col in X.columns:
        auc = roc_auc_score(y, X[col])
        print(f"{col}: {auc:.5f}")

worst_loan_paym_mean: 0.53476
worst_loan_util: 0.48952
worst_loan_overdue: 0.49135
worst_loan_util_to_mean_util: 0.50965
last_loan_paym_mean: 0.58107
last_loan_util: 0.49424
last_loan_outstanding: 0.51710
last_vs_mean_paym: 0.47835
last_vs_mean_util: 0.54353
last_vs_worst_paym: 0.56037
loan_paym_std: 0.42435
loan_util_std: 0.45043
loan_overdue_std: 0.54414
loan_paym_max_minus_mean: 0.41120
loan_util_max_minus_mean: 0.45097

## modeling 14.04

In [17]:
cat_params = {
    'iterations': 3000,
    'depth': 8,
    'learning_rate': 0.03,
    'l2_leaf_reg': 7,
    'loss_function': 'Logloss',
    'eval_metric': 'AUC',
    'class_weights': class_weights_dict,
    'early_stopping_rounds': 200,
    'verbose': 200
}

In [18]:
X = data.drop(['flag', 'id'], axis=1)
y = data["flag"]

skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

oof_preds = np.zeros(len(X))
scores = []

for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):
    print(f"\n===== FOLD {fold} =====")

    X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
    y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

    model = CatBoostClassifier(**cat_params)

    model.fit(X_train, y_train, eval_set=(X_val, y_val))

    preds = model.predict_proba(X_val)[:, 1]
    oof_preds[val_idx] = preds

    fold_auc = roc_auc_score(y_val, preds)
    scores.append(fold_auc)

    print(f"Fold AUC: {fold_auc:.5f}")

print("\nMean AUC:", np.mean(scores))
print("OOF AUC:", roc_auc_score(y, oof_preds))

===== FOLD 0 =====
0:	test: 0.6827996	best: 0.6827996 (0)	total: 722ms	remaining: 36m 5s
200:	test: 0.7237999	best: 0.7237999 (200)	total: 1m 56s	remaining: 26m 59s
400:	test: 0.7304127	best: 0.7304127 (400)	total: 3m 53s	remaining: 25m 16s
600:	test: 0.7343932	best: 0.7343932 (600)	total: 5m 50s	remaining: 23m 19s
800:	test: 0.7364060	best: 0.7364060 (800)	total: 7m 46s	remaining: 21m 21s
1000:	test: 0.7373331	best: 0.7373331 (1000)	total: 9m 42s	remaining: 19m 22s
1200:	test: 0.7378167	best: 0.7378167 (1200)	total: 11m 46s	remaining: 17m 37s
1400:	test: 0.7381992	best: 0.7381992 (1400)	total: 13m 44s	remaining: 15m 40s
1600:	test: 0.7382216	best: 0.7382384 (1594)	total: 15m 38s	remaining: 13m 39s
1800:	test: 0.7383253	best: 0.7383273 (1799)	total: 17m 33s	remaining: 11m 41s
2000:	test: 0.7382706	best: 0.7383475 (1841)	total: 19m 30s	remaining: 9m 44s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7383475277
bestIteration = 1841

Shrink model to first 1842 iterations.
Fold AUC: 0.73835

===== FOLD 1 =====
0:	test: 0.6858630	best: 0.6858630 (0)	total: 769ms	remaining: 38m 27s
200:	test: 0.7292147	best: 0.7292147 (200)	total: 2m 28s	remaining: 34m 26s
400:	test: 0.7354427	best: 0.7354427 (400)	total: 4m 56s	remaining: 32m 2s
600:	test: 0.7390293	best: 0.7390293 (600)	total: 7m 18s	remaining: 29m 9s
800:	test: 0.7409922	best: 0.7410020 (799)	total: 9m 26s	remaining: 25m 54s
1000:	test: 0.7417422	best: 0.7417422 (1000)	total: 11m 38s	remaining: 23m 15s
1200:	test: 0.7419853	best: 0.7419853 (1200)	total: 13m 48s	remaining: 20m 41s
1400:	test: 0.7420891	best: 0.7420989 (1384)	total: 15m 54s	remaining: 18m 9s
1600:	test: 0.7420953	best: 0.7421539 (1470)	total: 17m 59s	remaining: 15m 43s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7421539393
bestIteration = 1470

Shrink model to first 1471 iterations.
Fold AUC: 0.74215

===== FOLD 2 =====
0:	test: 0.6818253	best: 0.6818253 (0)	total: 585ms	remaining: 29m 14s
200:	test: 0.7251198	best: 0.7251198 (200)	total: 1m 59s	remaining: 27m 49s
400:	test: 0.7315786	best: 0.7315786 (400)	total: 3m 56s	remaining: 25m 30s
600:	test: 0.7353441	best: 0.7353441 (600)	total: 5m 58s	remaining: 23m 51s
800:	test: 0.7373855	best: 0.7373855 (800)	total: 8m 8s	remaining: 22m 19s
1000:	test: 0.7385307	best: 0.7385352 (999)	total: 10m 12s	remaining: 20m 22s
1200:	test: 0.7391594	best: 0.7391594 (1200)	total: 12m 13s	remaining: 18m 18s
1400:	test: 0.7393766	best: 0.7393888 (1394)	total: 14m 11s	remaining: 16m 12s
1600:	test: 0.7395343	best: 0.7395680 (1572)	total: 16m 10s	remaining: 14m 7s
1800:	test: 0.7394755	best: 0.7395734 (1642)	total: 18m 8s	remaining: 12m 4s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7395733695
bestIteration = 1642

Shrink model to first 1643 iterations.
Fold AUC: 0.73957

Mean AUC: 0.7400249455095843
OOF AUC: 0.7399910608425422

In [24]:
new_features = [
    "last_vs_prev_util",
    "last_vs_prev_paym",
    "util_rank",
    "paym_rank",
    "last_vs_last3_util",
    "last_vs_last3_paym",
    "last_vs_std_util",
    "last_vs_std_paym",
    "last_util_x_std",
    "last_paym_x_std",
    "last_vs_mean_util_x_std",
    "last_vs_mean_paym_x_std",
]

In [27]:
feature_importance = pd.DataFrame({
    "feature": X.columns,
    "importance": model.get_feature_importance()
})

# только новые фичи
new_feat_importance = feature_importance[
    feature_importance["feature"].isin(new_features)
].sort_values("importance", ascending=False)

print(new_feat_importance)

                     feature  importance
152         last_vs_std_paym    0.831587
151         last_vs_std_util    0.694093
155  last_vs_mean_util_x_std    0.605057
156  last_vs_mean_paym_x_std    0.483869
154          last_paym_x_std    0.380049
153          last_util_x_std    0.254936

In [28]:
total_importance = feature_importance["importance"].sum()
new_importance = new_feat_importance["importance"].sum()

print("New features total importance:", new_importance)
print("Share of total importance:", new_importance / total_importance)

New features total importance: 3.249591577906246
Share of total importance: 0.03249591577906244

In [29]:
for col in new_features:
    if col in X.columns:
        auc = roc_auc_score(y, X[col])
        print(f"{col}: {auc:.5f}")

last_vs_std_util: 0.49264
last_vs_std_paym: 0.49813
last_util_x_std: 0.45512
last_paym_x_std: 0.47488
last_vs_mean_util_x_std: 0.54280
last_vs_mean_paym_x_std: 0.47256

# 6. Final Model

This section evaluates an alternative approach provided externally.

Important:
The experiment is included for comparison purposes only.
It demonstrates that performance improvements can be achieved by altering data assumptions.

**Final ensemble AUC: ~0.742**

## списки фич, параметры моделей

In [4]:
xgb_features = [
    # --- core payment behavior ---
    "enc_paym_0_mean", "enc_paym_1_mean", "enc_paym_2_mean", "enc_paym_3_mean",
    "enc_paym_4_mean", "enc_paym_5_mean", "enc_paym_6_mean", "enc_paym_7_mean",
    "enc_paym_8_mean", "enc_paym_9_mean", "enc_paym_10_mean", "enc_paym_11_mean",
    "enc_paym_12_mean", "enc_paym_13_mean", "enc_paym_14_mean", "enc_paym_15_mean",
    "enc_paym_16_mean", "enc_paym_17_mean", "enc_paym_18_mean", "enc_paym_19_mean",
    "enc_paym_20_mean", "enc_paym_21_mean", "enc_paym_22_mean", "enc_paym_23_mean",

    # --- sums ---
    "enc_paym_0_sum", "enc_paym_1_sum", "enc_paym_2_sum", "enc_paym_3_sum",
    "enc_paym_4_sum", "enc_paym_5_sum", "enc_paym_6_sum", "enc_paym_7_sum",
    "enc_paym_8_sum", "enc_paym_9_sum", "enc_paym_10_sum", "enc_paym_11_sum",
    "enc_paym_19_sum", "enc_paym_20_sum", "enc_paym_21_sum", "enc_paym_22_sum",
    "enc_paym_23_sum",

    # --- max ---
    "enc_paym_0_max", "enc_paym_1_max",

    # --- behavioral aggregates ---
    "client_mean_bad_months_per_product",
    "client_mean_nonzero_paym_share",
    "client_mean_weighted_paym_score",
    "client_mean_paym_status",
    "client_mean_severe_bad_months",
    "client_max_weighted_paym_score",
    "client_worst_loan_max",

    # --- advanced behavior ---
    "recent_bad_ratio_max",
    "decayed_paym_score_mean",
    "decayed_paym_score_max",
    "worst_paym_ever",

    # --- dynamics ---
    "paym_std",
    "paym_switches",
    "paym_trend_lr",
    "paym_trend_abs",

    # --- relative ---
    "recent_vs_old",
    "recent_vs_old_early",
    "last_vs_mean",

    # --- NEW (самое важное) ---
    "last_vs_prev_util_last",
    "last_vs_prev_paym_last",
    "last_vs_last3_util_last",
    "last_vs_last3_paym_last",

    # --- ranks ---
    "util_rank_last",
    "paym_rank_last",

    # --- normalized ---
    "last_vs_std_util",
    "last_vs_std_paym",

    # --- interactions ---
    "last_util_x_std",
    "last_paym_x_std",
    "last_vs_mean_util_x_std",
    "last_vs_mean_paym_x_std",
]

lgb_features = [
    # --- ratios ---
    "bad_to_total_ratio",
    "util_per_loan",
    "util_stability",

    # --- credit structure ---
    "pre_loans_credit_cost_rate_mean",
    "pre_loans_outstanding_mean",
    "pre_loans_outstanding_max",
    "pre_loans_credit_limit_mean",
    "pre_loans_credit_limit_max",
    "pre_loans_next_pay_summ_mean",
    "pre_loans_next_pay_summ_max",
    "pre_loans_max_overdue_sum_max",

    # --- time ---
    "pre_since_opened_min",
    "pre_since_opened_max",
    "pre_since_opened_mean",
    "pre_since_confirmed_min",
    "pre_since_confirmed_max",
    "pre_since_confirmed_mean",

    "pre_pterm_min",
    "pre_pterm_max",
    "pre_pterm_mean",
    "pre_fterm_min",
    "pre_fterm_max",
    "pre_fterm_mean",

    "pre_till_pclose_min",
    "pre_till_pclose_max",
    "pre_till_fclose_min",
    "pre_till_fclose_max",

    # --- utilization ---
    "pre_util_mean",
    "pre_util_max",
    "mean_utilization_ratio_max",
    "max_utilization_ratio_max",
    "client_util_std_max",

    # --- flags ---
    "pclose_flag_mean",
    "fclose_flag_mean",

    # --- categorical ---
    "enc_loans_credit_type_nunique",
    "enc_loans_account_holder_type_nunique",
    "enc_loans_credit_status_nunique",
    "enc_loans_account_cur_nunique",

    # --- counts ---
    "pre_loans5_sum",
    "pre_loans530_sum",
    "client_products_count",
    "client_products_count_max",

    # --- zero ---
    "is_zero_util_mean",
    "is_zero_loans5_mean",
    "is_zero_loans5_sum",
    "is_zero_loans530_mean",
    "is_zero_loans530_sum",
    "is_zero_loans3060_mean",
    "is_zero_loans6090_mean",
    "is_zero_loans90_mean",
    "is_zero_over2limit_mean",
    "is_zero_maxover2limit_mean",

    # --- limits ---
    "pre_over2limit_max",

    # --- client ---
    "max_credit_share_max",
    "max_credit_share",

    # --- last/worst loans (как объекты) ---
    "worst_loan_paym_mean",
    "worst_loan_paym_max",
    "worst_loan_util",
    "worst_loan_overdue",
    "worst_loan_outstanding",
    "worst_loan_credit_limit",
    "worst_loan_overdue_to_limit",

    "last_loan_paym_mean",
    "last_loan_paym_max",
    "last_loan_util",
    "last_loan_overdue",
    "last_loan_outstanding",

    # --- dispersion ---
    "loan_paym_std",
    "loan_util_std",
    "loan_overdue_std",
    "loan_paym_max",
    "loan_util_max",
    "loan_util_mean",
    "loan_overdue_max",
    "loan_overdue_mean",

    "loan_paym_max_minus_mean",
    "loan_util_max_minus_mean",
    "loan_overdue_max_minus_mean",

    # --- relations ---
    "last_vs_mean_util",
    "last_vs_mean_paym",
    "last_vs_worst_paym",
    "worst_loan_util_to_mean_util",

    # --- misc ---
    "last_paym_status_max",
]

In [7]:
cat_params = {
    'iterations': 3000,
    'depth': 8,
    'learning_rate': 0.03,
    'l2_leaf_reg': 7,
    'loss_function': 'Logloss',
    'eval_metric': 'AUC',
    'class_weights': class_weights_dict,
    'early_stopping_rounds': 200,
    'verbose': 200
}

lgb_params = {
    'n_estimators': 5000,
    'num_leaves': 31,
    'colsample_bytree': 0.7,
    'min_child_samples': 50,
    'subsample': 0.7,
    'learning_rate': 0.03,
    'max_depth': -1,
    'random_state': 42,
    'class_weight': class_weights_dict,
    'verbosity': -1
}

pos_weight = class_weights_dict[1] / class_weights_dict[0]
xgb_params = {
    'n_estimators': 5000,
    'learning_rate': 0.03,
    'max_depth': 6,
    'reg_lambda': 10,
    'reg_alpha': 0,
    'subsample': 0.8,
    'colsample_bytree': 0.8,
    'eval_metric': 'auc',
    'random_state': 42,
    'scale_pos_weight': pos_weight,
    'early_stopping_rounds': 200,
    'verbosity': 1
}

## modeling

In [8]:
X = data.drop(['flag', 'id'], axis=1)
X_lgb = data[lgb_features]
X_xgb = data[xgb_features]

y = data["flag"]

X_np = X.to_numpy(dtype=np.float32)
X_lgb_np = X_lgb.to_numpy(dtype=np.float32)
X_xgb_np = X_xgb.to_numpy(dtype=np.float32)
y_np = y.to_numpy(dtype=np.int8)

print(set(lgb_features) & set(xgb_features))

print(X_lgb.shape)
print(X_xgb.shape)

set()
(3000000, 83)
(3000000, 73)

In [9]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

oof_cat = np.zeros(len(X))
oof_lgb = np.zeros(len(X))
oof_xgb = np.zeros(len(X))

cat_models_auc = []
lgb_models_auc = []
xgb_models_auc = []

for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):
    print(f"\n========== FOLD {fold} ==========")

    X_train, X_val = X_np[train_idx], X_np[val_idx]
    X_train_lgb, X_val_lgb = X_lgb_np[train_idx], X_lgb_np[val_idx]
    X_train_xgb, X_val_xgb = X_xgb_np[train_idx], X_xgb_np[val_idx]
    y_train, y_val = y_np[train_idx], y_np[val_idx]

    # ===== Обработка inf =====
    for arr_train, arr_val in [(X_train, X_val), (X_train_lgb, X_val_lgb), (X_train_xgb, X_val_xgb)]:
        for i in range(arr_train.shape[1]):
            col_train = arr_train[:, i]
            col_val = arr_val[:, i]

            median_val = np.nanmedian(col_train[np.isfinite(col_train)])

            col_train[~np.isfinite(col_train)] = median_val
            col_val[~np.isfinite(col_val)] = median_val

    # ===== CatBoost =====
    cat_model = CatBoostClassifier(**cat_params)
    cat_model.fit(
        X_train, y_train,
        eval_set=(X_val, y_val),
        use_best_model=True,
        verbose=200
    )

    oof_cat[val_idx] = cat_model.predict_proba(X_val)[:, 1]
    auc_cat = roc_auc_score(y_val, oof_cat[val_idx])
    best_iter_cat = cat_model.get_best_iteration()

    print(f"[CatBoost]  AUC: {auc_cat:.6f} | best_iter: {best_iter_cat}")

    cat_models_auc.append((auc_cat, cat_model))

    # ===== LightGBM =====
    lgb_model = lgb.LGBMClassifier(**lgb_params)
    lgb_model.fit(
        X_train_lgb, y_train,
        eval_set=[(X_val_lgb, y_val)],
        eval_metric='auc',
        callbacks=[
            lgb.early_stopping(200),
            lgb.log_evaluation(200)
        ]
    )

    oof_lgb[val_idx] = lgb_model.predict_proba(X_val_lgb)[:, 1]
    auc_lgb = roc_auc_score(y_val, oof_lgb[val_idx])
    best_iter_lgb = lgb_model.best_iteration_

    print(f"[LightGBM] AUC: {auc_lgb:.6f} | best_iter: {best_iter_lgb}")

    lgb_models_auc.append((auc_lgb, lgb_model))

    # ===== XGBoost =====
    xgb_model = xgb.XGBClassifier(**xgb_params)
    xgb_model.fit(
        X_train_xgb, y_train,
        eval_set=[(X_val_xgb, y_val)],
        verbose=200
    )

    oof_xgb[val_idx] = xgb_model.predict_proba(X_val_xgb)[:, 1]
    auc_xgb = roc_auc_score(y_val, oof_xgb[val_idx])
    best_iter_xgb = xgb_model.best_iteration

    print(f"[XGBoost]  AUC: {auc_xgb:.6f} | best_iter: {best_iter_xgb}")

    xgb_models_auc.append((auc_xgb, xgb_model))


print("\n========== OOF RESULTS ==========")
print("CatBoost AUC:", roc_auc_score(y, oof_cat))
print("LightGBM AUC:", roc_auc_score(y, oof_lgb))
print("XGBoost AUC:", roc_auc_score(y, oof_xgb))


# ===== STACKING =====
stack_X = np.vstack([oof_cat, oof_lgb, oof_xgb]).T
stack_oof = np.zeros(len(X))

for fold, (train_idx, val_idx) in enumerate(skf.split(stack_X, y)):
    print(f"\n===== META FOLD {fold} =====")

    X_train_meta, X_val_meta = stack_X[train_idx], stack_X[val_idx]
    y_train_meta, y_val_meta = y.iloc[train_idx], y.iloc[val_idx]

    meta_model = CatBoostClassifier(
        iterations=1000,
        depth=6,
        l2_leaf_reg=5,
        learning_rate=0.03,
        loss_function='Logloss',
        eval_metric='AUC',
        iterations=2000,
        verbose=200
    )

    meta_model.fit(
        X_train_meta, y_train_meta,
        eval_set=(X_val_meta, y_val_meta),
        use_best_model=True
    )

    stack_oof[val_idx] = meta_model.predict_proba(X_val_meta)[:, 1]
    auc_meta = roc_auc_score(y_val_meta, stack_oof[val_idx])

    print(f"[META] AUC: {auc_meta:.6f}")


print("\n========== FINAL ==========")
print("STACKING AUC:", roc_auc_score(y, stack_oof))

========== FOLD 0 ==========
0:	test: 0.6807794	best: 0.6807794 (0)	total: 954ms	remaining: 47m 40s
200:	test: 0.7260924	best: 0.7260924 (200)	total: 2m 32s	remaining: 35m 18s
400:	test: 0.7323657	best: 0.7323657 (400)	total: 4m 53s	remaining: 31m 41s
600:	test: 0.7362737	best: 0.7362737 (600)	total: 7m 4s	remaining: 28m 15s
800:	test: 0.7383358	best: 0.7383358 (800)	total: 9m 27s	remaining: 25m 57s
1000:	test: 0.7394563	best: 0.7394586 (999)	total: 11m 56s	remaining: 23m 51s
1200:	test: 0.7401155	best: 0.7401364 (1196)	total: 14m 19s	remaining: 21m 27s
1400:	test: 0.7403993	best: 0.7403993 (1400)	total: 16m 46s	remaining: 19m 8s
1600:	test: 0.7405992	best: 0.7406630 (1577)	total: 19m 11s	remaining: 16m 45s
1800:	test: 0.7406357	best: 0.7406761 (1654)	total: 21m 38s	remaining: 14m 24s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7406760928
bestIteration = 1654

Shrink model to first 1655 iterations.
[CatBoost]  AUC: 0.740676 | best_iter: 1654
Training until validation scores don't improve for 200 rounds
[200]	valid_0's auc: 0.729548	valid_0's binary_logloss: 0.607803
[400]	valid_0's auc: 0.735495	valid_0's binary_logloss: 0.599392
[600]	valid_0's auc: 0.73713	valid_0's binary_logloss: 0.594444
[800]	valid_0's auc: 0.73791	valid_0's binary_logloss: 0.59022
[1000]	valid_0's auc: 0.738278	valid_0's binary_logloss: 0.586358
[1200]	valid_0's auc: 0.738488	valid_0's binary_logloss: 0.582701
[1400]	valid_0's auc: 0.738704	valid_0's binary_logloss: 0.579258
[1600]	valid_0's auc: 0.738694	valid_0's binary_logloss: 0.575832
Early stopping, best iteration is:
[1468]	valid_0's auc: 0.738766	valid_0's binary_logloss: 0.578074

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] AUC: 0.738766 | best_iter: 1468
[0]	validation_0-auc:0.65967
[200]	validation_0-auc:0.69535
[400]	validation_0-auc:0.69893
[600]	validation_0-auc:0.70018
[800]	validation_0-auc:0.70083
[1000]	validation_0-auc:0.70111
[1200]	validation_0-auc:0.70104
[1322]	validation_0-auc:0.70111
[XGBoost]  AUC: 0.701186 | best_iter: 1122

========== FOLD 1 ==========
0:	test: 0.6778211	best: 0.6778211 (0)	total: 696ms	remaining: 34m 45s
200:	test: 0.7239287	best: 0.7239287 (200)	total: 2m 22s	remaining: 33m 8s
400:	test: 0.7304349	best: 0.7304349 (400)	total: 4m 44s	remaining: 30m 42s
600:	test: 0.7344030	best: 0.7344030 (600)	total: 7m 8s	remaining: 28m 30s
800:	test: 0.7363293	best: 0.7363293 (800)	total: 9m 27s	remaining: 25m 58s
1000:	test: 0.7375687	best: 0.7375687 (1000)	total: 11m 43s	remaining: 23m 25s
1200:	test: 0.7383153	best: 0.7383153 (1200)	total: 13m 57s	remaining: 20m 54s
1400:	test: 0.7387523	best: 0.7387523 (1400)	total: 16m 20s	remaining: 18m 38s
1600:	test: 0.7388154	best: 0.7388813 (1550)	total: 18m 41s	remaining: 16m 19s
1800:	test: 0.7389407	best: 0.7389407 (1800)	total: 20m 58s	remaining: 13m 57s
2000:	test: 0.7389634	best: 0.7390444 (1898)	total: 23m 22s	remaining: 11m 40s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7390444364
bestIteration = 1898

Shrink model to first 1899 iterations.
[CatBoost]  AUC: 0.739044 | best_iter: 1898
Training until validation scores don't improve for 200 rounds
[200]	valid_0's auc: 0.727253	valid_0's binary_logloss: 0.607202
[400]	valid_0's auc: 0.733543	valid_0's binary_logloss: 0.598543
[600]	valid_0's auc: 0.73519	valid_0's binary_logloss: 0.593584
[800]	valid_0's auc: 0.736087	valid_0's binary_logloss: 0.589233
[1000]	valid_0's auc: 0.736535	valid_0's binary_logloss: 0.585343
[1200]	valid_0's auc: 0.736727	valid_0's binary_logloss: 0.581792
[1400]	valid_0's auc: 0.736901	valid_0's binary_logloss: 0.578299
[1600]	valid_0's auc: 0.737015	valid_0's binary_logloss: 0.574941
Early stopping, best iteration is:
[1571]	valid_0's auc: 0.737041	valid_0's binary_logloss: 0.575439

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] AUC: 0.737041 | best_iter: 1571
[0]	validation_0-auc:0.65937
[200]	validation_0-auc:0.69538
[400]	validation_0-auc:0.69889
[600]	validation_0-auc:0.70018
[800]	validation_0-auc:0.70066
[1000]	validation_0-auc:0.70092
[1200]	validation_0-auc:0.70103
[1400]	validation_0-auc:0.70114
[1600]	validation_0-auc:0.70103
[1627]	validation_0-auc:0.70100
[XGBoost]  AUC: 0.701175 | best_iter: 1427

========== FOLD 2 ==========
0:	test: 0.6849727	best: 0.6849727 (0)	total: 656ms	remaining: 32m 46s
200:	test: 0.7309658	best: 0.7309658 (200)	total: 2m 21s	remaining: 32m 48s
400:	test: 0.7371710	best: 0.7371710 (400)	total: 4m 41s	remaining: 30m 27s
600:	test: 0.7407115	best: 0.7407115 (600)	total: 7m 7s	remaining: 28m 26s
800:	test: 0.7427149	best: 0.7427149 (800)	total: 9m 28s	remaining: 26m 2s
1000:	test: 0.7436643	best: 0.7436666 (999)	total: 11m 47s	remaining: 23m 32s
1200:	test: 0.7441927	best: 0.7441927 (1200)	total: 14m 3s	remaining: 21m 2s
1400:	test: 0.7443951	best: 0.7444217 (1320)	total: 16m 21s	remaining: 18m 40s
1600:	test: 0.7444916	best: 0.7445192 (1555)	total: 18m 37s	remaining: 16m 16s
1800:	test: 0.7444849	best: 0.7445337 (1665)	total: 21m 3s	remaining: 14m 1s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7445337115
bestIteration = 1665

Shrink model to first 1666 iterations.
[CatBoost]  AUC: 0.744534 | best_iter: 1665
Training until validation scores don't improve for 200 rounds
[200]	valid_0's auc: 0.733218	valid_0's binary_logloss: 0.608959
[400]	valid_0's auc: 0.739086	valid_0's binary_logloss: 0.600286
[600]	valid_0's auc: 0.740555	valid_0's binary_logloss: 0.595407
[800]	valid_0's auc: 0.741197	valid_0's binary_logloss: 0.591201
[1000]	valid_0's auc: 0.741642	valid_0's binary_logloss: 0.587339
[1200]	valid_0's auc: 0.741793	valid_0's binary_logloss: 0.583689
[1400]	valid_0's auc: 0.741987	valid_0's binary_logloss: 0.580254
[1600]	valid_0's auc: 0.742172	valid_0's binary_logloss: 0.576875
[1800]	valid_0's auc: 0.742095	valid_0's binary_logloss: 0.573563
Early stopping, best iteration is:
[1616]	valid_0's auc: 0.742183	valid_0's binary_logloss: 0.576612

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] AUC: 0.742183 | best_iter: 1616
[0]	validation_0-auc:0.66269
[200]	validation_0-auc:0.69933
[400]	validation_0-auc:0.70312
[600]	validation_0-auc:0.70440
[800]	validation_0-auc:0.70481
[1000]	validation_0-auc:0.70483
[1127]	validation_0-auc:0.70482
[XGBoost]  AUC: 0.704855 | best_iter: 927

========== FOLD 3 ==========
0:	test: 0.6796653	best: 0.6796653 (0)	total: 750ms	remaining: 37m 28s
200:	test: 0.7252350	best: 0.7252350 (200)	total: 2m 25s	remaining: 33m 42s
400:	test: 0.7318043	best: 0.7318043 (400)	total: 4m 54s	remaining: 31m 46s
600:	test: 0.7358954	best: 0.7358954 (600)	total: 7m 25s	remaining: 29m 37s
800:	test: 0.7380505	best: 0.7380505 (800)	total: 9m 53s	remaining: 27m 9s
1000:	test: 0.7391575	best: 0.7391575 (1000)	total: 12m 13s	remaining: 24m 24s
1200:	test: 0.7399632	best: 0.7399684 (1199)	total: 14m 36s	remaining: 21m 53s
1400:	test: 0.7403326	best: 0.7403326 (1400)	total: 17m 4s	remaining: 19m 29s
1600:	test: 0.7405994	best: 0.7406350 (1566)	total: 19m 26s	remaining: 16m 59s
1800:	test: 0.7406980	best: 0.7407294 (1793)	total: 21m 48s	remaining: 14m 31s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7407294106
bestIteration = 1793

Shrink model to first 1794 iterations.
[CatBoost]  AUC: 0.740729 | best_iter: 1793
Training until validation scores don't improve for 200 rounds
[200]	valid_0's auc: 0.727651	valid_0's binary_logloss: 0.607031
[400]	valid_0's auc: 0.734094	valid_0's binary_logloss: 0.598576
[600]	valid_0's auc: 0.735891	valid_0's binary_logloss: 0.593696
[800]	valid_0's auc: 0.736662	valid_0's binary_logloss: 0.589529
[1000]	valid_0's auc: 0.737124	valid_0's binary_logloss: 0.585637
[1200]	valid_0's auc: 0.737305	valid_0's binary_logloss: 0.582012
[1400]	valid_0's auc: 0.737451	valid_0's binary_logloss: 0.578521
[1600]	valid_0's auc: 0.737586	valid_0's binary_logloss: 0.575073
[1800]	valid_0's auc: 0.737645	valid_0's binary_logloss: 0.571794
Early stopping, best iteration is:
[1750]	valid_0's auc: 0.737656	valid_0's binary_logloss: 0.572607

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] AUC: 0.737656 | best_iter: 1750
[0]	validation_0-auc:0.65823
[200]	validation_0-auc:0.69489
[400]	validation_0-auc:0.69904
[600]	validation_0-auc:0.70022
[800]	validation_0-auc:0.70080
[1000]	validation_0-auc:0.70100
[1200]	validation_0-auc:0.70105
[1232]	validation_0-auc:0.70103
[XGBoost]  AUC: 0.701085 | best_iter: 1032

========== FOLD 4 ==========
0:	test: 0.6792036	best: 0.6792036 (0)	total: 728ms	remaining: 36m 23s
200:	test: 0.7261446	best: 0.7261446 (200)	total: 2m 33s	remaining: 35m 31s
400:	test: 0.7327444	best: 0.7327444 (400)	total: 5m 2s	remaining: 32m 39s
600:	test: 0.7364004	best: 0.7364004 (600)	total: 7m 32s	remaining: 30m 4s
800:	test: 0.7384076	best: 0.7384090 (799)	total: 10m 6s	remaining: 27m 45s
1000:	test: 0.7396052	best: 0.7396052 (1000)	total: 12m 30s	remaining: 24m 59s
1200:	test: 0.7403379	best: 0.7403474 (1199)	total: 14m 50s	remaining: 22m 13s
1400:	test: 0.7407401	best: 0.7407436 (1395)	total: 17m 10s	remaining: 19m 36s
1600:	test: 0.7410002	best: 0.7410002 (1600)	total: 19m 28s	remaining: 17m 1s
1800:	test: 0.7410182	best: 0.7410792 (1735)	total: 21m 43s	remaining: 14m 27s
2000:	test: 0.7410965	best: 0.7411844 (1946)	total: 23m 58s	remaining: 11m 57s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7411844164
bestIteration = 1946

Shrink model to first 1947 iterations.
[CatBoost]  AUC: 0.741184 | best_iter: 1946
Training until validation scores don't improve for 200 rounds
[200]	valid_0's auc: 0.7299	valid_0's binary_logloss: 0.607578
[400]	valid_0's auc: 0.73584	valid_0's binary_logloss: 0.599146
[600]	valid_0's auc: 0.737432	valid_0's binary_logloss: 0.594195
[800]	valid_0's auc: 0.738206	valid_0's binary_logloss: 0.589893
[1000]	valid_0's auc: 0.738703	valid_0's binary_logloss: 0.585919
[1200]	valid_0's auc: 0.73896	valid_0's binary_logloss: 0.582231
[1400]	valid_0's auc: 0.738992	valid_0's binary_logloss: 0.578799
[1600]	valid_0's auc: 0.739057	valid_0's binary_logloss: 0.575375
[1800]	valid_0's auc: 0.739105	valid_0's binary_logloss: 0.57205
Early stopping, best iteration is:
[1709]	valid_0's auc: 0.739163	valid_0's binary_logloss: 0.573489

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] AUC: 0.739163 | best_iter: 1709
[0]	validation_0-auc:0.66032
[200]	validation_0-auc:0.69634
[400]	validation_0-auc:0.70043
[600]	validation_0-auc:0.70176
[800]	validation_0-auc:0.70225
[1000]	validation_0-auc:0.70255
[1200]	validation_0-auc:0.70254
[1247]	validation_0-auc:0.70251
[XGBoost]  AUC: 0.702564 | best_iter: 1047

========== OOF RESULTS ==========
CatBoost AUC: 0.7412106295439781
LightGBM AUC: 0.7389532762022821
XGBoost AUC: 0.7021392043744689

SyntaxError: keyword argument repeated: iterations (394158217.py, line 107)

In [11]:
# ===== STACKING =====
stack_X = np.vstack([oof_cat, oof_lgb, oof_xgb]).T
stack_oof = np.zeros(len(X))

for fold, (train_idx, val_idx) in enumerate(skf.split(stack_X, y)):
    print(f"\n===== META FOLD {fold} =====")

    X_train_meta, X_val_meta = stack_X[train_idx], stack_X[val_idx]
    y_train_meta, y_val_meta = y.iloc[train_idx], y.iloc[val_idx]

    meta_model = CatBoostClassifier(
        iterations=2000,
        depth=6,
        l2_leaf_reg=5,
        learning_rate=0.03,
        loss_function='Logloss',
        eval_metric='AUC',
        verbose=200
    )

    meta_model.fit(
        X_train_meta, y_train_meta,
        eval_set=(X_val_meta, y_val_meta),
        use_best_model=True
    )

    stack_oof[val_idx] = meta_model.predict_proba(X_val_meta)[:, 1]
    auc_meta = roc_auc_score(y_val_meta, stack_oof[val_idx])

    print(f"[META] AUC: {auc_meta:.6f}")

print("\n========== FINAL ==========")
print("STACKING AUC:", roc_auc_score(y, stack_oof))

===== META FOLD 0 =====
0:	test: 0.7226107	best: 0.7226107 (0)	total: 235ms	remaining: 7m 49s
200:	test: 0.7413465	best: 0.7413465 (200)	total: 46.6s	remaining: 6m 56s
400:	test: 0.7415334	best: 0.7415345 (399)	total: 1m 34s	remaining: 6m 15s
600:	test: 0.7415378	best: 0.7415421 (549)	total: 2m 20s	remaining: 5m 27s
800:	test: 0.7415390	best: 0.7415446 (755)	total: 3m 7s	remaining: 4m 40s
1000:	test: 0.7414953	best: 0.7415446 (755)	total: 3m 53s	remaining: 3m 53s
1200:	test: 0.7414522	best: 0.7415446 (755)	total: 4m 41s	remaining: 3m 7s
1400:	test: 0.7413729	best: 0.7415446 (755)	total: 5m 30s	remaining: 2m 21s
1600:	test: 0.7413042	best: 0.7415446 (755)	total: 6m 19s	remaining: 1m 34s
1800:	test: 0.7412376	best: 0.7415446 (755)	total: 7m 7s	remaining: 47.3s
1999:	test: 0.7411884	best: 0.7415446 (755)	total: 7m 55s	remaining: 0us

bestTest = 0.7415446216
bestIteration = 755

Shrink model to first 756 iterations.
[META] AUC: 0.741545

===== META FOLD 1 =====
0:	test: 0.7210305	best: 0.7210305 (0)	total: 236ms	remaining: 7m 51s
200:	test: 0.7398569	best: 0.7398578 (199)	total: 47s	remaining: 7m
400:	test: 0.7399534	best: 0.7399573 (325)	total: 1m 33s	remaining: 6m 13s
600:	test: 0.7399241	best: 0.7399611 (427)	total: 2m 19s	remaining: 5m 25s
800:	test: 0.7398971	best: 0.7399611 (427)	total: 3m 6s	remaining: 4m 39s
1000:	test: 0.7398389	best: 0.7399611 (427)	total: 3m 54s	remaining: 3m 54s
1200:	test: 0.7397699	best: 0.7399611 (427)	total: 4m 43s	remaining: 3m 8s
1400:	test: 0.7397128	best: 0.7399611 (427)	total: 5m 30s	remaining: 2m 21s
1600:	test: 0.7396599	best: 0.7399611 (427)	total: 6m 18s	remaining: 1m 34s
1800:	test: 0.7395777	best: 0.7399611 (427)	total: 7m 6s	remaining: 47.1s
1999:	test: 0.7394834	best: 0.7399611 (427)	total: 7m 55s	remaining: 0us

bestTest = 0.7399610646
bestIteration = 427

Shrink model to first 428 iterations.
[META] AUC: 0.739961

===== META FOLD 2 =====
0:	test: 0.7258727	best: 0.7258727 (0)	total: 261ms	remaining: 8m 41s
200:	test: 0.7451633	best: 0.7451633 (200)	total: 49.1s	remaining: 7m 19s
400:	test: 0.7452866	best: 0.7452883 (395)	total: 1m 37s	remaining: 6m 28s
600:	test: 0.7453032	best: 0.7453131 (550)	total: 2m 24s	remaining: 5m 37s
800:	test: 0.7452922	best: 0.7453131 (550)	total: 3m 9s	remaining: 4m 43s
1000:	test: 0.7452543	best: 0.7453131 (550)	total: 3m 54s	remaining: 3m 53s
1200:	test: 0.7451994	best: 0.7453131 (550)	total: 4m 39s	remaining: 3m 6s
1400:	test: 0.7451333	best: 0.7453131 (550)	total: 5m 26s	remaining: 2m 19s
1600:	test: 0.7451112	best: 0.7453131 (550)	total: 6m 15s	remaining: 1m 33s
1800:	test: 0.7450983	best: 0.7453131 (550)	total: 7m 4s	remaining: 46.9s
1999:	test: 0.7450596	best: 0.7453131 (550)	total: 7m 52s	remaining: 0us

bestTest = 0.7453130839
bestIteration = 550

Shrink model to first 551 iterations.
[META] AUC: 0.745313

===== META FOLD 3 =====
0:	test: 0.7225974	best: 0.7225974 (0)	total: 312ms	remaining: 10m 23s
200:	test: 0.7410094	best: 0.7410094 (200)	total: 49.6s	remaining: 7m 23s
400:	test: 0.7411351	best: 0.7411351 (400)	total: 1m 38s	remaining: 6m 34s
600:	test: 0.7411075	best: 0.7411403 (451)	total: 2m 28s	remaining: 5m 46s
800:	test: 0.7410483	best: 0.7411403 (451)	total: 3m 16s	remaining: 4m 54s
1000:	test: 0.7410168	best: 0.7411403 (451)	total: 4m 5s	remaining: 4m 5s
1200:	test: 0.7409484	best: 0.7411403 (451)	total: 4m 53s	remaining: 3m 15s
1400:	test: 0.7409040	best: 0.7411403 (451)	total: 5m 42s	remaining: 2m 26s
1600:	test: 0.7408476	best: 0.7411403 (451)	total: 6m 31s	remaining: 1m 37s
1800:	test: 0.7407719	best: 0.7411403 (451)	total: 7m 21s	remaining: 48.8s
1999:	test: 0.7407026	best: 0.7411403 (451)	total: 8m 10s	remaining: 0us

bestTest = 0.7411403235
bestIteration = 451

Shrink model to first 452 iterations.
[META] AUC: 0.741140

===== META FOLD 4 =====
0:	test: 0.7232612	best: 0.7232612 (0)	total: 249ms	remaining: 8m 18s
200:	test: 0.7421225	best: 0.7421225 (200)	total: 48.4s	remaining: 7m 12s
400:	test: 0.7422922	best: 0.7422923 (398)	total: 1m 36s	remaining: 6m 26s
600:	test: 0.7423089	best: 0.7423089 (600)	total: 2m 24s	remaining: 5m 36s
800:	test: 0.7422799	best: 0.7423108 (615)	total: 3m 11s	remaining: 4m 46s
1000:	test: 0.7422595	best: 0.7423108 (615)	total: 3m 58s	remaining: 3m 58s
1200:	test: 0.7422401	best: 0.7423108 (615)	total: 4m 46s	remaining: 3m 10s
1400:	test: 0.7421905	best: 0.7423108 (615)	total: 5m 34s	remaining: 2m 23s
1600:	test: 0.7421104	best: 0.7423108 (615)	total: 6m 23s	remaining: 1m 35s
1800:	test: 0.7420690	best: 0.7423108 (615)	total: 7m 12s	remaining: 47.7s
1999:	test: 0.7420080	best: 0.7423108 (615)	total: 8m	remaining: 0us

bestTest = 0.7423108173
bestIteration = 615

Shrink model to first 616 iterations.
[META] AUC: 0.742311

========== FINAL ==========
STACKING AUC: 0.741997520655585

In [15]:
models_dir = "models"
os.makedirs(models_dir, exist_ok=True)

cat_dir = os.path.join(models_dir, "catboost")
lgb_dir = os.path.join(models_dir, "lightgbm")
xgb_dir = os.path.join(models_dir, "xgboost")
meta_dir = os.path.join(models_dir, "meta")

for d in [cat_dir, lgb_dir, xgb_dir, meta_dir]:
    os.makedirs(d, exist_ok=True)

np.save(os.path.join(models_dir, "oof_cat.npy"), oof_cat)
np.save(os.path.join(models_dir, "oof_lgb.npy"), oof_lgb)
np.save(os.path.join(models_dir, "oof_xgb.npy"), oof_xgb)
np.save(os.path.join(models_dir, "oof_stack.npy"), stack_oof)

print("OOF saved")

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

splits = []
for train_idx, val_idx in skf.split(np.zeros(len(y)), y):
    splits.append({
        "train_idx": train_idx.tolist(),
        "val_idx": val_idx.tolist()
    })

with open(os.path.join(models_dir, "splits.json"), "w") as f:
    json.dump(splits, f)

print("Splits saved")

cat_meta = []
lgb_meta = []
xgb_meta = []

for i, (auc, model) in enumerate(cat_models_auc):
    path = os.path.join(cat_dir, f"cat_fold_{i}.cbm")
    model.save_model(path)
    cat_meta.append({"fold": i, "auc": float(auc), "path": path})

for i, (auc, model) in enumerate(lgb_models_auc):
    path = os.path.join(lgb_dir, f"lgb_fold_{i}.pkl")
    joblib.dump(model, path)
    lgb_meta.append({"fold": i, "auc": float(auc), "path": path})

for i, (auc, model) in enumerate(xgb_models_auc):
    path = os.path.join(xgb_dir, f"xgb_fold_{i}.json")
    model.save_model(path)
    xgb_meta.append({"fold": i, "auc": float(auc), "path": path})

meta_model.save_model(os.path.join(meta_dir, "meta_model.cbm"))

print("Models saved")

summary = {
    "cat_auc": float(roc_auc_score(y, oof_cat)),
    "lgb_auc": float(roc_auc_score(y, oof_lgb)),
    "xgb_auc": float(roc_auc_score(y, oof_xgb)),
    "stack_auc": float(roc_auc_score(y, stack_oof)),
    "cat_models": cat_meta,
    "lgb_models": lgb_meta,
    "xgb_models": xgb_meta
}

with open(os.path.join(models_dir, "summary.json"), "w") as f:
    json.dump(summary, f, indent=2)

print("Summary saved")

OOF saved
Splits saved
Models saved
Summary saved

# 7. External Approach Comparison

This section evaluates an alternative approach provided externally.

Important:
The experiment is included for comparison purposes only.
It demonstrates that performance improvements can be achieved by altering data assumptions.

## experiment 20.04

In [3]:
data = pd.read_csv('full_data13.csv')

In [16]:
data_clean = data.drop(data[(data.is_zero_loans90_min == 0) & (data.flag == 0)].index)

In [17]:
mask = (data.is_zero_loans90_min == 0)

subset = data[mask]

print(subset['flag'].value_counts(normalize=True))

flag
0    0.941198
1    0.058802
Name: proportion, dtype: float64

In [18]:
mask_conflict = (data.is_zero_loans90_min == 0) & (data.flag == 0)

conflicts = data[mask_conflict]

print(len(conflicts), len(conflicts) / len(data))

367362 0.122454

In [30]:
def run_cv_catboost(data, target_col='flag', n_splits=3):

    X = data.drop(columns=[target_col])
    y = data[target_col]

    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

    oof_preds = np.zeros(len(data))
    fold_aucs = []

    classes = np.array([0, 1])
    weights = compute_class_weight(class_weight='balanced', classes=classes, y=y)
    class_weights_dict = {0: weights[0], 1: weights[1]}

    cat_params = {
        'iterations': 1500,
        'depth': 6,
        'learning_rate': 0.03,
        'l2_leaf_reg': 7,
        'loss_function': 'Logloss',
        'eval_metric': 'AUC',
        'class_weights': class_weights_dict,
        'early_stopping_rounds': 200,
        'verbose': 200,
        'random_seed': 42
    }

    for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):

        X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

        model = CatBoostClassifier(**cat_params)

        model.fit(
            X_train, y_train,
            eval_set=(X_val, y_val),
            use_best_model=True
        )

        preds = model.predict_proba(X_val)[:, 1]
        oof_preds[val_idx] = preds

        auc = roc_auc_score(y_val, preds)
        fold_aucs.append(auc)

        print(f"Fold {fold}: AUC = {auc:.5f}")

    print("\nMean AUC:", np.mean(fold_aucs))
    print("Std AUC:", np.std(fold_aucs))

    return np.mean(fold_aucs)

In [31]:
print("=== ORIGINAL DATA ===")
auc_original = run_cv_catboost(data)

print("\n=== CLEAN DATA ===")
auc_clean = run_cv_catboost(data_clean)

print("\n=== COMPARISON ===")
print(f"Original AUC: {auc_original:.5f}")
print(f"Clean AUC:    {auc_clean:.5f}")
print(f"Diff:         {auc_clean - auc_original:.5f}")

=== ORIGINAL DATA ===
0:	test: 0.6728527	best: 0.6728527 (0)	total: 442ms	remaining: 11m 2s
200:	test: 0.7200663	best: 0.7200663 (200)	total: 1m 31s	remaining: 9m 48s
400:	test: 0.7278284	best: 0.7278284 (400)	total: 2m 59s	remaining: 8m 11s
600:	test: 0.7327422	best: 0.7327422 (600)	total: 4m 31s	remaining: 6m 46s
800:	test: 0.7356316	best: 0.7356316 (800)	total: 6m 5s	remaining: 5m 19s
1000:	test: 0.7374657	best: 0.7374657 (1000)	total: 7m 37s	remaining: 3m 48s
1200:	test: 0.7386278	best: 0.7386278 (1200)	total: 9m 8s	remaining: 2m 16s
1400:	test: 0.7394504	best: 0.7394504 (1400)	total: 10m 41s	remaining: 45.4s
1499:	test: 0.7396843	best: 0.7396843 (1499)	total: 11m 25s	remaining: 0us

bestTest = 0.7396842998
bestIteration = 1499

Fold 0: AUC = 0.73968
0:	test: 0.6782771	best: 0.6782771 (0)	total: 477ms	remaining: 11m 54s
200:	test: 0.7253948	best: 0.7253948 (200)	total: 1m 32s	remaining: 9m 57s
400:	test: 0.7330897	best: 0.7330897 (400)	total: 3m 5s	remaining: 8m 27s
600:	test: 0.7376643	best: 0.7376643 (600)	total: 4m 41s	remaining: 7m
800:	test: 0.7403970	best: 0.7403970 (800)	total: 6m 13s	remaining: 5m 26s
1000:	test: 0.7420117	best: 0.7420117 (1000)	total: 7m 49s	remaining: 3m 53s
1200:	test: 0.7430235	best: 0.7430235 (1200)	total: 9m 21s	remaining: 2m 19s
1400:	test: 0.7436479	best: 0.7436479 (1400)	total: 10m 52s	remaining: 46.1s
1499:	test: 0.7438280	best: 0.7438280 (1499)	total: 11m 37s	remaining: 0us

bestTest = 0.7438280029
bestIteration = 1499

Fold 1: AUC = 0.74383
0:	test: 0.6748070	best: 0.6748070 (0)	total: 466ms	remaining: 11m 38s
200:	test: 0.7213242	best: 0.7213242 (200)	total: 1m 32s	remaining: 9m 59s
400:	test: 0.7292221	best: 0.7292221 (400)	total: 3m 6s	remaining: 8m 31s
600:	test: 0.7339317	best: 0.7339317 (600)	total: 4m 46s	remaining: 7m 9s
800:	test: 0.7366565	best: 0.7366565 (800)	total: 6m 21s	remaining: 5m 33s
1000:	test: 0.7382695	best: 0.7382695 (1000)	total: 7m 59s	remaining: 3m 58s
1200:	test: 0.7394294	best: 0.7394304 (1198)	total: 9m 32s	remaining: 2m 22s
1400:	test: 0.7403336	best: 0.7403362 (1398)	total: 11m 6s	remaining: 47.1s
1499:	test: 0.7406226	best: 0.7406227 (1498)	total: 11m 51s	remaining: 0us

bestTest = 0.7406227319
bestIteration = 1498

Shrink model to first 1499 iterations.
Fold 2: AUC = 0.74062

Mean AUC: 0.741378344910745
Std AUC: 0.001774031574437327

=== CLEAN DATA ===
0:	test: 0.7357589	best: 0.7357589 (0)	total: 395ms	remaining: 9m 51s
200:	test: 0.7823012	best: 0.7823012 (200)	total: 1m 21s	remaining: 8m 45s
400:	test: 0.7885755	best: 0.7885755 (400)	total: 2m 43s	remaining: 7m 28s
600:	test: 0.7923478	best: 0.7923478 (600)	total: 4m 8s	remaining: 6m 11s
800:	test: 0.7945019	best: 0.7945019 (800)	total: 5m 31s	remaining: 4m 49s
1000:	test: 0.7957221	best: 0.7957221 (1000)	total: 6m 57s	remaining: 3m 28s
1200:	test: 0.7966266	best: 0.7966266 (1200)	total: 8m 26s	remaining: 2m 6s
1400:	test: 0.7971964	best: 0.7971971 (1399)	total: 9m 47s	remaining: 41.5s
1499:	test: 0.7974136	best: 0.7974187 (1495)	total: 10m 28s	remaining: 0us

bestTest = 0.7974187071
bestIteration = 1495

Shrink model to first 1496 iterations.
Fold 0: AUC = 0.79742
0:	test: 0.7381972	best: 0.7381972 (0)	total: 410ms	remaining: 10m 14s
200:	test: 0.7813065	best: 0.7813065 (200)	total: 1m 22s	remaining: 8m 55s
400:	test: 0.7877468	best: 0.7877468 (400)	total: 2m 45s	remaining: 7m 34s
600:	test: 0.7916121	best: 0.7916121 (600)	total: 4m 9s	remaining: 6m 12s
800:	test: 0.7936885	best: 0.7936885 (800)	total: 5m 31s	remaining: 4m 49s
1000:	test: 0.7950169	best: 0.7950169 (1000)	total: 6m 52s	remaining: 3m 25s
1200:	test: 0.7958076	best: 0.7958076 (1200)	total: 8m 14s	remaining: 2m 3s
1400:	test: 0.7963374	best: 0.7963404 (1398)	total: 9m 34s	remaining: 40.6s
1499:	test: 0.7965100	best: 0.7965100 (1499)	total: 10m 14s	remaining: 0us

bestTest = 0.7965100049
bestIteration = 1499

Fold 1: AUC = 0.79651
0:	test: 0.7338836	best: 0.7338836 (0)	total: 401ms	remaining: 10m 1s
200:	test: 0.7804170	best: 0.7804170 (200)	total: 1m 24s	remaining: 9m 7s
400:	test: 0.7873162	best: 0.7873162 (400)	total: 2m 49s	remaining: 7m 43s
600:	test: 0.7913140	best: 0.7913140 (600)	total: 4m 16s	remaining: 6m 23s
800:	test: 0.7935290	best: 0.7935290 (800)	total: 5m 41s	remaining: 4m 57s
1000:	test: 0.7947897	best: 0.7947923 (999)	total: 7m 4s	remaining: 3m 31s
1200:	test: 0.7955842	best: 0.7955842 (1200)	total: 8m 25s	remaining: 2m 5s
1400:	test: 0.7961128	best: 0.7961128 (1400)	total: 9m 46s	remaining: 41.5s
1499:	test: 0.7962479	best: 0.7962516 (1496)	total: 10m 26s	remaining: 0us

bestTest = 0.7962515704
bestIteration = 1496

Shrink model to first 1497 iterations.
Fold 2: AUC = 0.79625

Mean AUC: 0.7967267608254188
Std AUC: 0.0005005259773354833

=== COMPARISON ===
Original AUC: 0.74138
Clean AUC:    0.79673
Diff:         0.05535

In [28]:
print(
    ((data['is_zero_loans90_min'] == 0) & (data['flag'] == 0)).sum()
    / (data['is_zero_loans90_min'] == 0).sum()
)

0.9411984740451894

In [29]:
print("Shape:", data.shape)
print("Memory (MB):", data.memory_usage(deep=True).sum() / 1024**2)

print("\nColumns:", len(data.columns))
print("Target distribution:\n", data['flag'].value_counts(normalize=True))

print("Clean shape:", data_clean.shape)
print("Removed rows:", len(data) - len(data_clean))
print("Removed %:", 1 - len(data_clean) / len(data))

Shape: (3000000, 160)
Memory (MB): 901.222354888916

Columns: 160
Target distribution:
 flag
0    0.964519
1    0.035481
Name: proportion, dtype: float64
Clean shape: (2632638, 160)
Removed rows: 367362
Removed %: 0.12245399999999995

In [24]:
data.groupby('is_zero_loans90_min')['flag'].mean()

is_zero_loans90_min
0    0.058802
1    0.031993
Name: flag, dtype: float64